const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.TiledBg,
		C3.Behaviors.solid,
		C3.Behaviors.Bullet,
		C3.Plugins.Sprite,
		C3.Behaviors.Platform,
		C3.Behaviors.Rotate,
		C3.Plugins.Touch,
		C3.Plugins.Audio,
		C3.Plugins.Browser,
		C3.Plugins.Spritefont2,
		C3.Plugins.LocalStorage,
		C3.Plugins.advert,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Spritefont2.Acts.SetText,
		C3.Behaviors.Bullet.Acts.SetAngleOfMotion,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.Audio.Cnds.IsTagPlaying,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.TiledBg.Cnds.CompareY,
		C3.Plugins.TiledBg.Acts.SetY,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.Sprite.Cnds.IsVisible,
		C3.Plugins.System.Acts.GoToLayout,
		C3.JavaScriptInEvents.Start_sht_Event6_Act3,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Acts.GetItem,
		C3.Plugins.LocalStorage.Cnds.OnItemGet,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.JavaScriptInEvents.Game_sht_Event4_Act10,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Exps.random,
		C3.Behaviors.Bullet.Acts.SetSpeed,
		C3.Behaviors.Bullet.Exps.Speed,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.JavaScriptInEvents.Game_sht_Event18_Act1,
		C3.Plugins.Sprite.Cnds.CompareY,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.Touch.Cnds.OnTouchStart,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Behaviors.Platform.Cnds.IsByWall,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Behaviors.Bullet.Acts.SetEnabled,
		C3.Behaviors.Platform.Acts.SetGravity,
		C3.Behaviors.Rotate.Acts.SetSpeed,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Spritefont2.Acts.SetVisible,
		C3.Plugins.Sprite.Cnds.CompareX,
		C3.Plugins.Sprite.Acts.StopAnim,
		C3.JavaScriptInEvents.Game_sht_Event115_Act10,
		C3.Plugins.Sprite.Acts.StartAnim,
		C3.JavaScriptInEvents.Game_sht_Event116_Act13,
		C3.Plugins.Sprite.Cnds.IsOutsideLayout,
		C3.Plugins.advert.Acts.CreateBanner,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.JavaScriptInEvents.Buy_sht_Event2_Act4,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.Spritefont2.Exps.Text,
		C3.Plugins.advert.Acts.ShowBanner,
		C3.Plugins.advert.Acts.ShowInterstitial,
		C3.Plugins.Browser.Acts.GoToURLWindow,
		C3.Plugins.System.Acts.RestartLayout,
		C3.JavaScriptInEvents.Gui_Event4_Act3
	];
};
self.C3_JsPropNameTable = [
	{Solid: 0},
	{Bullet: 0},
	{BG1: 0},
	{Platform: 0},
	{Rotate: 0},
	{P1: 0},
	{Touch: 0},
	{Saw: 0},
	{forks: 0},
	{Object1: 0},
	{Object2: 0},
	{Star: 0},
	{Audio: 0},
	{Play: 0},
	{Rate: 0},
	{Sound: 0},
	{MoreGames: 0},
	{Replay: 0},
	{Browser: 0},
	{Home: 0},
	{SC: 0},
	{score: 0},
	{HighScore: 0},
	{LocalStorage: 0},
	{StarIcon: 0},
	{StarScore: 0},
	{SHOP: 0},
	{B: 0},
	{B2: 0},
	{twiter: 0},
	{fb: 0},
	{ok: 0},
	{price: 0},
	{BG2: 0},
	{PauseBtn: 0},
	{Advert: 0},
	{Bullet2: 0},
	{Objects: 0},
	{UI: 0},
	{player: 0},
	{player2: 0},
	{music: 0},
	{pause: 0},
	{pause2: 0},
	{speed: 0},
	{star: 0},
	{starScore: 0},
	{UserId: 0},
	{ennemies: 0},
	{ennemies_position: 0},
	{P2: 0},
	{P3: 0},
	{P4: 0},
	{P5: 0},
	{P6: 0},
	{die: 0},
	{ads: 0}
];

self.InstanceType = {
	BG1: class extends self.ITiledBackgroundInstance {},
	P1: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {},
	Saw: class extends self.ISpriteInstance {},
	forks: class extends self.ISpriteInstance {},
	Object1: class extends self.ISpriteInstance {},
	Object2: class extends self.ISpriteInstance {},
	Star: class extends self.ISpriteInstance {},
	Audio: class extends self.IInstance {},
	Play: class extends self.ISpriteInstance {},
	Rate: class extends self.ISpriteInstance {},
	Sound: class extends self.ISpriteInstance {},
	MoreGames: class extends self.ISpriteInstance {},
	Replay: class extends self.ISpriteInstance {},
	Browser: class extends self.IInstance {},
	Home: class extends self.ISpriteInstance {},
	SC: class extends self.ISpriteInstance {},
	score: class extends self.ISpriteFontInstance {},
	HighScore: class extends self.ISpriteFontInstance {},
	LocalStorage: class extends self.IInstance {},
	StarIcon: class extends self.ISpriteInstance {},
	StarScore: class extends self.ISpriteFontInstance {},
	SHOP: class extends self.ISpriteInstance {},
	B: class extends self.ISpriteInstance {},
	B2: class extends self.ISpriteInstance {},
	twiter: class extends self.ISpriteInstance {},
	fb: class extends self.ISpriteInstance {},
	ok: class extends self.ISpriteInstance {},
	price: class extends self.ISpriteFontInstance {},
	BG2: class extends self.ITiledBackgroundInstance {},
	PauseBtn: class extends self.ISpriteInstance {},
	Advert: class extends self.IInstance {},
	Objects: class extends self.ISpriteInstance {},
	UI: class extends self.ISpriteInstance {}
}