const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Fade,
		C3.Behaviors.Physics,
		C3.Behaviors.Sin,
		C3.Plugins.Spritefont2,
		C3.Plugins.Audio,
		C3.Plugins.Browser,
		C3.Plugins.LocalStorage,
		C3.Plugins.Mouse,
		C3.Plugins.Touch,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Spritefont2.Acts.SetPos,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.System.Exps.projectname,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.Spritefont2.Acts.SetText,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Acts.AddVar,
		C3.Behaviors.Fade.Acts.StartFade,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.Sprite.Acts.SetHeight,
		C3.Plugins.Sprite.Exps.Height,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Acts.SetWidth,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Acts.SetGroupActive,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Behaviors.Fade.Cnds.OnFadeOutEnd,
		C3.Plugins.System.Acts.GoToLayout,
		C3.JavaScriptInEvents.Game_events_Event33_Act4,
		C3.Plugins.System.Acts.SetTimescale,
		C3.Plugins.System.Acts.RestartLayout,
		C3.JavaScriptInEvents.Game_events_Event35_Act4,
		C3.JavaScriptInEvents.Game_events_Event36_Act2,
		C3.Plugins.Audio.Acts.Play,
		C3.JavaScriptInEvents.Game_events_Event41_Act2,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.Mouse.Cnds.IsButtonDown,
		C3.Plugins.Mouse.Acts.SetCursorSprite,
		C3.Plugins.System.Exps.loadingprogress,
		C3.Plugins.System.Cnds.OnLoadFinished,
		C3.Plugins.Audio.Acts.Preload,
		C3.JavaScriptInEvents.Loading_events_Event2_Act8
	];
};
self.C3_JsPropNameTable = [
	{BackGround: 0},
	{Loading: 0},
	{LoadingBar: 0},
	{LoadingBarBackground: 0},
	{Fade: 0},
	{Physics: 0},
	{Smile1: 0},
	{Smile1Blood: 0},
	{Smile2: 0},
	{Smile2Blood: 0},
	{Smile3: 0},
	{Smile3Blood: 0},
	{Smile4: 0},
	{Smile4Blood: 0},
	{Smile5: 0},
	{Smile5Blood: 0},
	{Smile6: 0},
	{Smile6Blood: 0},
	{Menu: 0},
	{Pause: 0},
	{Sine: 0},
	{Play: 0},
	{Paused: 0},
	{Restart: 0},
	{Sounds: 0},
	{BestScoreFont: 0},
	{HighScoreFont: 0},
	{LastScoreFont: 0},
	{LoadingFont: 0},
	{ScoreFont: 0},
	{Smile1Font: 0},
	{Smile3Font: 0},
	{Smile4Font: 0},
	{Smile5Font: 0},
	{Smile6Font: 0},
	{Audio: 0},
	{Browser: 0},
	{LocalStorage: 0},
	{Mouse: 0},
	{Touch: 0},
	{BestScore: 0},
	{Cursor: 0},
	{CursorHover: 0},
	{MiniSmile1: 0},
	{MiniSmile2_1: 0},
	{MiniSmile2_2: 0},
	{MiniSmile2_3: 0},
	{MiniSmile3: 0},
	{MiniSmile4: 0},
	{MiniSmile5: 0},
	{MiniSmile6: 0},
	{ScoreLine: 0},
	{Score: 0},
	{WellDone: 0},
	{Collision: 0},
	{Smiles: 0},
	{Sun: 0},
	{Sound: 0},
	{LastScore: 0},
	{HighScore: 0}
];

self.InstanceType = {
	BackGround: class extends self.ISpriteInstance {},
	Loading: class extends self.ISpriteInstance {},
	LoadingBar: class extends self.ISpriteInstance {},
	LoadingBarBackground: class extends self.ISpriteInstance {},
	Smile1: class extends self.ISpriteInstance {},
	Smile1Blood: class extends self.ISpriteInstance {},
	Smile2: class extends self.ISpriteInstance {},
	Smile2Blood: class extends self.ISpriteInstance {},
	Smile3: class extends self.ISpriteInstance {},
	Smile3Blood: class extends self.ISpriteInstance {},
	Smile4: class extends self.ISpriteInstance {},
	Smile4Blood: class extends self.ISpriteInstance {},
	Smile5: class extends self.ISpriteInstance {},
	Smile5Blood: class extends self.ISpriteInstance {},
	Smile6: class extends self.ISpriteInstance {},
	Smile6Blood: class extends self.ISpriteInstance {},
	Menu: class extends self.ISpriteInstance {},
	Pause: class extends self.ISpriteInstance {},
	Play: class extends self.ISpriteInstance {},
	Paused: class extends self.ISpriteInstance {},
	Restart: class extends self.ISpriteInstance {},
	Sounds: class extends self.ISpriteInstance {},
	BestScoreFont: class extends self.ISpriteFontInstance {},
	HighScoreFont: class extends self.ISpriteFontInstance {},
	LastScoreFont: class extends self.ISpriteFontInstance {},
	LoadingFont: class extends self.ISpriteFontInstance {},
	ScoreFont: class extends self.ISpriteFontInstance {},
	Smile1Font: class extends self.ISpriteFontInstance {},
	Smile3Font: class extends self.ISpriteFontInstance {},
	Smile4Font: class extends self.ISpriteFontInstance {},
	Smile5Font: class extends self.ISpriteFontInstance {},
	Smile6Font: class extends self.ISpriteFontInstance {},
	Audio: class extends self.IInstance {},
	Browser: class extends self.IInstance {},
	LocalStorage: class extends self.IInstance {},
	Mouse: class extends self.IInstance {},
	Touch: class extends self.IInstance {},
	BestScore: class extends self.ISpriteInstance {},
	Cursor: class extends self.ISpriteInstance {},
	CursorHover: class extends self.ISpriteInstance {},
	MiniSmile1: class extends self.ISpriteInstance {},
	MiniSmile2_1: class extends self.ISpriteInstance {},
	MiniSmile2_2: class extends self.ISpriteInstance {},
	MiniSmile2_3: class extends self.ISpriteInstance {},
	MiniSmile3: class extends self.ISpriteInstance {},
	MiniSmile4: class extends self.ISpriteInstance {},
	MiniSmile5: class extends self.ISpriteInstance {},
	MiniSmile6: class extends self.ISpriteInstance {},
	ScoreLine: class extends self.ISpriteInstance {},
	Score: class extends self.ISpriteInstance {},
	WellDone: class extends self.ISpriteInstance {},
	Collision: class extends self.ISpriteInstance {},
	Smiles: class extends self.ISpriteInstance {},
	Sun: class extends self.ISpriteInstance {}
}