const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Audio,
		C3.Plugins.Browser,
		C3.Plugins.LocalStorage,
		C3.Plugins.Mouse,
		C3.Plugins.Touch,
		C3.Plugins.Sprite,
		C3.Behaviors.Physics,
		C3.Behaviors.Bullet,
		C3.Behaviors.wrap,
		C3.Behaviors.Sin,
		C3.Behaviors.solid,
		C3.Plugins.Spritefont2,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Spritefont2.Acts.SetText,
		C3.Plugins.System.Acts.SetVar,
		C3.Behaviors.Physics.Acts.SetWorldGravity,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Acts.GoToLayout,
		C3.JavaScriptInEvents.Game_events_Event3_Act3,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.System.Acts.SetTimescale,
		C3.Plugins.System.Exps.timescale,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Acts.SetWidth,
		C3.Plugins.Sprite.Exps.Height,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Sprite.Cnds.CompareOpacity,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.Sprite.Acts.SetHeight,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.Sprite.Exps.Opacity,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Behaviors.Bullet.Acts.SetSpeed,
		C3.Behaviors.Sin.Acts.SetEnabled,
		C3.Plugins.Sprite.Cnds.OnAnimFinished,
		C3.Plugins.Audio.Acts.Preload,
		C3.Plugins.System.Exps.loadingprogress,
		C3.Plugins.System.Cnds.OnLoadFinished,
		C3.Plugins.Audio.Acts.Play,
		C3.JavaScriptInEvents.Loading_events_Event3_Act3,
		C3.JavaScriptInEvents.Main_events_Event1_Act3,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.System.Exps.projectname,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Audio.Acts.PlayAtObject,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.System.Acts.SetGroupActive
	];
};
self.C3_JsPropNameTable = [
	{Audio: 0},
	{Browser: 0},
	{LocalStorage: 0},
	{Mouse: 0},
	{Touch: 0},
	{Physics: 0},
	{Box: 0},
	{Car: 0},
	{Bullet: 0},
	{Wrap: 0},
	{Car1: 0},
	{Car2: 0},
	{Car3: 0},
	{Car4: 0},
	{Car5: 0},
	{Car6: 0},
	{Sine: 0},
	{Sine2: 0},
	{Cloud: 0},
	{DecalBrake: 0},
	{DecalContactMine: 0},
	{DecalDirt: 0},
	{DecalGas: 0},
	{DecalOil: 0},
	{Solid: 0},
	{Fence: 0},
	{ContactMine: 0},
	{Gas: 0},
	{Loading: 0},
	{LoadingBar: 0},
	{LoadingBarBackground: 0},
	{Tree1: 0},
	{Tree2: 0},
	{Rane: 0},
	{LampPost: 0},
	{Tree3: 0},
	{Splat: 0},
	{Road: 0},
	{Rane2: 0},
	{Lamp: 0},
	{Collision: 0},
	{GuiBlack: 0},
	{Life: 0},
	{ButtonBack: 0},
	{ButtonGame: 0},
	{ButtonPause: 0},
	{ButtonPlay: 0},
	{ButtonReload: 0},
	{ButtonSound: 0},
	{HighScoreFont: 0},
	{LastScoreFont: 0},
	{LevelFont: 0},
	{LifeFont: 0},
	{ScoreFont: 0},
	{TimeFont: 0},
	{Zombie1: 0},
	{Zombie1Blood: 0},
	{Zombie2: 0},
	{Zombie2Blood: 0},
	{Zombie3: 0},
	{Zombie3Blood: 0},
	{Zombie4: 0},
	{Zombie4Blood: 0},
	{ZombieUprising: 0},
	{Level: 0},
	{Score: 0},
	{Minutes: 0},
	{Seconds: 0},
	{PlayerLife: 0},
	{LastScore: 0},
	{HighScore: 0},
	{Sound: 0}
];

self.InstanceType = {
	Audio: class extends self.IInstance {},
	Browser: class extends self.IInstance {},
	LocalStorage: class extends self.IInstance {},
	Mouse: class extends self.IInstance {},
	Touch: class extends self.IInstance {},
	Box: class extends self.ISpriteInstance {},
	Car: class extends self.ISpriteInstance {},
	Car1: class extends self.ISpriteInstance {},
	Car2: class extends self.ISpriteInstance {},
	Car3: class extends self.ISpriteInstance {},
	Car4: class extends self.ISpriteInstance {},
	Car5: class extends self.ISpriteInstance {},
	Car6: class extends self.ISpriteInstance {},
	Cloud: class extends self.ISpriteInstance {},
	DecalBrake: class extends self.ISpriteInstance {},
	DecalContactMine: class extends self.ISpriteInstance {},
	DecalDirt: class extends self.ISpriteInstance {},
	DecalGas: class extends self.ISpriteInstance {},
	DecalOil: class extends self.ISpriteInstance {},
	Fence: class extends self.ISpriteInstance {},
	ContactMine: class extends self.ISpriteInstance {},
	Gas: class extends self.ISpriteInstance {},
	Loading: class extends self.ISpriteInstance {},
	LoadingBar: class extends self.ISpriteInstance {},
	LoadingBarBackground: class extends self.ISpriteInstance {},
	Tree1: class extends self.ISpriteInstance {},
	Tree2: class extends self.ISpriteInstance {},
	Rane: class extends self.ISpriteInstance {},
	LampPost: class extends self.ISpriteInstance {},
	Tree3: class extends self.ISpriteInstance {},
	Splat: class extends self.ISpriteInstance {},
	Road: class extends self.ISpriteInstance {},
	Rane2: class extends self.ISpriteInstance {},
	Lamp: class extends self.ISpriteInstance {},
	Collision: class extends self.ISpriteInstance {},
	GuiBlack: class extends self.ISpriteInstance {},
	Life: class extends self.ISpriteInstance {},
	ButtonBack: class extends self.ISpriteInstance {},
	ButtonGame: class extends self.ISpriteInstance {},
	ButtonPause: class extends self.ISpriteInstance {},
	ButtonPlay: class extends self.ISpriteInstance {},
	ButtonReload: class extends self.ISpriteInstance {},
	ButtonSound: class extends self.ISpriteInstance {},
	HighScoreFont: class extends self.ISpriteFontInstance {},
	LastScoreFont: class extends self.ISpriteFontInstance {},
	LevelFont: class extends self.ISpriteFontInstance {},
	LifeFont: class extends self.ISpriteFontInstance {},
	ScoreFont: class extends self.ISpriteFontInstance {},
	TimeFont: class extends self.ISpriteFontInstance {},
	Zombie1: class extends self.ISpriteInstance {},
	Zombie1Blood: class extends self.ISpriteInstance {},
	Zombie2: class extends self.ISpriteInstance {},
	Zombie2Blood: class extends self.ISpriteInstance {},
	Zombie3: class extends self.ISpriteInstance {},
	Zombie3Blood: class extends self.ISpriteInstance {},
	Zombie4: class extends self.ISpriteInstance {},
	Zombie4Blood: class extends self.ISpriteInstance {},
	ZombieUprising: class extends self.ISpriteInstance {}
}