const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Mouse,
		C3.Plugins.Audio,
		C3.Plugins.Browser,
		C3.Plugins.Touch,
		C3.Plugins.Sprite,
		C3.Behaviors.solid,
		C3.Behaviors.Platform,
		C3.Behaviors.scrollto,
		C3.Behaviors.Bullet,
		C3.Behaviors.Fade,
		C3.Plugins.TiledBg,
		C3.Behaviors.Sin,
		C3.Plugins.Spritefont2,
		C3.Behaviors.Physics,
		C3.Behaviors.wrap,
		C3.Behaviors.Rotate,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Acts.SetGroupActive,
		C3.Plugins.System.Acts.SetTimescale,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Spritefont2.Acts.SetY,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Spritefont2.Acts.SetVisible,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Behaviors.Platform.Acts.SimulateControl,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Behaviors.Bullet.Acts.SetSpeed,
		C3.Plugins.Sprite.Acts.StopAnim,
		C3.Behaviors.Fade.Acts.StartFade,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.JavaScriptInEvents.Gameset_Event3_Act23,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.JavaScriptInEvents.Gameset_Event4_Act4,
		C3.Plugins.Sprite.Cnds.OnAnimFinished,
		C3.Plugins.System.Acts.AddVar,
		C3.Behaviors.Bullet.Acts.SetEnabled,
		C3.Behaviors.Bullet.Acts.SetAngleOfMotion,
		C3.Behaviors.Fade.Cnds.OnFadeOutEnd,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Spritefont2.Acts.SetText,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Cnds.OnDestroyed,
		C3.Plugins.System.Acts.GoToLayout,
		C3.JavaScriptInEvents.Addset_Event22_Act3,
		C3.Plugins.System.Acts.RestartLayout,
		C3.JavaScriptInEvents.Addset_Event23_Act2,
		C3.JavaScriptInEvents.Addset_Event25_Act3,
		C3.Plugins.System.Cnds.Else,
		C3.JavaScriptInEvents.Addset_Event26_Act3,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.System.Cnds.OnLoadFinished,
		C3.Plugins.Audio.Acts.Preload,
		C3.JavaScriptInEvents.Loadingset_Event1_Act10
	];
};
self.C3_JsPropNameTable = [
	{Mouse: 0},
	{Audio: 0},
	{Browser: 0},
	{Touch: 0},
	{Solid: 0},
	{Roads: 0},
	{Platform: 0},
	{ScrollTo: 0},
	{Bullet: 0},
	{Fade: 0},
	{Player: 0},
	{Sine: 0},
	{Water: 0},
	{Coin: 0},
	{Bomb: 0},
	{Box: 0},
	{Sky: 0},
	{TiledBackground: 0},
	{Moon: 0},
	{CoinsFont: 0},
	{CoinGui: 0},
	{ScoreFont: 0},
	{DistanceFont: 0},
	{BtnRestart: 0},
	{BtnSound: 0},
	{BtnMelody: 0},
	{BtnPause: 0},
	{FrameGui: 0},
	{DistanceGui: 0},
	{ScoreGui: 0},
	{BtnSpeed: 0},
	{GameOver: 0},
	{CoinsBigFont: 0},
	{ScoreBigFont: 0},
	{DistanceBigFont: 0},
	{NinjaRun: 0},
	{BtnPlay: 0},
	{Collision: 0},
	{Physics: 0},
	{BombAttack: 0},
	{Wrap: 0},
	{PlayerMenu: 0},
	{Prize: 0},
	{Background: 0},
	{Rotate: 0},
	{Loading: 0},
	{LoadnigText: 0},
	{Melody: 0},
	{Sound: 0},
	{Speed: 0},
	{Pause: 0},
	{Coins: 0},
	{Score: 0},
	{Distances: 0}
];

self.InstanceType = {
	Mouse: class extends self.IInstance {},
	Audio: class extends self.IInstance {},
	Browser: class extends self.IInstance {},
	Touch: class extends self.IInstance {},
	Roads: class extends self.ISpriteInstance {},
	Player: class extends self.ISpriteInstance {},
	Water: class extends self.ITiledBackgroundInstance {},
	Coin: class extends self.ISpriteInstance {},
	Bomb: class extends self.ISpriteInstance {},
	Box: class extends self.ISpriteInstance {},
	Sky: class extends self.ISpriteInstance {},
	TiledBackground: class extends self.ITiledBackgroundInstance {},
	Moon: class extends self.ISpriteInstance {},
	CoinsFont: class extends self.ISpriteFontInstance {},
	CoinGui: class extends self.ISpriteInstance {},
	ScoreFont: class extends self.ISpriteFontInstance {},
	DistanceFont: class extends self.ISpriteFontInstance {},
	BtnRestart: class extends self.ISpriteInstance {},
	BtnSound: class extends self.ISpriteInstance {},
	BtnMelody: class extends self.ISpriteInstance {},
	BtnPause: class extends self.ISpriteInstance {},
	FrameGui: class extends self.ISpriteInstance {},
	DistanceGui: class extends self.ISpriteInstance {},
	ScoreGui: class extends self.ISpriteInstance {},
	BtnSpeed: class extends self.ISpriteInstance {},
	GameOver: class extends self.ISpriteInstance {},
	CoinsBigFont: class extends self.ISpriteFontInstance {},
	ScoreBigFont: class extends self.ISpriteFontInstance {},
	DistanceBigFont: class extends self.ISpriteFontInstance {},
	NinjaRun: class extends self.ISpriteInstance {},
	BtnPlay: class extends self.ISpriteInstance {},
	Collision: class extends self.ISpriteInstance {},
	BombAttack: class extends self.ISpriteInstance {},
	PlayerMenu: class extends self.ISpriteInstance {},
	Prize: class extends self.ISpriteInstance {},
	Background: class extends self.ISpriteInstance {},
	Loading: class extends self.ISpriteInstance {},
	LoadnigText: class extends self.ISpriteInstance {}
}