const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Flash,
		C3.Behaviors.Sin,
		C3.Plugins.Audio,
		C3.Plugins.Browser,
		C3.Plugins.Arr,
		C3.Plugins.LocalStorage,
		C3.Plugins.PlatformInfo,
		C3.Plugins.Function,
		C3.Plugins.Touch,
		C3.Plugins.Spritefont2,
		C3.Plugins.Text,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Exps.choose,
		C3.Plugins.Function.Acts.CallFunction,
		C3.Plugins.Spritefont2.Acts.SetText,
		C3.JavaScriptInEvents.Game_sheet_Event1_Act11,
		C3.Plugins.Function.Cnds.OnFunction,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Exps.random,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Arr.Exps.At,
		C3.Plugins.Arr.Exps.Width,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.Spritefont2.Cnds.PickByUID,
		C3.Plugins.Sprite.Cnds.PickByUID,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Sprite.Acts.SetWidth,
		C3.Plugins.Sprite.Acts.ToggleBoolInstanceVar,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.Sprite.Cnds.CompareWidth,
		C3.Behaviors.Flash.Acts.Flash,
		C3.Plugins.System.Cnds.OnLayoutEnd,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.Browser.Acts.ExecJs,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Acts.Wait,
		C3.JavaScriptInEvents.Game_sheet_Event33_Act3,
		C3.JavaScriptInEvents.Game_sheet_Event36_Act3,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.Audio.Acts.StopAll,
		C3.Plugins.System.Acts.GoToLayout,
		C3.JavaScriptInEvents.Game_sheet_Event37_Act4,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.JavaScriptInEvents.Menu_sheet_Event1_Act10,
		C3.Plugins.Audio.Acts.SetVolume,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.PlatformInfo.Cnds.IsOnMobile,
		C3.Plugins.Browser.Acts.RequestFullScreen,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Exps.loadingprogress,
		C3.Plugins.System.Cnds.OnLoadFinished,
		C3.Plugins.Audio.Acts.Preload
	];
};
self.C3_JsPropNameTable = [
	{Flash: 0},
	{ButtonFalse: 0},
	{ButtonRight: 0},
	{HomeButton: 0},
	{soundButton: 0},
	{Sine: 0},
	{PlayButton: 0},
	{Audio: 0},
	{Browser: 0},
	{CompositeArray: 0},
	{LocalStorage: 0},
	{PlatformInfo: 0},
	{Function: 0},
	{Touch: 0},
	{GameBoard: 0},
	{Operator: 0},
	{Game_Bg: 0},
	{SpriteFontColorNumber: 0},
	{SpriteFont: 0},
	{LoadingFont: 0},
	{loading: 0},
	{Text_Score: 0},
	{Game_Title: 0},
	{active: 0},
	{GameTime: 0},
	{GameTimeBG: 0},
	{Bar: 0},
	{Menu_Bg: 0},
	{Answer_ready: 0},
	{TrueOrFalse: 0},
	{NumberOfPrime: 0},
	{NUMBER: 0},
	{GameMode: 0},
	{Numb2: 0},
	{Result: 0},
	{Number1: 0},
	{BestScore: 0},
	{UserId: 0},
	{Score: 0},
	{FindNumber: 0},
	{i: 0},
	{sound: 0}
];

self.InstanceType = {
	ButtonFalse: class extends self.ISpriteInstance {},
	ButtonRight: class extends self.ISpriteInstance {},
	HomeButton: class extends self.ISpriteInstance {},
	soundButton: class extends self.ISpriteInstance {},
	PlayButton: class extends self.ISpriteInstance {},
	Audio: class extends self.IInstance {},
	Browser: class extends self.IInstance {},
	CompositeArray: class extends self.IArrayInstance {},
	LocalStorage: class extends self.IInstance {},
	PlatformInfo: class extends self.IInstance {},
	Function: class extends self.IInstance {},
	Touch: class extends self.IInstance {},
	GameBoard: class extends self.ISpriteInstance {},
	Operator: class extends self.ISpriteInstance {},
	Game_Bg: class extends self.ISpriteInstance {},
	SpriteFontColorNumber: class extends self.ISpriteFontInstance {},
	SpriteFont: class extends self.ISpriteFontInstance {},
	LoadingFont: class extends self.ITextInstance {},
	loading: class extends self.ISpriteInstance {},
	Text_Score: class extends self.ISpriteInstance {},
	Game_Title: class extends self.ISpriteInstance {},
	GameTime: class extends self.ISpriteInstance {},
	GameTimeBG: class extends self.ISpriteInstance {},
	Bar: class extends self.ISpriteInstance {},
	Menu_Bg: class extends self.ISpriteInstance {}
}