const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Audio,
		C3.Plugins.Browser,
		C3.Plugins.Keyboard,
		C3.Plugins.Mouse,
		C3.Plugins.Touch,
		C3.Plugins.Sprite,
		C3.Behaviors.Platform,
		C3.Behaviors.Rotate,
		C3.Behaviors.Sin,
		C3.Behaviors.bound,
		C3.Plugins.Text,
		C3.Behaviors.Bullet,
		C3.Behaviors.wrap,
		C3.Behaviors.Fade,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.Touch.Cnds.OnTouchStart,
		C3.Behaviors.Platform.Acts.SetGravity,
		C3.Behaviors.Platform.Acts.SetVectorY,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Sprite.Acts.AddInstanceVar,
		C3.Behaviors.Sin.Acts.SetEnabled,
		C3.Plugins.Audio.Acts.Play,
		C3.JavaScriptInEvents.Game_events_Event2_Act7,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.System.Acts.ResetGlobals,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.System.Acts.SetVar,
		C3.JavaScriptInEvents.Game_events_Event10_Act6,
		C3.JavaScriptInEvents.Game_events_Event12_Act6,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Sprite.Cnds.CompareX,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Behaviors.Platform.Acts.SetEnabled,
		C3.Plugins.Text.Acts.SetY,
		C3.Plugins.System.Acts.Wait,
		C3.JavaScriptInEvents.Game_events_Event19_Act10,
		C3.JavaScriptInEvents.Main_events_Event2_Act4,
		C3.Plugins.System.Exps.loadingprogress,
		C3.Plugins.Sprite.Acts.SetWidth,
		C3.Plugins.System.Cnds.OnLoadFinished,
		C3.Plugins.Audio.Acts.Preload,
		C3.Plugins.Mouse.Cnds.IsButtonDown,
		C3.Plugins.Mouse.Acts.SetCursorSprite,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Audio.Acts.SetVolume,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.Sprite.Cnds.CompareFrame
	];
};
self.C3_JsPropNameTable = [
	{Audio: 0},
	{Browser: 0},
	{Keyboard: 0},
	{Mouse: 0},
	{Touch: 0},
	{Platform: 0},
	{Rotate: 0},
	{Sine: 0},
	{BoundToLayout: 0},
	{player: 0},
	{Scored: 0},
	{stop: 0},
	{tube_down: 0},
	{text_score: 0},
	{tap: 0},
	{play: 0},
	{tube_top: 0},
	{bg: 0},
	{text_score_back: 0},
	{Bullet: 0},
	{Wrap: 0},
	{cloud_01: 0},
	{cloud_02: 0},
	{cloud_03: 0},
	{cloud_04: 0},
	{cloud_05: 0},
	{cloud_06: 0},
	{cloud_07: 0},
	{cloud_08: 0},
	{cloud_09: 0},
	{cloud_10: 0},
	{sky: 0},
	{ground: 0},
	{Fade: 0},
	{shadow: 0},
	{flappy_ball: 0},
	{start_game: 0},
	{frame: 0},
	{loading: 0},
	{loading_bar_background: 0},
	{loading_bar: 0},
	{text_loading: 0},
	{ButtonSound: 0},
	{cursor: 0},
	{cursor_hover: 0},
	{tube_top_menu: 0},
	{tube_down_menu: 0},
	{return: 0},
	{Score: 0},
	{UserId: 0},
	{Scroll_Speed: 0},
	{Sound_Status: 0},
	{Sound: 0}
];

self.InstanceType = {
	Audio: class extends self.IInstance {},
	Browser: class extends self.IInstance {},
	Keyboard: class extends self.IInstance {},
	Mouse: class extends self.IInstance {},
	Touch: class extends self.IInstance {},
	player: class extends self.ISpriteInstance {},
	tube_down: class extends self.ISpriteInstance {},
	text_score: class extends self.ITextInstance {},
	tap: class extends self.ISpriteInstance {},
	play: class extends self.ISpriteInstance {},
	tube_top: class extends self.ISpriteInstance {},
	text_score_back: class extends self.ITextInstance {},
	cloud_01: class extends self.ISpriteInstance {},
	cloud_02: class extends self.ISpriteInstance {},
	cloud_03: class extends self.ISpriteInstance {},
	cloud_04: class extends self.ISpriteInstance {},
	cloud_05: class extends self.ISpriteInstance {},
	cloud_06: class extends self.ISpriteInstance {},
	cloud_07: class extends self.ISpriteInstance {},
	cloud_08: class extends self.ISpriteInstance {},
	cloud_09: class extends self.ISpriteInstance {},
	cloud_10: class extends self.ISpriteInstance {},
	sky: class extends self.ISpriteInstance {},
	ground: class extends self.ISpriteInstance {},
	shadow: class extends self.ISpriteInstance {},
	flappy_ball: class extends self.ISpriteInstance {},
	start_game: class extends self.ISpriteInstance {},
	frame: class extends self.ISpriteInstance {},
	loading: class extends self.ISpriteInstance {},
	loading_bar_background: class extends self.ISpriteInstance {},
	loading_bar: class extends self.ISpriteInstance {},
	text_loading: class extends self.ITextInstance {},
	ButtonSound: class extends self.ISpriteInstance {},
	cursor: class extends self.ISpriteInstance {},
	cursor_hover: class extends self.ISpriteInstance {},
	tube_top_menu: class extends self.ISpriteInstance {},
	tube_down_menu: class extends self.ISpriteInstance {},
	return: class extends self.ISpriteInstance {}
}