const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Audio,
		C3.Plugins.Browser,
		C3.Plugins.Mouse,
		C3.Plugins.Touch,
		C3.Plugins.LocalStorage,
		C3.Plugins.Sprite,
		C3.Behaviors.Bullet,
		C3.Behaviors.Fade,
		C3.Plugins.Spritefont2,
		C3.Behaviors.Sin,
		C3.Behaviors.Physics,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Spritefont2.Acts.SetPos,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.System.Exps.projectname,
		C3.JavaScriptInEvents.Global_events_Event1_Act16,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.Spritefont2.Acts.SetText,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Acts.AddVar,
		C3.Behaviors.Fade.Acts.StartFade,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.Sprite.Acts.SetHeight,
		C3.Plugins.Sprite.Exps.Height,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Acts.SetWidth,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.System.Acts.SetGroupActive,
		C3.JavaScriptInEvents.Global_events_Event23_Act9,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Behaviors.Fade.Cnds.OnFadeOutEnd,
		C3.Plugins.System.Acts.GoToLayout,
		C3.JavaScriptInEvents.Global_events_Event33_Act4,
		C3.Plugins.System.Acts.SetTimescale,
		C3.JavaScriptInEvents.Global_events_Event34_Act4,
		C3.Plugins.System.Acts.RestartLayout,
		C3.JavaScriptInEvents.Global_events_Event35_Act4,
		C3.JavaScriptInEvents.Global_events_Event36_Act2,
		C3.JavaScriptInEvents.Global_events_Event37_Act4,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.Mouse.Cnds.IsButtonDown,
		C3.Plugins.Mouse.Acts.SetCursorSprite,
		C3.Plugins.System.Exps.loadingprogress,
		C3.Plugins.System.Cnds.OnLoadFinished,
		C3.Plugins.Audio.Acts.Preload
	];
};
self.C3_JsPropNameTable = [
	{Audio: 0},
	{Browser: 0},
	{Mouse: 0},
	{Touch: 0},
	{LocalStorage: 0},
	{Bullet: 0},
	{Balloon1: 0},
	{Fade: 0},
	{Balloon1Crash: 0},
	{Balloon2: 0},
	{Balloon2Crash: 0},
	{Balloon3: 0},
	{Balloon3Crash: 0},
	{Balloon4: 0},
	{Balloon4Crash: 0},
	{Balloon5: 0},
	{Balloon5Crash: 0},
	{Balloon6: 0},
	{Balloon6Crash: 0},
	{Balloon1Font: 0},
	{Balloon3Font: 0},
	{Balloon4Font: 0},
	{Balloon5Font: 0},
	{Balloon6Font: 0},
	{BestScoreFont: 0},
	{HighScoreFont: 0},
	{LastScoreFont: 0},
	{LoadingFont: 0},
	{ScoreFont: 0},
	{BackGround: 0},
	{Loading: 0},
	{LoadingBar: 0},
	{LoadingBarBackground: 0},
	{Menu: 0},
	{Pause: 0},
	{Paused: 0},
	{Sine: 0},
	{Play: 0},
	{Restart: 0},
	{Sounds: 0},
	{Cursor: 0},
	{CursorHover: 0},
	{HighScoreGui: 0},
	{LastScoreGui: 0},
	{BestScore: 0},
	{MiniBalloon2_1: 0},
	{MiniBalloon1: 0},
	{MiniBalloon2_0: 0},
	{MiniBalloon2_2: 0},
	{MiniBalloon2_3: 0},
	{MiniBalloon3: 0},
	{MiniBalloon4: 0},
	{MiniBalloon5: 0},
	{MiniBalloon6: 0},
	{Sun: 0},
	{WellDone: 0},
	{ScoreGui: 0},
	{Physics: 0},
	{Collision: 0},
	{Balloons: 0},
	{Score: 0},
	{Sound: 0},
	{Balloon: 0},
	{LastScore: 0},
	{HighScore: 0},
	{UserId: 0}
];

self.InstanceType = {
	Audio: class extends self.IInstance {},
	Browser: class extends self.IInstance {},
	Mouse: class extends self.IInstance {},
	Touch: class extends self.IInstance {},
	LocalStorage: class extends self.IInstance {},
	Balloon1: class extends self.ISpriteInstance {},
	Balloon1Crash: class extends self.ISpriteInstance {},
	Balloon2: class extends self.ISpriteInstance {},
	Balloon2Crash: class extends self.ISpriteInstance {},
	Balloon3: class extends self.ISpriteInstance {},
	Balloon3Crash: class extends self.ISpriteInstance {},
	Balloon4: class extends self.ISpriteInstance {},
	Balloon4Crash: class extends self.ISpriteInstance {},
	Balloon5: class extends self.ISpriteInstance {},
	Balloon5Crash: class extends self.ISpriteInstance {},
	Balloon6: class extends self.ISpriteInstance {},
	Balloon6Crash: class extends self.ISpriteInstance {},
	Balloon1Font: class extends self.ISpriteFontInstance {},
	Balloon3Font: class extends self.ISpriteFontInstance {},
	Balloon4Font: class extends self.ISpriteFontInstance {},
	Balloon5Font: class extends self.ISpriteFontInstance {},
	Balloon6Font: class extends self.ISpriteFontInstance {},
	BestScoreFont: class extends self.ISpriteFontInstance {},
	HighScoreFont: class extends self.ISpriteFontInstance {},
	LastScoreFont: class extends self.ISpriteFontInstance {},
	LoadingFont: class extends self.ISpriteFontInstance {},
	ScoreFont: class extends self.ISpriteFontInstance {},
	BackGround: class extends self.ISpriteInstance {},
	Loading: class extends self.ISpriteInstance {},
	LoadingBar: class extends self.ISpriteInstance {},
	LoadingBarBackground: class extends self.ISpriteInstance {},
	Menu: class extends self.ISpriteInstance {},
	Pause: class extends self.ISpriteInstance {},
	Paused: class extends self.ISpriteInstance {},
	Play: class extends self.ISpriteInstance {},
	Restart: class extends self.ISpriteInstance {},
	Sounds: class extends self.ISpriteInstance {},
	Cursor: class extends self.ISpriteInstance {},
	CursorHover: class extends self.ISpriteInstance {},
	HighScoreGui: class extends self.ISpriteInstance {},
	LastScoreGui: class extends self.ISpriteInstance {},
	BestScore: class extends self.ISpriteInstance {},
	MiniBalloon2_1: class extends self.ISpriteInstance {},
	MiniBalloon1: class extends self.ISpriteInstance {},
	MiniBalloon2_0: class extends self.ISpriteInstance {},
	MiniBalloon2_2: class extends self.ISpriteInstance {},
	MiniBalloon2_3: class extends self.ISpriteInstance {},
	MiniBalloon3: class extends self.ISpriteInstance {},
	MiniBalloon4: class extends self.ISpriteInstance {},
	MiniBalloon5: class extends self.ISpriteInstance {},
	MiniBalloon6: class extends self.ISpriteInstance {},
	Sun: class extends self.ISpriteInstance {},
	WellDone: class extends self.ISpriteInstance {},
	ScoreGui: class extends self.ISpriteInstance {},
	Collision: class extends self.ISpriteInstance {},
	Balloons: class extends self.ISpriteInstance {}
}