const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Audio,
		C3.Plugins.Browser,
		C3.Plugins.Mouse,
		C3.Plugins.Touch,
		C3.Plugins.Function,
		C3.Plugins.LocalStorage,
		C3.Plugins.Sprite,
		C3.Behaviors.Timer,
		C3.Plugins.Spritefont2,
		C3.Behaviors.Sin,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Audio.Acts.SetVolume,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.Spritefont2.Acts.SetY,
		C3.Plugins.Spritefont2.Acts.SetText,
		C3.Plugins.System.Acts.SetTimescale,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Function.Acts.CallFunction,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Behaviors.Timer.Exps.CurrentTime,
		C3.Plugins.System.Cnds.CompareVar,
		C3.JavaScriptInEvents.Game_events_Event3_Act6,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.System.Exps.projectname,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.System.Exps.originalwindowheight,
		C3.Plugins.Sprite.Acts.MoveAtAngle,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.System.Acts.RestartLayout,
		C3.JavaScriptInEvents.Game_events_Event11_Act2,
		C3.Plugins.System.Acts.GoToLayout,
		C3.JavaScriptInEvents.Game_events_Event12_Act2,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.Function.Cnds.OnFunction,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.System.Exps.windowwidth,
		C3.Plugins.System.Exps.windowheight,
		C3.Behaviors.Timer.Acts.StartTimer,
		C3.Plugins.System.Acts.AddVar,
		C3.Behaviors.Timer.Acts.StopTimer,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Behaviors.Timer.Exps.Duration,
		C3.Behaviors.Timer.Cnds.OnTimer,
		C3.JavaScriptInEvents.Main_events_Event2_Act2,
		C3.JavaScriptInEvents.Main_events_Event3_Act1,
		C3.Plugins.Browser.Acts.Close,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Acts.SetGroupActive,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.Mouse.Cnds.IsButtonDown,
		C3.Plugins.Mouse.Acts.SetCursorSprite,
		C3.JavaScriptInEvents.Global_events_Event14_Act2,
		C3.Plugins.Sprite.Acts.SetWidth,
		C3.Plugins.System.Exps.loadingprogress,
		C3.Plugins.System.Cnds.OnLoadFinished,
		C3.Plugins.Audio.Acts.Preload,
		C3.JavaScriptInEvents.Loading_events_Event2_Act6
	];
};
self.C3_JsPropNameTable = [
	{Audio: 0},
	{Browser: 0},
	{Mouse: 0},
	{Touch: 0},
	{Function: 0},
	{LocalStorage: 0},
	{BackGround: 0},
	{tCurrent: 0},
	{tDuration: 0},
	{Timer: 0},
	{Ball: 0},
	{Loading: 0},
	{LoadingBar: 0},
	{LoadingBarBackground: 0},
	{BtnClose: 0},
	{BtnMenu: 0},
	{BtnMusic: 0},
	{BtnPlay: 0},
	{BtnRestart: 0},
	{HighScoreFont: 0},
	{ScoreFont: 0},
	{ScoreFont2: 0},
	{TimerFont: 0},
	{Icon: 0},
	{Sine: 0},
	{TouchBall: 0},
	{Cursor: 0},
	{CursorHover: 0},
	{Score: 0},
	{HighScore: 0},
	{Music: 0}
];

self.InstanceType = {
	Audio: class extends self.IInstance {},
	Browser: class extends self.IInstance {},
	Mouse: class extends self.IInstance {},
	Touch: class extends self.IInstance {},
	Function: class extends self.IInstance {},
	LocalStorage: class extends self.IInstance {},
	BackGround: class extends self.ISpriteInstance {},
	Ball: class extends self.ISpriteInstance {},
	Loading: class extends self.ISpriteInstance {},
	LoadingBar: class extends self.ISpriteInstance {},
	LoadingBarBackground: class extends self.ISpriteInstance {},
	BtnClose: class extends self.ISpriteInstance {},
	BtnMenu: class extends self.ISpriteInstance {},
	BtnMusic: class extends self.ISpriteInstance {},
	BtnPlay: class extends self.ISpriteInstance {},
	BtnRestart: class extends self.ISpriteInstance {},
	HighScoreFont: class extends self.ISpriteFontInstance {},
	ScoreFont: class extends self.ISpriteFontInstance {},
	ScoreFont2: class extends self.ISpriteFontInstance {},
	TimerFont: class extends self.ISpriteFontInstance {},
	Icon: class extends self.ISpriteInstance {},
	TouchBall: class extends self.ISpriteInstance {},
	Cursor: class extends self.ISpriteInstance {},
	CursorHover: class extends self.ISpriteInstance {}
}