const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Audio,
		C3.Plugins.Browser,
		C3.Plugins.LocalStorage,
		C3.Plugins.Touch,
		C3.Plugins.Sprite,
		C3.Behaviors.Sin,
		C3.Plugins.Spritefont2,
		C3.Behaviors.solid,
		C3.Plugins.TiledBg,
		C3.Behaviors.Platform,
		C3.Behaviors.Pin,
		C3.Behaviors.Fade,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Behaviors.Pin.Acts.Pin,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Spritefont2.Acts.SetText,
		C3.Plugins.Sprite.Acts.MoveToBottom,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.TiledBg.Acts.SetX,
		C3.Plugins.TiledBg.Exps.X,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.Sprite.Exps.Angle,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Spritefont2.Acts.SetVisible,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Spritefont2.Acts.SetPos,
		C3.JavaScriptInEvents.Game_events_Event3_Act15,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.System.Exps.projectname,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Behaviors.Fade.Acts.StartFade,
		C3.JavaScriptInEvents.Game_events_Event6_Act4,
		C3.Plugins.TiledBg.Cnds.CompareX,
		C3.Plugins.TiledBg.Exps.Width,
		C3.Behaviors.Platform.Acts.SimulateControl,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Exps.random,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Sprite.Exps.AnimationFrame,
		C3.Plugins.Sprite.Cnds.CompareX,
		C3.Plugins.Audio.Acts.Preload,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.Audio.Cnds.IsTagPlaying,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.JavaScriptInEvents.Main_events_Event6_Act1,
		C3.Plugins.Browser.Acts.Close,
		C3.Plugins.System.Acts.GoToLayout,
		C3.JavaScriptInEvents.Main_events_Event7_Act2,
		C3.JavaScriptInEvents.Main_events_Event8_Act2,
		C3.Plugins.System.Acts.RestartLayout,
		C3.JavaScriptInEvents.Main_events_Event9_Act2,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Sprite.Acts.SetAnim
	];
};
self.C3_JsPropNameTable = [
	{Audio: 0},
	{Browser: 0},
	{LocalStorage: 0},
	{Touch: 0},
	{BTNEXIT: 0},
	{Sine: 0},
	{GAME: 0},
	{MENU: 0},
	{RESTART: 0},
	{SOUND: 0},
	{BESTSCORE: 0},
	{GAMEOVER: 0},
	{LEVEL: 0},
	{SCORE: 0},
	{STARS: 0},
	{Solid: 0},
	{CollisonPlayerCar: 0},
	{BG: 0},
	{GameBackground: 0},
	{Coin: 0},
	{GameLogo: 0},
	{Platform: 0},
	{PlayerCar: 0},
	{Pin: 0},
	{PlayerCarWheel: 0},
	{ID: 0},
	{TrafficCars: 0},
	{TrafficCarsWheel: 0},
	{FrameGameOver: 0},
	{FrameScore: 0},
	{FrameStars: 0},
	{Fade: 0},
	{LevelUp: 0},
	{TouchToStart: 0},
	{PAUSE: 0},
	{NEEDSTARS: 0}
];

self.InstanceType = {
	Audio: class extends self.IInstance {},
	Browser: class extends self.IInstance {},
	LocalStorage: class extends self.IInstance {},
	Touch: class extends self.IInstance {},
	BTNEXIT: class extends self.ISpriteInstance {},
	GAME: class extends self.ISpriteInstance {},
	MENU: class extends self.ISpriteInstance {},
	RESTART: class extends self.ISpriteInstance {},
	SOUND: class extends self.ISpriteInstance {},
	BESTSCORE: class extends self.ISpriteFontInstance {},
	GAMEOVER: class extends self.ISpriteFontInstance {},
	LEVEL: class extends self.ISpriteFontInstance {},
	SCORE: class extends self.ISpriteFontInstance {},
	STARS: class extends self.ISpriteFontInstance {},
	CollisonPlayerCar: class extends self.ISpriteInstance {},
	BG: class extends self.ISpriteInstance {},
	GameBackground: class extends self.ITiledBackgroundInstance {},
	Coin: class extends self.ISpriteInstance {},
	GameLogo: class extends self.ISpriteInstance {},
	PlayerCar: class extends self.ISpriteInstance {},
	PlayerCarWheel: class extends self.ISpriteInstance {},
	TrafficCars: class extends self.ISpriteInstance {},
	TrafficCarsWheel: class extends self.ISpriteInstance {},
	FrameGameOver: class extends self.ISpriteInstance {},
	FrameScore: class extends self.ISpriteInstance {},
	FrameStars: class extends self.ISpriteInstance {},
	LevelUp: class extends self.ISpriteInstance {},
	TouchToStart: class extends self.ISpriteInstance {}
}