const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Rotate,
		C3.Behaviors.Sin,
		C3.Plugins.TiledBg,
		C3.Plugins.Audio,
		C3.Plugins.Browser,
		C3.Plugins.Keyboard,
		C3.Plugins.Mouse,
		C3.Plugins.Touch,
		C3.Plugins.LocalStorage,
		C3.Behaviors.Bullet,
		C3.Behaviors.scrollto,
		C3.Behaviors.bound,
		C3.Plugins.Spritefont2,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Acts.SetGroupActive,
		C3.Plugins.System.Acts.SetTimescale,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.System.Acts.SetLayerEffectParam,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Spritefont2.Acts.SetText,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.Sprite.Exps.Y,
		C3.Behaviors.Bullet.Acts.SetDistanceTravelled,
		C3.Behaviors.Bullet.Acts.SetSpeed,
		C3.Behaviors.Bullet.Acts.SetAngleOfMotion,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Behaviors.Bullet.Cnds.CompareTravelled,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Behaviors.scrollto.Acts.Shake,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Spritefont2.Acts.SetVisible,
		C3.JavaScriptInEvents.Game_events_Event24_Act25,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.System.Exps.projectname,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.JavaScriptInEvents.Game_events_Event28_Act15,
		C3.Plugins.System.Exps.choose,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Exps.Angle,
		C3.Plugins.Audio.Acts.Preload,
		C3.Plugins.System.Exps.loadingprogress,
		C3.Plugins.System.Cnds.OnLoadFinished,
		C3.Plugins.System.Acts.WaitForSignal,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Acts.GoToLayout,
		C3.JavaScriptInEvents.Loading_events_Event3_Act6,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.JavaScriptInEvents.Global_events_Event16_Act5,
		C3.JavaScriptInEvents.Global_events_Event17_Act2,
		C3.JavaScriptInEvents.Global_events_Event19_Act2,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Mouse.Cnds.IsButtonDown,
		C3.Plugins.Mouse.Acts.SetCursorSprite,
		C3.Plugins.Mouse.Cnds.IsOverObject,
		C3.Behaviors.Sin.Acts.SetEnabled,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.System.Cnds.LayerVisible,
		C3.JavaScriptInEvents.Global_events_Event56_Act1,
		C3.Plugins.Browser.Acts.RequestFullScreen,
		C3.Plugins.Browser.Acts.CancelFullScreen,
		C3.Plugins.System.Acts.SetLayerOpacity,
		C3.Plugins.System.Cnds.LayerCmpOpacity,
		C3.Plugins.System.Exps.layeropacity,
		C3.Plugins.System.Acts.Signal
	];
};
self.C3_JsPropNameTable = [
	{BtnMoveDown: 0},
	{BtnPause: 0},
	{BtnMusic: 0},
	{BtnPlay: 0},
	{BtnMoveUp: 0},
	{BtnSound: 0},
	{Cursor: 0},
	{CursorHover: 0},
	{Rotate: 0},
	{SunLight: 0},
	{BtnFullscreen: 0},
	{Icons: 0},
	{Frame: 0},
	{BtnOk: 0},
	{Instruction: 0},
	{GameIcon: 0},
	{Background: 0},
	{Sine: 0},
	{GameLogo: 0},
	{Grass: 0},
	{AsphaltRoad_1: 0},
	{AsphaltRoad_2: 0},
	{GroundIntersection: 0},
	{Water: 0},
	{WaterIntersection: 0},
	{Ground: 0},
	{Asphalt: 0},
	{Sand: 0},
	{GroundRoad_2: 0},
	{WaterRoad_2: 0},
	{GroundRoad_1: 0},
	{WaterRoad_1: 0},
	{Railroad_1: 0},
	{Railroad_2: 0},
	{Audio: 0},
	{Browser: 0},
	{Keyboard: 0},
	{Mouse: 0},
	{Touch: 0},
	{LocalStorage: 0},
	{Window: 0},
	{BtnMenu: 0},
	{BtnRestart: 0},
	{Bullet: 0},
	{ScrollTo: 0},
	{BoundToLayout: 0},
	{Player: 0},
	{PlayerCar: 0},
	{ID: 0},
	{Cars: 0},
	{CarSpeed: 0},
	{SpawnCars: 0},
	{Train: 0},
	{SpeedLimit: 0},
	{Sign2: 0},
	{Crosswalk: 0},
	{Grills: 0},
	{StartMenuSpawnCars: 0},
	{Umbrella: 0},
	{Barrier_1: 0},
	{Barrier_2: 0},
	{Bush: 0},
	{Cones: 0},
	{Stones: 0},
	{Trees: 0},
	{Wheels: 0},
	{Barrier_3: 0},
	{Boat: 0},
	{Tunnel: 0},
	{Palm: 0},
	{Sine2: 0},
	{Effects: 0},
	{BestScoreFont: 0},
	{LastScoreFont: 0},
	{LoadingFont: 0},
	{ScoreFont: 0},
	{ScoreTopFont: 0},
	{TimeFont: 0},
	{WinnerFont: 0},
	{ButtonsSound: 0},
	{Score: 0},
	{Seconds: 0},
	{Minutes: 0},
	{LastScore: 0},
	{BestScore: 0},
	{Pause: 0},
	{Music: 0},
	{Sound: 0},
	{Fullscreen: 0}
];

self.InstanceType = {
	BtnMoveDown: class extends self.ISpriteInstance {},
	BtnPause: class extends self.ISpriteInstance {},
	BtnMusic: class extends self.ISpriteInstance {},
	BtnPlay: class extends self.ISpriteInstance {},
	BtnMoveUp: class extends self.ISpriteInstance {},
	BtnSound: class extends self.ISpriteInstance {},
	Cursor: class extends self.ISpriteInstance {},
	CursorHover: class extends self.ISpriteInstance {},
	SunLight: class extends self.ISpriteInstance {},
	BtnFullscreen: class extends self.ISpriteInstance {},
	Icons: class extends self.ISpriteInstance {},
	Frame: class extends self.ISpriteInstance {},
	BtnOk: class extends self.ISpriteInstance {},
	Instruction: class extends self.ISpriteInstance {},
	GameIcon: class extends self.ISpriteInstance {},
	Background: class extends self.ISpriteInstance {},
	GameLogo: class extends self.ISpriteInstance {},
	Grass: class extends self.ITiledBackgroundInstance {},
	AsphaltRoad_1: class extends self.ITiledBackgroundInstance {},
	AsphaltRoad_2: class extends self.ITiledBackgroundInstance {},
	GroundIntersection: class extends self.ISpriteInstance {},
	Water: class extends self.ITiledBackgroundInstance {},
	WaterIntersection: class extends self.ISpriteInstance {},
	Ground: class extends self.ITiledBackgroundInstance {},
	Asphalt: class extends self.ITiledBackgroundInstance {},
	Sand: class extends self.ITiledBackgroundInstance {},
	GroundRoad_2: class extends self.ITiledBackgroundInstance {},
	WaterRoad_2: class extends self.ITiledBackgroundInstance {},
	GroundRoad_1: class extends self.ISpriteInstance {},
	WaterRoad_1: class extends self.ISpriteInstance {},
	Railroad_1: class extends self.ITiledBackgroundInstance {},
	Railroad_2: class extends self.ITiledBackgroundInstance {},
	Audio: class extends self.IInstance {},
	Browser: class extends self.IInstance {},
	Keyboard: class extends self.IInstance {},
	Mouse: class extends self.IInstance {},
	Touch: class extends self.IInstance {},
	LocalStorage: class extends self.IInstance {},
	Window: class extends self.ISpriteInstance {},
	BtnMenu: class extends self.ISpriteInstance {},
	BtnRestart: class extends self.ISpriteInstance {},
	Player: class extends self.ISpriteInstance {},
	PlayerCar: class extends self.ISpriteInstance {},
	Cars: class extends self.ISpriteInstance {},
	SpawnCars: class extends self.ISpriteInstance {},
	Train: class extends self.ISpriteInstance {},
	SpeedLimit: class extends self.ISpriteInstance {},
	Sign2: class extends self.ISpriteInstance {},
	Crosswalk: class extends self.ISpriteInstance {},
	Grills: class extends self.ISpriteInstance {},
	StartMenuSpawnCars: class extends self.ISpriteInstance {},
	Umbrella: class extends self.ISpriteInstance {},
	Barrier_1: class extends self.ITiledBackgroundInstance {},
	Barrier_2: class extends self.ITiledBackgroundInstance {},
	Bush: class extends self.ITiledBackgroundInstance {},
	Cones: class extends self.ITiledBackgroundInstance {},
	Stones: class extends self.ISpriteInstance {},
	Trees: class extends self.ISpriteInstance {},
	Wheels: class extends self.ISpriteInstance {},
	Barrier_3: class extends self.ITiledBackgroundInstance {},
	Boat: class extends self.ISpriteInstance {},
	Tunnel: class extends self.ISpriteInstance {},
	Palm: class extends self.ISpriteInstance {},
	Effects: class extends self.ISpriteInstance {},
	BestScoreFont: class extends self.ISpriteFontInstance {},
	LastScoreFont: class extends self.ISpriteFontInstance {},
	LoadingFont: class extends self.ISpriteFontInstance {},
	ScoreFont: class extends self.ISpriteFontInstance {},
	ScoreTopFont: class extends self.ISpriteFontInstance {},
	TimeFont: class extends self.ISpriteFontInstance {},
	WinnerFont: class extends self.ISpriteFontInstance {},
	ButtonsSound: class extends self.ISpriteInstance {}
}