const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Sin,
		C3.Behaviors.Flash,
		C3.Plugins.Audio,
		C3.Plugins.Browser,
		C3.Plugins.Function,
		C3.Plugins.Touch,
		C3.Plugins.LocalStorage,
		C3.Plugins.Spritefont2,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.System.Exps.projectname,
		C3.JavaScriptInEvents.Game_events_Event2_Act3,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Acts.SetGroupActive,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.Audio.Cnds.IsTagPlaying,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.Spritefont2.Acts.SetText,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.System.Acts.GoToLayout,
		C3.JavaScriptInEvents.Game_events_Event8_Act6,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Acts.SubVar,
		C3.JavaScriptInEvents.Game_events_Event13_Act3,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Behaviors.Flash.Acts.Flash,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.System.Cnds.CompareBetween,
		C3.Plugins.System.Exps.random,
		C3.Plugins.System.Exps.choose,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Function.Acts.CallFunction,
		C3.JavaScriptInEvents.Game_events_Event33_Act1,
		C3.JavaScriptInEvents.Game_events_Event38_Act1,
		C3.JavaScriptInEvents.Game_events_Event43_Act1,
		C3.Plugins.Function.Cnds.OnFunction,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Exps.int,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.JavaScriptInEvents.Game_events_Event52_Act7,
		C3.JavaScriptInEvents.Game_events_Event53_Act2,
		C3.Plugins.Sprite.Acts.SetAnim
	];
};
self.C3_JsPropNameTable = [
	{Sine: 0},
	{GameOver: 0},
	{ButtonHome: 0},
	{ButtonRestart: 0},
	{ButtonPlay: 0},
	{GameLogo: 0},
	{Background: 0},
	{Value: 0},
	{Flash: 0},
	{ButtonGreen: 0},
	{ButtonRed: 0},
	{ButtonSound: 0},
	{ButtonYellow: 0},
	{Frame: 0},
	{Audio: 0},
	{Browser: 0},
	{Function: 0},
	{Touch: 0},
	{LocalStorage: 0},
	{QuestionFont: 0},
	{TimerFont: 0},
	{AnswerRedFont: 0},
	{AnswerYellowFont: 0},
	{AnswerGreenFont: 0},
	{ScoreFont: 0},
	{BestScoreFont: 0},
	{StartMenuBestScoreFont: 0},
	{TextScoreFont: 0},
	{TextScoreValueFont: 0},
	{Sound: 0},
	{BestScore: 0},
	{IsGameOver: 0},
	{NextQuestion: 0},
	{CurrentScore: 0},
	{CurrentQuestion: 0},
	{UserId: 0},
	{CorrectAnswer: 0},
	{SecondsLeft: 0},
	{MAXSECONDS: 0},
	{Question1: 0},
	{Question2: 0},
	{Question3: 0},
	{Question4: 0}
];

self.InstanceType = {
	GameOver: class extends self.ISpriteInstance {},
	ButtonHome: class extends self.ISpriteInstance {},
	ButtonRestart: class extends self.ISpriteInstance {},
	ButtonPlay: class extends self.ISpriteInstance {},
	GameLogo: class extends self.ISpriteInstance {},
	Background: class extends self.ISpriteInstance {},
	ButtonGreen: class extends self.ISpriteInstance {},
	ButtonRed: class extends self.ISpriteInstance {},
	ButtonSound: class extends self.ISpriteInstance {},
	ButtonYellow: class extends self.ISpriteInstance {},
	Frame: class extends self.ISpriteInstance {},
	Audio: class extends self.IInstance {},
	Browser: class extends self.IInstance {},
	Function: class extends self.IInstance {},
	Touch: class extends self.IInstance {},
	LocalStorage: class extends self.IInstance {},
	QuestionFont: class extends self.ISpriteFontInstance {},
	TimerFont: class extends self.ISpriteFontInstance {},
	AnswerRedFont: class extends self.ISpriteFontInstance {},
	AnswerYellowFont: class extends self.ISpriteFontInstance {},
	AnswerGreenFont: class extends self.ISpriteFontInstance {},
	ScoreFont: class extends self.ISpriteFontInstance {},
	BestScoreFont: class extends self.ISpriteFontInstance {},
	StartMenuBestScoreFont: class extends self.ISpriteFontInstance {},
	TextScoreFont: class extends self.ISpriteFontInstance {},
	TextScoreValueFont: class extends self.ISpriteFontInstance {}
}