const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Rotate,
		C3.Behaviors.Fade,
		C3.Plugins.TiledBg,
		C3.Behaviors.Sin,
		C3.Plugins.Audio,
		C3.Plugins.Browser,
		C3.Plugins.Keyboard,
		C3.Plugins.Mouse,
		C3.Plugins.Touch,
		C3.Plugins.LocalStorage,
		C3.Plugins.NinePatch,
		C3.Behaviors.Pin,
		C3.Behaviors.Flash,
		C3.Plugins.Spritefont2,
		C3.Behaviors.solid,
		C3.Behaviors.Platform,
		C3.Behaviors.scrollto,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Behaviors.Pin.Acts.Pin,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Spritefont2.Acts.SetPos,
		C3.Plugins.Sprite.Acts.SetY,
		C3.JavaScriptInEvents.Gameevent_Event1_Act27,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.Spritefont2.Acts.SetText,
		C3.Plugins.TiledBg.Acts.SetX,
		C3.Plugins.TiledBg.Exps.X,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Acts.SetPosToObject,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Spritefont2.Acts.SetScale,
		C3.Plugins.Spritefont2.Exps.CharacterScale,
		C3.Plugins.Spritefont2.Acts.SetX,
		C3.Plugins.Spritefont2.Exps.X,
		C3.Plugins.Spritefont2.Acts.SetY,
		C3.Plugins.Spritefont2.Exps.Y,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.Keyboard.Cnds.OnAnyKey,
		C3.Behaviors.Sin.Cnds.IsEnabled,
		C3.Plugins.Audio.Acts.Play,
		C3.Behaviors.Fade.Acts.StartFade,
		C3.Behaviors.Sin.Acts.SetEnabled,
		C3.Plugins.Sprite.Cnds.OnDestroyed,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.JavaScriptInEvents.Gameevent_Event16_Act8,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.System.Exps.projectname,
		C3.Plugins.System.Acts.SetGroupActive,
		C3.Plugins.System.Acts.WaitForSignal,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Behaviors.Platform.Acts.SimulateControl,
		C3.Plugins.Sprite.Cnds.CompareY,
		C3.Behaviors.solid.Acts.SetEnabled,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Behaviors.Platform.Acts.SetDoubleJumpEnabled,
		C3.Behaviors.Platform.Cnds.IsOnFloor,
		C3.Plugins.Sprite.Cnds.OnAnimFinished,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Exps.AnimationFrame,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Sprite.Cnds.IsOutsideLayout,
		C3.Plugins.System.Exps.random,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.System.Exps.layoutwidth,
		C3.Plugins.Sprite.Acts.SetAnimSpeed,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.NinePatch.Acts.SetWidth,
		C3.Plugins.NinePatch.Acts.SetHeight,
		C3.Plugins.NinePatch.Exps.Height,
		C3.Plugins.NinePatch.Acts.SetX,
		C3.Plugins.NinePatch.Exps.Width,
		C3.Plugins.NinePatch.Acts.SetY,
		C3.Plugins.Sprite.Exps.Height,
		C3.Plugins.NinePatch.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Acts.SubInstanceVar,
		C3.Plugins.NinePatch.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Cnds.OnAnyAnimFinished,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.NinePatch.Acts.Destroy,
		C3.Plugins.Sprite.Cnds.CompareX,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.NinePatch.Cnds.CompareX,
		C3.Behaviors.Flash.Acts.Flash,
		C3.Plugins.TiledBg.Cnds.CompareX,
		C3.Plugins.TiledBg.Exps.Width,
		C3.Plugins.Sprite.Acts.SetWidth,
		C3.Plugins.Sprite.Acts.MoveToBottom,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.Sprite.Exps.LayerName,
		C3.Plugins.TiledBg.Cnds.CompareInstanceVar,
		C3.Plugins.Spritefont2.Cnds.CompareInstanceVar,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.TiledBg.Acts.SetVisible,
		C3.Plugins.Spritefont2.Acts.SetVisible,
		C3.Plugins.TiledBg.Acts.SetHeight,
		C3.Plugins.TiledBg.Exps.Height,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.Audio.Acts.Preload,
		C3.Plugins.System.Exps.loadingprogress,
		C3.Plugins.System.Cnds.OnLoadFinished,
		C3.Plugins.System.Acts.SetLayerOpacity,
		C3.Plugins.System.Acts.SetTimescale,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.LocalStorage.Cnds.OnItemMissing,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.Touch.Exps.X,
		C3.Plugins.System.Exps.log10,
		C3.Plugins.Audio.Acts.SetVolume,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.System.Cnds.Else,
		C3.JavaScriptInEvents.Addevent_Event30_Act1,
		C3.JavaScriptInEvents.Addevent_Event35_Act6,
		C3.JavaScriptInEvents.Addevent_Event38_Act1,
		C3.JavaScriptInEvents.Addevent_Event40_Act1,
		C3.Plugins.System.Acts.RestartLayout,
		C3.JavaScriptInEvents.Addevent_Event42_Act1,
		C3.Plugins.Sprite.Acts.StartAnim,
		C3.JavaScriptInEvents.Addevent_Event45_Act3,
		C3.Plugins.Browser.Acts.Close,
		C3.JavaScriptInEvents.Addevent_Event47_Act1,
		C3.Plugins.Sprite.Cnds.CompareAnimSpeed,
		C3.JavaScriptInEvents.Addevent_Event49_Act1,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.System.Acts.SetLayerScale,
		C3.Plugins.System.Exps.layeropacity,
		C3.Plugins.System.Exps.layerscale,
		C3.JavaScriptInEvents.Addevent_Event152,
		C3.Plugins.System.Cnds.LayerCmpOpacity,
		C3.Plugins.System.Acts.Signal
	];
};
self.C3_JsPropNameTable = [
	{Rotate: 0},
	{SunLight: 0},
	{EndMusic: 0},
	{EndSound: 0},
	{FramePaused: 0},
	{AreaMusic: 0},
	{SliderMusic: 0},
	{TextPaused: 0},
	{AreaSound: 0},
	{FrameSound: 0},
	{SliderSound: 0},
	{FrameMusic: 0},
	{FrameInfo: 0},
	{TextGameInfo: 0},
	{Fade: 0},
	{TextTapToPlay: 0},
	{TextGameOver: 0},
	{TextYourScore: 0},
	{FrameGui: 0},
	{ID: 0},
	{GuiLife: 0},
	{GuiBullets: 0},
	{GuiScore: 0},
	{GuiTime: 0},
	{MagicName: 0},
	{Size: 0},
	{MagicShadow: 0},
	{GuiEnemyLife: 0},
	{GuiNumber: 0},
	{GuiShield: 0},
	{GuiSpeed: 0},
	{FrameInfoBig: 0},
	{Sine: 0},
	{GameLogo: 0},
	{GameIcon: 0},
	{Speed: 0},
	{Background: 0},
	{Hills: 0},
	{Ground: 0},
	{Bushes: 0},
	{Buildings: 0},
	{Smoke: 0},
	{Clouds: 0},
	{PlayerMenu: 0},
	{EnemyDeadMenu: 0},
	{EnemyWalkMenu: 0},
	{FlyEnemyMenu: 0},
	{EnemiesGuide: 0},
	{Audio: 0},
	{Browser: 0},
	{Keyboard: 0},
	{Mouse: 0},
	{Touch: 0},
	{LocalStorage: 0},
	{ExplosionAir: 0},
	{Touched: 0},
	{ExplosionGround: 0},
	{Fire: 0},
	{EnemiesLife: 0},
	{EnemiesLifeBack: 0},
	{FrameWidthPixels: 0},
	{EnemiesLifeFrame: 0},
	{Hit: 0},
	{Bomb: 0},
	{FireBall: 0},
	{Freeze: 0},
	{Lightning: 0},
	{Fireplace: 0},
	{Frame: 0},
	{Pin: 0},
	{Flash: 0},
	{Player: 0},
	{Damage: 0},
	{Bullet: 0},
	{BoxAmmo: 0},
	{BoxShield: 0},
	{Shield: 0},
	{PlayerShot: 0},
	{Coin: 0},
	{Life: 0},
	{BoxScore: 0},
	{LastScoreFont: 0},
	{BestScoreFont: 0},
	{ScoreFont: 0},
	{TimeFont: 0},
	{MusicFont: 0},
	{SoundFont: 0},
	{LoadingFont: 0},
	{InfoFont: 0},
	{GameOverFont: 0},
	{BulletsFont: 0},
	{MagicTimeFont: 0},
	{DamageFont: 0},
	{MoneyFont: 0},
	{BtnExit: 0},
	{BtnPlay: 0},
	{BtnInfo: 0},
	{BtnMenu: 0},
	{BtnMusic: 0},
	{BtnPause: 0},
	{BtnReload: 0},
	{BtnReturn: 0},
	{BtnSound: 0},
	{BtnStart: 0},
	{BtnGo: 0},
	{BtnRestart: 0},
	{BtnShot: 0},
	{BtnUp: 0},
	{Active: 0},
	{BtnFireMagic: 0},
	{BtnFreezeMagic: 0},
	{BtnLightingMagic: 0},
	{BtnLeft: 0},
	{BtnRight: 0},
	{Solid: 0},
	{CollisionRoad: 0},
	{Platform: 0},
	{ScrollTo: 0},
	{CollisionPlayer: 0},
	{TouchArea: 0},
	{CollisionEnemies: 0},
	{CollisionObject: 0},
	{EnemiesMenuSpawner: 0},
	{Fly: 0},
	{LifeRate: 0},
	{Dead: 0},
	{Reward: 0},
	{CollWidth: 0},
	{CollHeight: 0},
	{FlyEnemy_01: 0},
	{FlyEnemy_02: 0},
	{FlyEnemy_03: 0},
	{Enemy_1: 0},
	{Enemy_2: 0},
	{Enemy_3: 0},
	{Enemy_4: 0},
	{Enemy_5: 0},
	{Enemy_6: 0},
	{Buttons: 0},
	{TextFonts: 0},
	{Enemies: 0},
	{Back: 0},
	{Objects: 0},
	{EnemiesFrame: 0},
	{InfoMenuGui: 0},
	{CoinRandom: 0},
	{FireMagicTime: 0},
	{FireMagicTimeCurrent: 0},
	{FreezeMagicTime: 0},
	{FreezeMagicTimeCurrent: 0},
	{LightningMagicTime: 0},
	{LightningMagicTimeCurrent: 0},
	{ShieldTimer: 0},
	{EnemiesType: 0},
	{EnemiesID: 0},
	{Bullets: 0},
	{Lives: 0},
	{Score: 0},
	{Seconds: 0},
	{Minutes: 0},
	{LastScore: 0},
	{BestScore: 0},
	{CountScore: 0},
	{UserId: 0},
	{EnemiesSpawn: 0},
	{Pause: 0},
	{Sound_db: 0},
	{Sound_Slider: 0},
	{Sound_Volume: 0},
	{Music_db: 0},
	{Music_Slider: 0},
	{Music_Volume: 0}
];

self.InstanceType = {
	SunLight: class extends self.ISpriteInstance {},
	EndMusic: class extends self.ISpriteInstance {},
	EndSound: class extends self.ISpriteInstance {},
	FramePaused: class extends self.ISpriteInstance {},
	AreaMusic: class extends self.ISpriteInstance {},
	SliderMusic: class extends self.ISpriteInstance {},
	TextPaused: class extends self.ISpriteInstance {},
	AreaSound: class extends self.ISpriteInstance {},
	FrameSound: class extends self.ISpriteInstance {},
	SliderSound: class extends self.ISpriteInstance {},
	FrameMusic: class extends self.ISpriteInstance {},
	FrameInfo: class extends self.ISpriteInstance {},
	TextGameInfo: class extends self.ISpriteInstance {},
	TextTapToPlay: class extends self.ISpriteInstance {},
	TextGameOver: class extends self.ISpriteInstance {},
	TextYourScore: class extends self.ISpriteInstance {},
	FrameGui: class extends self.ISpriteInstance {},
	GuiLife: class extends self.ISpriteInstance {},
	GuiBullets: class extends self.ISpriteInstance {},
	GuiScore: class extends self.ISpriteInstance {},
	GuiTime: class extends self.ISpriteInstance {},
	MagicShadow: class extends self.ITiledBackgroundInstance {},
	GuiEnemyLife: class extends self.ISpriteInstance {},
	GuiNumber: class extends self.ISpriteInstance {},
	GuiShield: class extends self.ISpriteInstance {},
	GuiSpeed: class extends self.ISpriteInstance {},
	FrameInfoBig: class extends self.ISpriteInstance {},
	GameLogo: class extends self.ISpriteInstance {},
	GameIcon: class extends self.ISpriteInstance {},
	Background: class extends self.ITiledBackgroundInstance {},
	Hills: class extends self.ITiledBackgroundInstance {},
	Ground: class extends self.ITiledBackgroundInstance {},
	Bushes: class extends self.ISpriteInstance {},
	Buildings: class extends self.ISpriteInstance {},
	Smoke: class extends self.ITiledBackgroundInstance {},
	Clouds: class extends self.ISpriteInstance {},
	PlayerMenu: class extends self.ISpriteInstance {},
	EnemyDeadMenu: class extends self.ISpriteInstance {},
	EnemyWalkMenu: class extends self.ISpriteInstance {},
	FlyEnemyMenu: class extends self.ISpriteInstance {},
	EnemiesGuide: class extends self.ISpriteInstance {},
	Audio: class extends self.IInstance {},
	Browser: class extends self.IInstance {},
	Keyboard: class extends self.IInstance {},
	Mouse: class extends self.IInstance {},
	Touch: class extends self.IInstance {},
	LocalStorage: class extends self.IInstance {},
	ExplosionAir: class extends self.ISpriteInstance {},
	ExplosionGround: class extends self.ISpriteInstance {},
	Fire: class extends self.ISpriteInstance {},
	EnemiesLife: class extends self.I9PatchInstance {},
	EnemiesLifeBack: class extends self.I9PatchInstance {},
	EnemiesLifeFrame: class extends self.I9PatchInstance {},
	Hit: class extends self.ISpriteInstance {},
	Bomb: class extends self.ISpriteInstance {},
	FireBall: class extends self.ISpriteInstance {},
	Freeze: class extends self.ISpriteInstance {},
	Lightning: class extends self.ISpriteInstance {},
	Fireplace: class extends self.ISpriteInstance {},
	Player: class extends self.ISpriteInstance {},
	Bullet: class extends self.ISpriteInstance {},
	BoxAmmo: class extends self.ISpriteInstance {},
	BoxShield: class extends self.ISpriteInstance {},
	Shield: class extends self.ISpriteInstance {},
	PlayerShot: class extends self.ISpriteInstance {},
	Coin: class extends self.ISpriteInstance {},
	Life: class extends self.ISpriteInstance {},
	BoxScore: class extends self.ISpriteInstance {},
	LastScoreFont: class extends self.ISpriteFontInstance {},
	BestScoreFont: class extends self.ISpriteFontInstance {},
	ScoreFont: class extends self.ISpriteFontInstance {},
	TimeFont: class extends self.ISpriteFontInstance {},
	MusicFont: class extends self.ISpriteFontInstance {},
	SoundFont: class extends self.ISpriteFontInstance {},
	LoadingFont: class extends self.ISpriteFontInstance {},
	InfoFont: class extends self.ISpriteFontInstance {},
	GameOverFont: class extends self.ISpriteFontInstance {},
	BulletsFont: class extends self.ISpriteFontInstance {},
	MagicTimeFont: class extends self.ISpriteFontInstance {},
	DamageFont: class extends self.ISpriteFontInstance {},
	MoneyFont: class extends self.ISpriteFontInstance {},
	BtnExit: class extends self.ISpriteInstance {},
	BtnPlay: class extends self.ISpriteInstance {},
	BtnInfo: class extends self.ISpriteInstance {},
	BtnMenu: class extends self.ISpriteInstance {},
	BtnMusic: class extends self.ISpriteInstance {},
	BtnPause: class extends self.ISpriteInstance {},
	BtnReload: class extends self.ISpriteInstance {},
	BtnReturn: class extends self.ISpriteInstance {},
	BtnSound: class extends self.ISpriteInstance {},
	BtnStart: class extends self.ISpriteInstance {},
	BtnGo: class extends self.ISpriteInstance {},
	BtnRestart: class extends self.ISpriteInstance {},
	BtnShot: class extends self.ISpriteInstance {},
	BtnUp: class extends self.ISpriteInstance {},
	BtnFireMagic: class extends self.ISpriteInstance {},
	BtnFreezeMagic: class extends self.ISpriteInstance {},
	BtnLightingMagic: class extends self.ISpriteInstance {},
	BtnLeft: class extends self.ISpriteInstance {},
	BtnRight: class extends self.ISpriteInstance {},
	CollisionRoad: class extends self.ISpriteInstance {},
	CollisionPlayer: class extends self.ISpriteInstance {},
	TouchArea: class extends self.ISpriteInstance {},
	CollisionEnemies: class extends self.ISpriteInstance {},
	CollisionObject: class extends self.ISpriteInstance {},
	EnemiesMenuSpawner: class extends self.ISpriteInstance {},
	FlyEnemy_01: class extends self.ISpriteInstance {},
	FlyEnemy_02: class extends self.ISpriteInstance {},
	FlyEnemy_03: class extends self.ISpriteInstance {},
	Enemy_1: class extends self.ISpriteInstance {},
	Enemy_2: class extends self.ISpriteInstance {},
	Enemy_3: class extends self.ISpriteInstance {},
	Enemy_4: class extends self.ISpriteInstance {},
	Enemy_5: class extends self.ISpriteInstance {},
	Enemy_6: class extends self.ISpriteInstance {},
	Buttons: class extends self.ISpriteInstance {},
	TextFonts: class extends self.ISpriteInstance {},
	Enemies: class extends self.ISpriteInstance {},
	Back: class extends self.ITiledBackgroundInstance {},
	Objects: class extends self.ISpriteInstance {},
	EnemiesFrame: class extends self.I9PatchInstance {},
	InfoMenuGui: class extends self.ISpriteInstance {}
}