const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Audio,
		C3.Plugins.Browser,
		C3.Plugins.Touch,
		C3.Plugins.Mouse,
		C3.Plugins.Keyboard,
		C3.Plugins.LocalStorage,
		C3.Plugins.Sprite,
		C3.Behaviors.Rotate,
		C3.Plugins.Spritefont2,
		C3.Plugins.TiledBg,
		C3.Behaviors.Bullet,
		C3.Behaviors.Fade,
		C3.Behaviors.Sin,
		C3.Behaviors.Platform,
		C3.Behaviors.Flash,
		C3.Behaviors.solid,
		C3.Behaviors.wrap,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Acts.SetGroupActive,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Acts.SetTimescale,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.Spritefont2.Acts.SetY,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.System.Exps.projectname,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.Spritefont2.Acts.SetText,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Behaviors.Platform.Acts.SimulateControl,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Behaviors.Platform.Cnds.IsOnFloor,
		C3.Plugins.Sprite.Cnds.OnAnimFinished,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.Sprite.Cnds.IsOutsideLayout,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.SetCollisions,
		C3.Behaviors.Fade.Acts.StartFade,
		C3.Behaviors.Bullet.Acts.SetSpeed,
		C3.Plugins.Sprite.Acts.StopAnim,
		C3.Plugins.TiledBg.Cnds.CompareX,
		C3.Plugins.TiledBg.Exps.Width,
		C3.Plugins.TiledBg.Acts.SetX,
		C3.Plugins.TiledBg.Exps.X,
		C3.Plugins.System.Exps.layoutwidth,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Behaviors.Flash.Acts.Flash,
		C3.Behaviors.Fade.Cnds.OnFadeOutEnd,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.System.Acts.Wait,
		C3.JavaScriptInEvents.Game_events_Event133_Act27,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.JavaScriptInEvents.Game_events_Event147_Act2,
		C3.Plugins.System.Exps.loadingprogress,
		C3.Plugins.Sprite.Acts.SetWidth,
		C3.Plugins.System.Cnds.OnLoadFinished,
		C3.Plugins.Audio.Acts.Preload,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Acts.GoToLayout,
		C3.JavaScriptInEvents.Loading_events_Event2_Act24,
		C3.Plugins.Sprite.Cnds.OnDestroyed,
		C3.JavaScriptInEvents.Global_events_Event40_Act2,
		C3.JavaScriptInEvents.Global_events_Event41_Act2,
		C3.Plugins.System.Acts.RestartLayout,
		C3.JavaScriptInEvents.Global_events_Event42_Act2,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Mouse.Cnds.IsButtonDown,
		C3.Plugins.Mouse.Acts.SetCursorSprite,
		C3.Plugins.Mouse.Cnds.IsOverObject,
		C3.Behaviors.Sin.Acts.SetEnabled,
		C3.Plugins.Sprite.Acts.SetSize
	];
};
self.C3_JsPropNameTable = [
	{Audio: 0},
	{Browser: 0},
	{Touch: 0},
	{Mouse: 0},
	{Keyboard: 0},
	{LocalStorage: 0},
	{GuiBullet: 0},
	{GuiKills: 0},
	{GuiLife: 0},
	{Cursor: 0},
	{CursorHover: 0},
	{Frame: 0},
	{Score100: 0},
	{Rotate: 0},
	{SunLight: 0},
	{Score200: 0},
	{Score300: 0},
	{Score500: 0},
	{Score5000: 0},
	{BestDistFont: 0},
	{BestKillsFont: 0},
	{BulletFont: 0},
	{DistanceFont: 0},
	{GameOverFont: 0},
	{HighScoreFont: 0},
	{KillsFont: 0},
	{LastDistFont: 0},
	{LastKillsFont: 0},
	{LastScoreFont: 0},
	{LoadingFont: 0},
	{NewDistFont: 0},
	{NewKillsFont: 0},
	{NewScoreFont: 0},
	{ScoreFont: 0},
	{TimeFont: 0},
	{BtnFire: 0},
	{BtnMenu: 0},
	{BtnMusic: 0},
	{BtnPause: 0},
	{BtnPlay: 0},
	{BtnRestart: 0},
	{BtnSound: 0},
	{BtnUp: 0},
	{Bullet: 0},
	{Background: 0},
	{Box: 0},
	{Bush: 0},
	{Cactus: 0},
	{House: 0},
	{Loading: 0},
	{LoadingBar: 0},
	{LoadingBarBackground: 0},
	{MenuPlayer: 0},
	{Road: 0},
	{Tree: 0},
	{Scarecrow: 0},
	{Skeleton: 0},
	{AmmoBox: 0},
	{Bomb: 0},
	{Coin: 0},
	{Fade: 0},
	{Enemy: 0},
	{Enemy2: 0},
	{Enemy3: 0},
	{Enemy4: 0},
	{Enemy5: 0},
	{Explosion: 0},
	{Sine: 0},
	{Life: 0},
	{Money: 0},
	{Platform: 0},
	{Flash: 0},
	{Player: 0},
	{Wheel: 0},
	{BlackColor: 0},
	{CollisionDestroyer: 0},
	{Solid: 0},
	{Wrap: 0},
	{CollisionPlayer: 0},
	{GameLogo: 0},
	{MouseOver: 0},
	{ButtonsSound: 0},
	{Score: 0},
	{Kills: 0},
	{LastKills: 0},
	{BestKills: 0},
	{Dist: 0},
	{BestDist: 0},
	{LastDist: 0},
	{Pause: 0},
	{Seconds: 0},
	{Minutes: 0},
	{LastScore: 0},
	{HighScore: 0},
	{Music: 0},
	{Sound: 0}
];

self.InstanceType = {
	Audio: class extends self.IInstance {},
	Browser: class extends self.IInstance {},
	Touch: class extends self.IInstance {},
	Mouse: class extends self.IInstance {},
	Keyboard: class extends self.IInstance {},
	LocalStorage: class extends self.IInstance {},
	GuiBullet: class extends self.ISpriteInstance {},
	GuiKills: class extends self.ISpriteInstance {},
	GuiLife: class extends self.ISpriteInstance {},
	Cursor: class extends self.ISpriteInstance {},
	CursorHover: class extends self.ISpriteInstance {},
	Frame: class extends self.ISpriteInstance {},
	Score100: class extends self.ISpriteInstance {},
	SunLight: class extends self.ISpriteInstance {},
	Score200: class extends self.ISpriteInstance {},
	Score300: class extends self.ISpriteInstance {},
	Score500: class extends self.ISpriteInstance {},
	Score5000: class extends self.ISpriteInstance {},
	BestDistFont: class extends self.ISpriteFontInstance {},
	BestKillsFont: class extends self.ISpriteFontInstance {},
	BulletFont: class extends self.ISpriteFontInstance {},
	DistanceFont: class extends self.ISpriteFontInstance {},
	GameOverFont: class extends self.ISpriteFontInstance {},
	HighScoreFont: class extends self.ISpriteFontInstance {},
	KillsFont: class extends self.ISpriteFontInstance {},
	LastDistFont: class extends self.ISpriteFontInstance {},
	LastKillsFont: class extends self.ISpriteFontInstance {},
	LastScoreFont: class extends self.ISpriteFontInstance {},
	LoadingFont: class extends self.ISpriteFontInstance {},
	NewDistFont: class extends self.ISpriteFontInstance {},
	NewKillsFont: class extends self.ISpriteFontInstance {},
	NewScoreFont: class extends self.ISpriteFontInstance {},
	ScoreFont: class extends self.ISpriteFontInstance {},
	TimeFont: class extends self.ISpriteFontInstance {},
	BtnFire: class extends self.ISpriteInstance {},
	BtnMenu: class extends self.ISpriteInstance {},
	BtnMusic: class extends self.ISpriteInstance {},
	BtnPause: class extends self.ISpriteInstance {},
	BtnPlay: class extends self.ISpriteInstance {},
	BtnRestart: class extends self.ISpriteInstance {},
	BtnSound: class extends self.ISpriteInstance {},
	BtnUp: class extends self.ISpriteInstance {},
	Background: class extends self.ITiledBackgroundInstance {},
	Box: class extends self.ISpriteInstance {},
	Bush: class extends self.ISpriteInstance {},
	Cactus: class extends self.ISpriteInstance {},
	House: class extends self.ISpriteInstance {},
	Loading: class extends self.ISpriteInstance {},
	LoadingBar: class extends self.ISpriteInstance {},
	LoadingBarBackground: class extends self.ISpriteInstance {},
	MenuPlayer: class extends self.ISpriteInstance {},
	Road: class extends self.ITiledBackgroundInstance {},
	Tree: class extends self.ISpriteInstance {},
	Scarecrow: class extends self.ISpriteInstance {},
	Skeleton: class extends self.ISpriteInstance {},
	AmmoBox: class extends self.ISpriteInstance {},
	Bomb: class extends self.ISpriteInstance {},
	Bullet: class extends self.ISpriteInstance {},
	Coin: class extends self.ISpriteInstance {},
	Enemy: class extends self.ISpriteInstance {},
	Enemy2: class extends self.ISpriteInstance {},
	Enemy3: class extends self.ISpriteInstance {},
	Enemy4: class extends self.ISpriteInstance {},
	Enemy5: class extends self.ISpriteInstance {},
	Explosion: class extends self.ISpriteInstance {},
	Life: class extends self.ISpriteInstance {},
	Money: class extends self.ISpriteInstance {},
	Player: class extends self.ISpriteInstance {},
	Wheel: class extends self.ISpriteInstance {},
	BlackColor: class extends self.ISpriteInstance {},
	CollisionDestroyer: class extends self.ISpriteInstance {},
	CollisionPlayer: class extends self.ISpriteInstance {},
	GameLogo: class extends self.ISpriteInstance {},
	MouseOver: class extends self.ISpriteInstance {},
	ButtonsSound: class extends self.ISpriteInstance {},
	Score: class extends self.ISpriteInstance {}
}