const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Audio,
		C3.Plugins.Browser,
		C3.Plugins.Arr,
		C3.Plugins.Function,
		C3.Plugins.Touch,
		C3.Plugins.LocalStorage,
		C3.Plugins.Spritefont2,
		C3.Behaviors.Bullet,
		C3.Behaviors.Fade,
		C3.Plugins.Sprite,
		C3.Behaviors.Sin,
		C3.Plugins.Particles,
		C3.Behaviors.Rotate,
		C3.Behaviors.Pin,
		C3.Plugins.TiledBg,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Acts.SetGroupActive,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.JavaScriptInEvents.Game_events_Event2_Act7,
		C3.Plugins.Function.Cnds.OnFunction,
		C3.Plugins.Sprite.Cnds.PickByUID,
		C3.Plugins.Arr.Exps.At,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.Sprite.Cnds.OnDestroyed,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.System.Exps.layoutheight,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.System.Exps.int,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Sprite.Exps.AnimationFrameCount,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Exps.AnimationFrame,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Behaviors.Pin.Acts.Pin,
		C3.Plugins.Sprite.Cnds.CompareY,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Sprite.Acts.MoveAtAngle,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.Arr.Acts.SetSize,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Arr.Acts.SetX,
		C3.Plugins.Sprite.Exps.UID,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Sprite.Acts.SetWidth,
		C3.Plugins.Touch.Exps.X,
		C3.Plugins.Touch.Exps.Y,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.Sprite.Cnds.CompareWidth,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Touch.Cnds.OnTouchEnd,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Spritefont2.Acts.SetText,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Cnds.PickAll,
		C3.Plugins.Arr.Acts.Clear,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.Sprite.Acts.StartAnim,
		C3.Plugins.System.Acts.GoToLayout,
		C3.JavaScriptInEvents.Game_events_Event53_Act4,
		C3.JavaScriptInEvents.Game_events_Event54_Act4,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Behaviors.Bullet.Acts.SetAngleOfMotion,
		C3.Plugins.Sprite.Acts.SetPosToObject,
		C3.Plugins.Audio.Acts.StopAll,
		C3.Plugins.Audio.Cnds.IsTagPlaying,
		C3.JavaScriptInEvents.Game_events_Event65_Act6,
		C3.JavaScriptInEvents.Game_events_Event68_Act7,
		C3.JavaScriptInEvents.Game_events_Event72_Act11,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.System.Exps.projectname,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.JavaScriptInEvents.Main_events_Event9_Act4,
		C3.JavaScriptInEvents.Main_events_Event10_Act4,
		C3.JavaScriptInEvents.Main_events_Event11_Act4,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.JavaScriptInEvents.Main_events_Event17_Act3,
		C3.Plugins.Browser.Acts.Close
	];
};
self.C3_JsPropNameTable = [
	{Audio: 0},
	{Browser: 0},
	{DotsUIDS: 0},
	{Function: 0},
	{LinesUIDS: 0},
	{Touch: 0},
	{LocalStorage: 0},
	{BestScoreFont: 0},
	{Bullet: 0},
	{Fade: 0},
	{BonusFont: 0},
	{LastScoreFont: 0},
	{ScoreFont: 0},
	{TimeFont: 0},
	{GameOverFont: 0},
	{isConnected: 0},
	{color: 0},
	{Dot: 0},
	{Sine: 0},
	{GameLogo: 0},
	{Particles: 0},
	{ButtonPause: 0},
	{ButtonPlay: 0},
	{ButtonSound: 0},
	{Line: 0},
	{Grid: 0},
	{Background: 0},
	{ButtonMenu: 0},
	{ButtonExit: 0},
	{ButtonRestart: 0},
	{Rotate: 0},
	{SunLight: 0},
	{Pin: 0},
	{Detector: 0},
	{FadeMenu: 0},
	{FadeGame: 0},
	{Dots: 0},
	{Pause: 0},
	{Sound: 0},
	{Combo: 0},
	{BestScore: 0},
	{LastScore: 0},
	{TimeGame: 0},
	{Score: 0},
	{MegScore: 0},
	{GROUND: 0},
	{ConnectedCount: 0},
	{CurrentColor: 0},
	{CurrentPos: 0},
	{UserId: 0},
	{Draging: 0},
	{SoundOn: 0}
];

self.InstanceType = {
	Audio: class extends self.IInstance {},
	Browser: class extends self.IInstance {},
	DotsUIDS: class extends self.IArrayInstance {},
	Function: class extends self.IInstance {},
	LinesUIDS: class extends self.IArrayInstance {},
	Touch: class extends self.IInstance {},
	LocalStorage: class extends self.IInstance {},
	BestScoreFont: class extends self.ISpriteFontInstance {},
	BonusFont: class extends self.ISpriteFontInstance {},
	LastScoreFont: class extends self.ISpriteFontInstance {},
	ScoreFont: class extends self.ISpriteFontInstance {},
	TimeFont: class extends self.ISpriteFontInstance {},
	GameOverFont: class extends self.ISpriteFontInstance {},
	Dot: class extends self.ISpriteInstance {},
	GameLogo: class extends self.ISpriteInstance {},
	Particles: class extends self.IParticlesInstance {},
	ButtonPause: class extends self.ISpriteInstance {},
	ButtonPlay: class extends self.ISpriteInstance {},
	ButtonSound: class extends self.ISpriteInstance {},
	Line: class extends self.ISpriteInstance {},
	Grid: class extends self.ISpriteInstance {},
	Background: class extends self.ISpriteInstance {},
	ButtonMenu: class extends self.ISpriteInstance {},
	ButtonExit: class extends self.ISpriteInstance {},
	ButtonRestart: class extends self.ISpriteInstance {},
	SunLight: class extends self.ISpriteInstance {},
	Detector: class extends self.ISpriteInstance {},
	FadeMenu: class extends self.ISpriteInstance {},
	FadeGame: class extends self.ITiledBackgroundInstance {},
	Dots: class extends self.ISpriteInstance {}
}