const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Rotate,
		C3.Behaviors.Bullet,
		C3.Behaviors.Fade,
		C3.Plugins.Spritefont2,
		C3.Plugins.TiledBg,
		C3.Behaviors.scrollto,
		C3.Plugins.Touch,
		C3.Plugins.Mouse,
		C3.Plugins.Text,
		C3.Plugins.LocalStorage,
		C3.Plugins.Browser,
		C3.Plugins.XML,
		C3.Plugins.AJAX,
		C3.Behaviors.Physics,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Spritefont2.Acts.SetText,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Behaviors.Physics.Acts.SetWorldGravity,
		C3.Plugins.Sprite.Acts.SetPosToObject,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.System.Cnds.CompareVar,
		C3.JavaScriptInEvents.Events_game_Event3_Act1,
		C3.Plugins.Touch.Cnds.OnTouchStart,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.System.Exps.fps,
		C3.Plugins.Sprite.Acts.MoveAtAngle,
		C3.Plugins.System.Acts.GoToLayoutByName,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.System.Acts.RestartLayout,
		C3.JavaScriptInEvents.Events_game_Event13_Act5,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Behaviors.Fade.Acts.StartFade,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.Mouse.Cnds.IsOverObject,
		C3.Plugins.Mouse.Acts.SetCursor,
		C3.Plugins.Touch.Exps.X,
		C3.Plugins.Touch.Exps.Y,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Touch.Cnds.IsInTouch,
		C3.Plugins.Sprite.Cnds.CompareX,
		C3.Plugins.System.Exps.layoutwidth,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.Sprite.Cnds.CompareY,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Exps.random,
		C3.Behaviors.Bullet.Acts.SetAngleOfMotion,
		C3.Behaviors.Bullet.Acts.SetSpeed,
		C3.Behaviors.Rotate.Acts.SetSpeed,
		C3.Plugins.Sprite.Acts.SetScale,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Sprite.Acts.SetCollisions,
		C3.JavaScriptInEvents.Events_game_Event60_Act5,
		C3.Plugins.System.Exps.choose,
		C3.JavaScriptInEvents.Events_game_Event64_Act6,
		C3.Plugins.Sprite.Cnds.OnDestroyed,
		C3.Plugins.Sprite.Cnds.IsOnScreen,
		C3.Behaviors.Physics.Acts.SetVelocity,
		C3.Plugins.System.Exps.int,
		C3.Behaviors.Physics.Exps.VelocityX,
		C3.Behaviors.Physics.Exps.VelocityY,
		C3.Behaviors.Physics.Cnds.CompareVelocity,
		C3.Behaviors.Physics.Acts.ApplyForce,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Acts.SubInstanceVar,
		C3.Behaviors.Physics.Cnds.CompareAngularVelocity,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Acts.GetItem,
		C3.Plugins.LocalStorage.Cnds.OnItemGet,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.JavaScriptInEvents.Events_home_Event30_Act2,
		C3.Plugins.Spritefont2.Acts.SetVisible,
		C3.Plugins.AJAX.Acts.Request,
		C3.Plugins.AJAX.Cnds.OnComplete,
		C3.Plugins.XML.Acts.Load,
		C3.Plugins.AJAX.Exps.LastData,
		C3.Plugins.XML.Exps.StringValue,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Browser.Acts.GoToURLWindow
	];
};
self.C3_JsPropNameTable = [
	{motion: 0},
	{motion_value_distance: 0},
	{motion_valeu_distance_start: 0},
	{motion_value_speed: 0},
	{motion_value_angle: 0},
	{enemy_ball_blue: 0},
	{enemy_ball_green: 0},
	{enemy_diamond_blue: 0},
	{enemy_ball_yellow: 0},
	{enemy_diamond_red: 0},
	{enemy_diamond_green: 0},
	{enemy_diamond_yellow: 0},
	{enemy_hexagon_red: 0},
	{enemy_more_blue: 0},
	{enemy_more_yellow: 0},
	{enemy_hexagon_yellow: 0},
	{enemy_more_green: 0},
	{enemy_ball_red: 0},
	{enemy_more_red: 0},
	{enemy_hexagon_blue: 0},
	{enemy_square_blue: 0},
	{enemy_side_yellow: 0},
	{enemy_side_red: 0},
	{enemy_side_green: 0},
	{enemy_square_green: 0},
	{enemy_square_red: 0},
	{enemy_hexagon_green: 0},
	{enemy_side_blue: 0},
	{enemy_square_yellow: 0},
	{enemy_star_blue: 0},
	{enemy_star_green: 0},
	{enemy_star_red: 0},
	{enemy_star_yellow: 0},
	{enemy_triangle_blue: 0},
	{enemy_triangle_green: 0},
	{enemy_triangle_red: 0},
	{enemy_triangle_yellow: 0},
	{character_ball: 0},
	{character_square: 0},
	{character_triangle: 0},
	{character_star: 0},
	{character_diamond: 0},
	{character_hexagon: 0},
	{character_more: 0},
	{Rotate: 0},
	{Bullet: 0},
	{effect_dead: 0},
	{Fade: 0},
	{effect_dead_white: 0},
	{effect_smoke: 0},
	{effect_win: 0},
	{stage_25: 0},
	{stage_50: 0},
	{stage_75: 0},
	{stage_final: 0},
	{stage_font: 0},
	{stage_start: 0},
	{stage_swipe: 0},
	{stage_background: 0},
	{ScrollTo: 0},
	{z_element_camera: 0},
	{z_element_character_position_start: 0},
	{z_element_touch_position_now: 0},
	{z_element_touch_position_start: 0},
	{motion_enemy_format: 0},
	{motion_enemy_color: 0},
	{motion_distance_character: 0},
	{motion_create_count: 0},
	{motion_create_time: 0},
	{z_element_create_enemy: 0},
	{button_home: 0},
	{status: 0},
	{level_number: 0},
	{button_level: 0},
	{layout_font: 0},
	{button_logo: 0},
	{share_facebook: 0},
	{logo_color_pump: 0},
	{share_twitter: 0},
	{background_bottom: 0},
	{Touch: 0},
	{Mouse: 0},
	{Text: 0},
	{LocalStorage: 0},
	{Browser: 0},
	{XML: 0},
	{AJAX: 0},
	{Physics: 0},
	{enemies: 0},
	{characters: 0},
	{enemies_red: 0},
	{enemies_blue: 0},
	{enemies_green: 0},
	{enemies_yellow: 0},
	{game_status: 0},
	{game_touch: 0},
	{game_level_color: 0},
	{game_level_format: 0},
	{gameplay_character: 0},
	{game_level_now: 0},
	{character_posx: 0},
	{character_posy: 0},
	{level_1: 0},
	{level_2: 0},
	{level_3: 0},
	{level_4: 0},
	{level_5: 0},
	{level_6: 0},
	{level_7: 0},
	{level_8: 0},
	{level_9: 0},
	{level_10: 0},
	{level_11: 0},
	{level_12: 0},
	{level_13: 0},
	{level_14: 0},
	{level_15: 0},
	{level_16: 0},
	{level_17: 0},
	{level_18: 0},
	{level_19: 0},
	{level_20: 0},
	{level_21: 0},
	{level_22: 0},
	{level_23: 0},
	{level_24: 0},
	{level_25: 0},
	{level_26: 0},
	{level_27: 0},
	{level_28: 0},
	{level_29: 0},
	{level_30: 0},
	{level_31: 0},
	{level_32: 0},
	{level_33: 0},
	{level_34: 0},
	{level_35: 0},
	{level_36: 0},
	{level_37: 0},
	{level_38: 0},
	{level_39: 0},
	{level_40: 0},
	{facebookShare: 0},
	{facebook_message: 0},
	{twitterShare: 0},
	{twitter_message: 0}
];

self.InstanceType = {
	enemy_ball_blue: class extends self.ISpriteInstance {},
	enemy_ball_green: class extends self.ISpriteInstance {},
	enemy_diamond_blue: class extends self.ISpriteInstance {},
	enemy_ball_yellow: class extends self.ISpriteInstance {},
	enemy_diamond_red: class extends self.ISpriteInstance {},
	enemy_diamond_green: class extends self.ISpriteInstance {},
	enemy_diamond_yellow: class extends self.ISpriteInstance {},
	enemy_hexagon_red: class extends self.ISpriteInstance {},
	enemy_more_blue: class extends self.ISpriteInstance {},
	enemy_more_yellow: class extends self.ISpriteInstance {},
	enemy_hexagon_yellow: class extends self.ISpriteInstance {},
	enemy_more_green: class extends self.ISpriteInstance {},
	enemy_ball_red: class extends self.ISpriteInstance {},
	enemy_more_red: class extends self.ISpriteInstance {},
	enemy_hexagon_blue: class extends self.ISpriteInstance {},
	enemy_square_blue: class extends self.ISpriteInstance {},
	enemy_side_yellow: class extends self.ISpriteInstance {},
	enemy_side_red: class extends self.ISpriteInstance {},
	enemy_side_green: class extends self.ISpriteInstance {},
	enemy_square_green: class extends self.ISpriteInstance {},
	enemy_square_red: class extends self.ISpriteInstance {},
	enemy_hexagon_green: class extends self.ISpriteInstance {},
	enemy_side_blue: class extends self.ISpriteInstance {},
	enemy_square_yellow: class extends self.ISpriteInstance {},
	enemy_star_blue: class extends self.ISpriteInstance {},
	enemy_star_green: class extends self.ISpriteInstance {},
	enemy_star_red: class extends self.ISpriteInstance {},
	enemy_star_yellow: class extends self.ISpriteInstance {},
	enemy_triangle_blue: class extends self.ISpriteInstance {},
	enemy_triangle_green: class extends self.ISpriteInstance {},
	enemy_triangle_red: class extends self.ISpriteInstance {},
	enemy_triangle_yellow: class extends self.ISpriteInstance {},
	character_ball: class extends self.ISpriteInstance {},
	character_square: class extends self.ISpriteInstance {},
	character_triangle: class extends self.ISpriteInstance {},
	character_star: class extends self.ISpriteInstance {},
	character_diamond: class extends self.ISpriteInstance {},
	character_hexagon: class extends self.ISpriteInstance {},
	character_more: class extends self.ISpriteInstance {},
	effect_dead: class extends self.ISpriteInstance {},
	effect_dead_white: class extends self.ISpriteInstance {},
	effect_smoke: class extends self.ISpriteInstance {},
	effect_win: class extends self.ISpriteInstance {},
	stage_25: class extends self.ISpriteInstance {},
	stage_50: class extends self.ISpriteInstance {},
	stage_75: class extends self.ISpriteInstance {},
	stage_final: class extends self.ISpriteInstance {},
	stage_font: class extends self.ISpriteFontInstance {},
	stage_start: class extends self.ISpriteInstance {},
	stage_swipe: class extends self.ISpriteInstance {},
	stage_background: class extends self.ITiledBackgroundInstance {},
	z_element_camera: class extends self.ISpriteInstance {},
	z_element_character_position_start: class extends self.ISpriteInstance {},
	z_element_touch_position_now: class extends self.ISpriteInstance {},
	z_element_touch_position_start: class extends self.ISpriteInstance {},
	z_element_create_enemy: class extends self.ISpriteInstance {},
	button_home: class extends self.ISpriteInstance {},
	button_level: class extends self.ISpriteInstance {},
	layout_font: class extends self.ISpriteFontInstance {},
	button_logo: class extends self.ISpriteInstance {},
	share_facebook: class extends self.ISpriteInstance {},
	logo_color_pump: class extends self.ISpriteInstance {},
	share_twitter: class extends self.ISpriteInstance {},
	background_bottom: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {},
	Mouse: class extends self.IInstance {},
	Text: class extends self.ITextInstance {},
	LocalStorage: class extends self.IInstance {},
	Browser: class extends self.IInstance {},
	XML: class extends self.IInstance {},
	AJAX: class extends self.IInstance {},
	enemies: class extends self.ISpriteInstance {},
	characters: class extends self.ISpriteInstance {},
	enemies_red: class extends self.ISpriteInstance {},
	enemies_blue: class extends self.ISpriteInstance {},
	enemies_green: class extends self.ISpriteInstance {},
	enemies_yellow: class extends self.ISpriteInstance {}
}