const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Sin,
		C3.Behaviors.Fade,
		C3.Plugins.Touch,
		C3.Plugins.Audio,
		C3.Plugins.Browser,
		C3.Plugins.Keyboard,
		C3.Behaviors.Pin,
		C3.Behaviors.Physics,
		C3.Behaviors.solid,
		C3.Behaviors.scrollto,
		C3.Plugins.TiledBg,
		C3.Plugins.Spritefont2,
		C3.Behaviors.Bullet,
		C3.Plugins.Particles,
		C3.Behaviors.Rotate,
		C3.Behaviors.LOS,
		C3.Plugins.Button,
		C3.Behaviors.EightDir,
		C3.Plugins.Function,
		C3.Plugins.LocalStorage,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.IsMobile,
		C3.Plugins.Browser.Cnds.IsPortraitLandscape,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.System.Acts.SetTimescale,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Audio.Acts.SetSilent,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Audio.Acts.StopAll,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Behaviors.Bullet.Acts.SetEnabled,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Behaviors.Physics.Acts.SetWorldGravity,
		C3.Plugins.Audio.Acts.PlayByName,
		C3.Plugins.System.Exps.choose,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Behaviors.Fade.Acts.StartFade,
		C3.Plugins.Spritefont2.Acts.Destroy,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Spritefont2.Acts.SetPos,
		C3.Plugins.Button.Acts.SetPos,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Behaviors.Physics.Acts.ApplyImpulseAtAngle,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.JavaScriptInEvents.Gameplay_Event41_Act6,
		C3.JavaScriptInEvents.Gameplay_Event42_Act6,
		C3.Plugins.Sprite.Cnds.PickDistance,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.Sprite.Acts.SetPosToObject,
		C3.Plugins.Touch.Cnds.IsInTouch,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.Touch.Exps.X,
		C3.Plugins.Touch.Exps.Y,
		C3.Plugins.Sprite.Acts.MoveAtAngle,
		C3.Plugins.Sprite.Exps.Angle,
		C3.Plugins.System.Exps.min,
		C3.Plugins.Sprite.Acts.SetWidth,
		C3.Plugins.Touch.Cnds.OnTouchEnd,
		C3.Plugins.Spritefont2.Acts.SetVisible,
		C3.Behaviors.Physics.Acts.SetAngularVelocity,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Behaviors.Bullet.Acts.SetAngleOfMotion,
		C3.Plugins.Touch.Cnds.OnTouchStart,
		C3.Behaviors.Physics.Cnds.CompareVelocity,
		C3.Plugins.Function.Acts.CallFunction,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Cnds.OnDestroyed,
		C3.JavaScriptInEvents.Gameplay_Event52_Act19,
		C3.Plugins.Sprite.Cnds.PickTopBottom,
		C3.Plugins.Function.Cnds.OnFunction,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Cnds.IsVisible,
		C3.Plugins.Sprite.Acts.SetScale,
		C3.Behaviors.Sin.Acts.SetMagnitude,
		C3.Behaviors.Pin.Acts.Pin,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Behaviors.Sin.Cnds.CompareMagnitude,
		C3.Behaviors.Sin.Exps.Magnitude,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.System.Acts.GoToLayoutByName,
		C3.JavaScriptInEvents.Gameplay_Event66_Act5,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Behaviors.LOS.Cnds.HasLOSToObject,
		C3.Plugins.Spritefont2.Acts.SetText,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Plugins.Sprite.Cnds.IsOnScreen,
		C3.JavaScriptInEvents.Gameplay_Event79_Act5,
		C3.JavaScriptInEvents.Gameplay_Event80_Act5,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.Sprite.Acts.SetCollisions,
		C3.Behaviors.Bullet.Exps.DistanceTravelled,
		C3.Behaviors.Bullet.Acts.SetSpeed,
		C3.Behaviors.Bullet.Exps.Speed,
		C3.Behaviors.EightDir.Acts.SetVectorX,
		C3.Behaviors.EightDir.Acts.SetVectorY,
		C3.Plugins.Sprite.Cnds.OnAnimFinished,
		C3.Behaviors.Physics.Acts.SetVelocity,
		C3.Plugins.Particles.Acts.SetSpraying,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Cnds.PickRandom,
		C3.Plugins.Particles.Acts.SetAngle,
		C3.Behaviors.Physics.Acts.SetEnabled,
		C3.Behaviors.Physics.Acts.EnableCollisions,
		C3.Behaviors.Physics.Acts.CreateDistanceJoint,
		C3.Plugins.System.Acts.SubVar,
		C3.Behaviors.Sin.Acts.SetEnabled,
		C3.JavaScriptInEvents.Shop_Event54_Act4,
		C3.JavaScriptInEvents.Shop_Event55_Act4,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Acts.GetItem,
		C3.Plugins.LocalStorage.Cnds.OnItemMissing,
		C3.Plugins.LocalStorage.Cnds.OnItemGet,
		C3.Plugins.LocalStorage.Exps.ItemValue
	];
};
self.C3_JsPropNameTable = [
	{Sine: 0},
	{Fade: 0},
	{GameTittle: 0},
	{ShopCoinUI: 0},
	{Touch: 0},
	{Audio: 0},
	{FadeScreen: 0},
	{Browser: 0},
	{SoundUI: 0},
	{Keyboard: 0},
	{Pin: 0},
	{TntEffect: 0},
	{RotateScreen: 0},
	{avalaibles: 0},
	{avalaible: 0},
	{PinnerPick1: 0},
	{Physics: 0},
	{GamePlayer: 0},
	{Arms1: 0},
	{Arms2: 0},
	{Limiter: 0},
	{PlayerSkin1: 0},
	{Solid: 0},
	{SideWall2: 0},
	{PlayerSkin2: 0},
	{ScrollTo: 0},
	{GameCamera: 0},
	{GameBackground: 0},
	{ShopButton: 0},
	{RewardsButton: 0},
	{Tutorial: 0},
	{CoinUI: 0},
	{CoinFontGame: 0},
	{SideWallBackground: 0},
	{SideWallBackground2: 0},
	{MainPillar: 0},
	{Grass3: 0},
	{Grass1: 0},
	{LightEffect: 0},
	{Grass2: 0},
	{Bullet: 0},
	{WaterBackground: 0},
	{BlockParticles1: 0},
	{BlockParticles2: 0},
	{SideWall1: 0},
	{PlayerParticles: 0},
	{PillarObstacle: 0},
	{PinnerPick2: 0},
	{PinnerPick3: 0},
	{SlingsBackground: 0},
	{Rotate: 0},
	{EnemyBlade1: 0},
	{Coinmagnet: 0},
	{LineOfSight: 0},
	{Coin1: 0},
	{WallBrick: 0},
	{Sine2: 0},
	{WallEnemy1: 0},
	{WallEnemy2: 0},
	{PinnerPickRed: 0},
	{SideWallCone: 0},
	{HalfWallSpin: 0},
	{BubbleParticles: 0},
	{GameoverButtons: 0},
	{MoreGameButton: 0},
	{RestartButton: 0},
	{FadeGameover: 0},
	{GameoverScreen: 0},
	{BestScoreFont: 0},
	{GameOverScoreFont: 0},
	{EndCoinFont: 0},
	{JumpEffect: 0},
	{Collitionbox1: 0},
	{Collitionbox2: 0},
	{BloodParticles: 0},
	{SmokeEffect: 0},
	{CoinParticles: 0},
	{EnemyBlade2: 0},
	{DiamondItem: 0},
	{DiamondParticles: 0},
	{Pinballs1: 0},
	{WheelFire1: 0},
	{FireEffect1: 0},
	{PinnerPick5: 0},
	{Pinballs2: 0},
	{WheelFire2: 0},
	{PinnerPick6: 0},
	{CannonBow: 0},
	{EnemyArrow: 0},
	{ArrowStick: 0},
	{CannonBow2: 0},
	{FireEffect2: 0},
	{EnemyBlade3: 0},
	{"8Direction": 0},
	{BoosterItem: 0},
	{ItemEffect: 0},
	{RocketDash: 0},
	{RocketEffect4: 0},
	{RocketEffect7: 0},
	{RocketEffect5: 0},
	{RocketEffect8: 0},
	{RocketEffect3: 0},
	{RocketEffect6: 0},
	{RocketEffect2: 0},
	{RocketEffect1: 0},
	{GameScoreFont: 0},
	{ShieldEffect: 0},
	{Bullet2: 0},
	{Coin2: 0},
	{Function: 0},
	{Collitionbox3: 0},
	{ShopTittle: 0},
	{ShopSlings: 0},
	{ShopWalls: 0},
	{ShopUiButtons: 0},
	{ShopBackground: 0},
	{ShopPins: 0},
	{SkinBTN1: 0},
	{SkinBTN2: 0},
	{SkinBTN3: 0},
	{SkinBTN4: 0},
	{SkinBTN5: 0},
	{SkinBTN6: 0},
	{SkinBTN7: 0},
	{SkinBTN8: 0},
	{Price1: 0},
	{Price2: 0},
	{Price3: 0},
	{Price4: 0},
	{Price5: 0},
	{Price6: 0},
	{Price7: 0},
	{EndCoinFont2: 0},
	{PlayButton: 0},
	{MoreGamesShop: 0},
	{CompanyLogo: 0},
	{EnemyBox: 0},
	{CoinParticles2: 0},
	{AimArrow: 0},
	{TouchToPlayBTN: 0},
	{LocalStorage: 0},
	{Family3: 0},
	{Family4: 0},
	{Sound: 0},
	{TouchAvalaible: 0},
	{BouceSound: 0},
	{Rewards: 0},
	{Gameover: 0},
	{HighScore: 0},
	{Score: 0},
	{Diamonds: 0},
	{Firstvida: 0},
	{Pinntype: 0},
	{Shield: 0},
	{Boost: 0},
	{Triggerpin: 0},
	{Piny: 0},
	{Pinx: 0},
	{Redpin: 0},
	{Coins: 0},
	{Touching: 0},
	{IsAiming: 0},
	{Magnet: 0},
	{IsScreenRotate: 0},
	{SkinSelect: 0},
	{Upgrade8: 0},
	{Upgrade7: 0},
	{Upgrade6: 0},
	{Upgrade5: 0},
	{Upgrade4: 0},
	{Upgrade3: 0},
	{Upgrade2: 0}
];

self.InstanceType = {
	GameTittle: class extends self.ISpriteInstance {},
	ShopCoinUI: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {},
	Audio: class extends self.IInstance {},
	FadeScreen: class extends self.ISpriteInstance {},
	Browser: class extends self.IInstance {},
	SoundUI: class extends self.ISpriteInstance {},
	Keyboard: class extends self.IInstance {},
	TntEffect: class extends self.ISpriteInstance {},
	RotateScreen: class extends self.ISpriteInstance {},
	PinnerPick1: class extends self.ISpriteInstance {},
	GamePlayer: class extends self.ISpriteInstance {},
	Arms1: class extends self.ISpriteInstance {},
	Arms2: class extends self.ISpriteInstance {},
	Limiter: class extends self.ISpriteInstance {},
	PlayerSkin1: class extends self.ISpriteInstance {},
	SideWall2: class extends self.ISpriteInstance {},
	PlayerSkin2: class extends self.ISpriteInstance {},
	GameCamera: class extends self.ISpriteInstance {},
	GameBackground: class extends self.ITiledBackgroundInstance {},
	ShopButton: class extends self.ISpriteInstance {},
	RewardsButton: class extends self.ISpriteInstance {},
	Tutorial: class extends self.ISpriteInstance {},
	CoinUI: class extends self.ISpriteInstance {},
	CoinFontGame: class extends self.ISpriteFontInstance {},
	SideWallBackground: class extends self.ITiledBackgroundInstance {},
	SideWallBackground2: class extends self.ITiledBackgroundInstance {},
	MainPillar: class extends self.ISpriteInstance {},
	Grass3: class extends self.ISpriteInstance {},
	Grass1: class extends self.ISpriteInstance {},
	LightEffect: class extends self.ISpriteInstance {},
	Grass2: class extends self.ISpriteInstance {},
	WaterBackground: class extends self.ISpriteInstance {},
	BlockParticles1: class extends self.IParticlesInstance {},
	BlockParticles2: class extends self.IParticlesInstance {},
	SideWall1: class extends self.ISpriteInstance {},
	PlayerParticles: class extends self.IParticlesInstance {},
	PillarObstacle: class extends self.ISpriteInstance {},
	PinnerPick2: class extends self.ISpriteInstance {},
	PinnerPick3: class extends self.ISpriteInstance {},
	SlingsBackground: class extends self.ISpriteInstance {},
	EnemyBlade1: class extends self.ISpriteInstance {},
	Coin1: class extends self.ISpriteInstance {},
	WallBrick: class extends self.ISpriteInstance {},
	WallEnemy1: class extends self.ISpriteInstance {},
	WallEnemy2: class extends self.ISpriteInstance {},
	PinnerPickRed: class extends self.ISpriteInstance {},
	SideWallCone: class extends self.ISpriteInstance {},
	HalfWallSpin: class extends self.ISpriteInstance {},
	BubbleParticles: class extends self.IParticlesInstance {},
	GameoverButtons: class extends self.ISpriteInstance {},
	MoreGameButton: class extends self.IButtonInstance {},
	RestartButton: class extends self.IButtonInstance {},
	FadeGameover: class extends self.ISpriteInstance {},
	GameoverScreen: class extends self.ISpriteInstance {},
	BestScoreFont: class extends self.ISpriteFontInstance {},
	GameOverScoreFont: class extends self.ISpriteFontInstance {},
	EndCoinFont: class extends self.ISpriteFontInstance {},
	JumpEffect: class extends self.ISpriteInstance {},
	Collitionbox1: class extends self.ISpriteInstance {},
	Collitionbox2: class extends self.ISpriteInstance {},
	BloodParticles: class extends self.IParticlesInstance {},
	SmokeEffect: class extends self.ISpriteInstance {},
	CoinParticles: class extends self.IParticlesInstance {},
	EnemyBlade2: class extends self.ISpriteInstance {},
	DiamondItem: class extends self.ISpriteInstance {},
	DiamondParticles: class extends self.IParticlesInstance {},
	Pinballs1: class extends self.ISpriteInstance {},
	WheelFire1: class extends self.ISpriteInstance {},
	FireEffect1: class extends self.ISpriteInstance {},
	PinnerPick5: class extends self.ISpriteInstance {},
	Pinballs2: class extends self.ISpriteInstance {},
	WheelFire2: class extends self.ISpriteInstance {},
	PinnerPick6: class extends self.ISpriteInstance {},
	CannonBow: class extends self.ISpriteInstance {},
	EnemyArrow: class extends self.ISpriteInstance {},
	ArrowStick: class extends self.ISpriteInstance {},
	CannonBow2: class extends self.ISpriteInstance {},
	FireEffect2: class extends self.ISpriteInstance {},
	EnemyBlade3: class extends self.ISpriteInstance {},
	BoosterItem: class extends self.ISpriteInstance {},
	ItemEffect: class extends self.ISpriteInstance {},
	RocketDash: class extends self.ISpriteInstance {},
	RocketEffect4: class extends self.IParticlesInstance {},
	RocketEffect7: class extends self.IParticlesInstance {},
	RocketEffect5: class extends self.IParticlesInstance {},
	RocketEffect8: class extends self.IParticlesInstance {},
	RocketEffect3: class extends self.IParticlesInstance {},
	RocketEffect6: class extends self.IParticlesInstance {},
	RocketEffect2: class extends self.IParticlesInstance {},
	RocketEffect1: class extends self.IParticlesInstance {},
	GameScoreFont: class extends self.ISpriteFontInstance {},
	ShieldEffect: class extends self.ISpriteInstance {},
	Coin2: class extends self.ISpriteInstance {},
	Function: class extends self.IInstance {},
	Collitionbox3: class extends self.ISpriteInstance {},
	ShopTittle: class extends self.ISpriteInstance {},
	ShopSlings: class extends self.ISpriteInstance {},
	ShopWalls: class extends self.ISpriteInstance {},
	ShopUiButtons: class extends self.ISpriteInstance {},
	ShopBackground: class extends self.ISpriteInstance {},
	ShopPins: class extends self.ISpriteInstance {},
	SkinBTN1: class extends self.ISpriteInstance {},
	SkinBTN2: class extends self.ISpriteInstance {},
	SkinBTN3: class extends self.ISpriteInstance {},
	SkinBTN4: class extends self.ISpriteInstance {},
	SkinBTN5: class extends self.ISpriteInstance {},
	SkinBTN6: class extends self.ISpriteInstance {},
	SkinBTN7: class extends self.ISpriteInstance {},
	SkinBTN8: class extends self.ISpriteInstance {},
	Price1: class extends self.ISpriteInstance {},
	Price2: class extends self.ISpriteInstance {},
	Price3: class extends self.ISpriteInstance {},
	Price4: class extends self.ISpriteInstance {},
	Price5: class extends self.ISpriteInstance {},
	Price6: class extends self.ISpriteInstance {},
	Price7: class extends self.ISpriteInstance {},
	EndCoinFont2: class extends self.ISpriteFontInstance {},
	PlayButton: class extends self.ISpriteInstance {},
	MoreGamesShop: class extends self.ISpriteInstance {},
	CompanyLogo: class extends self.ISpriteInstance {},
	EnemyBox: class extends self.ISpriteInstance {},
	CoinParticles2: class extends self.IParticlesInstance {},
	AimArrow: class extends self.ISpriteInstance {},
	TouchToPlayBTN: class extends self.ISpriteInstance {},
	LocalStorage: class extends self.IInstance {},
	Family3: class extends self.ISpriteInstance {},
	Family4: class extends self.ISpriteInstance {}
}