const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.solid,
		C3.Behaviors.Bullet,
		C3.Plugins.Touch,
		C3.Plugins.Spritefont2,
		C3.Plugins.Arr,
		C3.Plugins.Browser,
		C3.Plugins.Audio,
		C3.Plugins.LocalStorage,
		C3.Plugins.Text,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.System.Exps.layoutname,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Exps.random,
		C3.Plugins.System.Acts.SetLayerBackground,
		C3.Plugins.System.Exps.rgb,
		C3.Plugins.Touch.Cnds.OnTouchStart,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Behaviors.Bullet.Acts.SetAngleOfMotion,
		C3.Plugins.System.Exps.int,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Behaviors.Bullet.Acts.SetEnabled,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Acts.GetItem,
		C3.Plugins.LocalStorage.Cnds.OnItemMissing,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.LocalStorage.Cnds.OnItemGet,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.LocalStorage.Cnds.CompareValue,
		C3.Behaviors.Bullet.Cnds.CompareTravelled,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.Sprite.Exps.Opacity,
		C3.Plugins.System.Exps.dt,
		C3.Plugins.Sprite.Cnds.CompareOpacity,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Exps.wallclocktime,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Spritefont2.Acts.SetText,
		C3.Behaviors.Bullet.Acts.SetSpeed,
		C3.Behaviors.Bullet.Exps.Speed,
		C3.Plugins.Spritefont2.Cnds.OnCreated,
		C3.Plugins.Arr.Acts.JSONLoad,
		C3.Plugins.Spritefont2.Acts.SetCharacterWidth,
		C3.Plugins.System.Cnds.For,
		C3.Plugins.Arr.Exps.Height,
		C3.Plugins.Arr.Exps.At,
		C3.Plugins.System.Exps.loopindex,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.Browser.Acts.GoToURLWindow,
		C3.Plugins.Sprite.Cnds.CompareY,
		C3.Plugins.System.Cnds.PickByComparison,
		C3.Plugins.Spritefont2.Exps.UID
	];
};
self.C3_JsPropNameTable = [
	{Solid: 0},
	{walls: 0},
	{Bullet: 0},
	{ball: 0},
	{floors: 0},
	{Touch: 0},
	{balltrail: 0},
	{sfNames: 0},
	{SpriteFontImporter: 0},
	{shadow: 0},
	{mineblocks: 0},
	{title: 0},
	{gameover: 0},
	{scoreBest: 0},
	{retry: 0},
	{likes: 0},
	{twitter: 0},
	{facebook: 0},
	{Browser: 0},
	{Audio: 0},
	{LocalStorage: 0},
	{debug: 0},
	{maxpoints: 0},
	{points: 0},
	{clicktime: 0},
	{start: 0},
	{disparitionSpeed: 0},
	{R: 0},
	{G: 0},
	{B: 0}
];

self.InstanceType = {
	walls: class extends self.ISpriteInstance {},
	ball: class extends self.ISpriteInstance {},
	floors: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {},
	balltrail: class extends self.ISpriteInstance {},
	sfNames: class extends self.ISpriteFontInstance {},
	SpriteFontImporter: class extends self.IArrayInstance {},
	shadow: class extends self.ISpriteInstance {},
	mineblocks: class extends self.ISpriteInstance {},
	title: class extends self.ISpriteInstance {},
	gameover: class extends self.ISpriteInstance {},
	scoreBest: class extends self.ISpriteInstance {},
	retry: class extends self.ISpriteInstance {},
	likes: class extends self.ISpriteInstance {},
	twitter: class extends self.ISpriteInstance {},
	facebook: class extends self.ISpriteInstance {},
	Browser: class extends self.IInstance {},
	Audio: class extends self.IInstance {},
	LocalStorage: class extends self.IInstance {},
	debug: class extends self.ITextInstance {}
}