const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Plugins.TiledBg,
		C3.Behaviors.Platform,
		C3.Behaviors.Sin,
		C3.Behaviors.bound,
		C3.Plugins.Audio,
		C3.Plugins.Browser,
		C3.Plugins.Keyboard,
		C3.Plugins.Mouse,
		C3.Plugins.Touch,
		C3.Plugins.LocalStorage,
		C3.Plugins.Spritefont2,
		C3.Behaviors.Fade,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Sprite.Exps.Height,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.System.Exps.viewportleft,
		C3.Plugins.System.Exps.viewportright,
		C3.Plugins.System.Exps.viewporttop,
		C3.Plugins.System.Exps.viewportbottom,
		C3.Behaviors.Platform.Acts.SetGravity,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Spritefont2.Acts.SetPos,
		C3.Plugins.Spritefont2.Exps.LayerName,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Sprite.Exps.LayerName,
		C3.Plugins.Touch.Cnds.OnTouchStart,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Audio.Acts.Play,
		C3.Behaviors.Sin.Acts.SetEnabled,
		C3.Behaviors.Fade.Acts.StartFade,
		C3.Plugins.Sprite.Cnds.OnDestroyed,
		C3.Behaviors.Platform.Acts.SetVectorY,
		C3.Plugins.Spritefont2.Acts.SetText,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.TiledBg.Acts.SetX,
		C3.Plugins.TiledBg.Exps.X,
		C3.Plugins.Spritefont2.Exps.X,
		C3.Plugins.Spritefont2.Exps.Y,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.System.Exps.choose,
		C3.Plugins.System.Exps.originalwindowwidth,
		C3.Plugins.System.Exps.originalwindowheight,
		C3.Plugins.TiledBg.Exps.Height,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Sprite.Exps.AnimationFrameCount,
		C3.Plugins.TiledBg.Cnds.CompareX,
		C3.Plugins.TiledBg.Exps.Width,
		C3.Plugins.Sprite.Cnds.CompareX,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Sprite.Exps.AnimationFrame,
		C3.Behaviors.Platform.Acts.SetEnabled,
		C3.Plugins.Spritefont2.Acts.Destroy,
		C3.Plugins.Sprite.Acts.MoveToBottom,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.System.Exps.projectname,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Acts.SetGroupActive,
		C3.Plugins.System.Acts.WaitForSignal,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Audio.Acts.Preload,
		C3.Plugins.Spritefont2.Exps.Height,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.System.Exps.loadingprogress,
		C3.Plugins.Spritefont2.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.System.Cnds.OnLoadFinished,
		C3.Plugins.Spritefont2.Acts.SetBoolInstanceVar,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.Sprite.Acts.StartAnim,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.LocalStorage.Cnds.OnItemMissing,
		C3.Plugins.LocalStorage.Cnds.IsProcessingGets,
		C3.Plugins.Audio.Acts.SetVolume,
		C3.Plugins.System.Cnds.Else,
		C3.JavaScriptInEvents.Global_event_Event28_Act6,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.System.Exps.layoutheight,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.System.Acts.SetLayerOpacity,
		C3.Plugins.System.Acts.SetLayerScale,
		C3.Plugins.System.Exps.layeropacity,
		C3.Plugins.System.Exps.layerscale,
		C3.Plugins.System.Exps.windowwidth,
		C3.Plugins.System.Cnds.LayerCmpOpacity,
		C3.Plugins.System.Acts.Signal,
		C3.JavaScriptInEvents.Menu_event_Event4_Act6,
		C3.JavaScriptInEvents.Menu_event_Event6_Act1,
		C3.Plugins.Browser.Acts.Close,
		C3.JavaScriptInEvents.Game_over_event_Event5_Act6
	];
};
self.C3_JsPropNameTable = [
	{Background: 0},
	{Foreground: 0},
	{Scored: 0},
	{stop: 0},
	{Pillar_Bottom: 0},
	{Pillar_Top: 0},
	{Platform: 0},
	{Sine: 0},
	{BoundToLayout: 0},
	{Player: 0},
	{Midground_1: 0},
	{Midground_2: 0},
	{Coin: 0},
	{Background_Objects: 0},
	{Fish_Menu: 0},
	{Audio: 0},
	{Browser: 0},
	{Keyboard: 0},
	{Mouse: 0},
	{Touch: 0},
	{LocalStorage: 0},
	{Top_Score_Font: 0},
	{Score_Font: 0},
	{Active: 0},
	{Loading_Font: 0},
	{Game_Score_Font: 0},
	{Fade: 0},
	{Coin_Font: 0},
	{Width_Size: 0},
	{Height_Size: 0},
	{Button_Exit: 0},
	{Button_Play: 0},
	{Button_Menu: 0},
	{Button_Music: 0},
	{Button_Pause: 0},
	{Button_Restart: 0},
	{Button_Sound: 0},
	{Button_Start: 0},
	{Button_Back: 0},
	{Game_Icon: 0},
	{Game_Logo: 0},
	{Black_Screen: 0},
	{Window_Score: 0},
	{Text_Paused: 0},
	{Text_Tap_To_Play: 0},
	{Text_Game_Over: 0},
	{Text_You_Score: 0},
	{Buttons: 0},
	{Texts: 0},
	{Objects: 0},
	{Backgrounds: 0},
	{Game_Status: 0},
	{Game_Speed: 0},
	{Spawn_Object: 0},
	{Spawn_Time: 0},
	{Score: 0},
	{Coin_Frame: 0},
	{Coin_Size: 0},
	{Top_Score: 0},
	{Sound: 0},
	{Sound_Status: 0},
	{Music: 0},
	{Music_Status: 0},
	{Size_Difference: 0},
	{Current_Distance: 0},
	{DISTANCE_BETWEEN_OBJECTS: 0}
];

self.InstanceType = {
	Background: class extends self.ISpriteInstance {},
	Foreground: class extends self.ITiledBackgroundInstance {},
	Pillar_Bottom: class extends self.ISpriteInstance {},
	Pillar_Top: class extends self.ISpriteInstance {},
	Player: class extends self.ISpriteInstance {},
	Midground_1: class extends self.ITiledBackgroundInstance {},
	Midground_2: class extends self.ITiledBackgroundInstance {},
	Coin: class extends self.ISpriteInstance {},
	Background_Objects: class extends self.ISpriteInstance {},
	Fish_Menu: class extends self.ISpriteInstance {},
	Audio: class extends self.IInstance {},
	Browser: class extends self.IInstance {},
	Keyboard: class extends self.IInstance {},
	Mouse: class extends self.IInstance {},
	Touch: class extends self.IInstance {},
	LocalStorage: class extends self.IInstance {},
	Top_Score_Font: class extends self.ISpriteFontInstance {},
	Score_Font: class extends self.ISpriteFontInstance {},
	Loading_Font: class extends self.ISpriteFontInstance {},
	Game_Score_Font: class extends self.ISpriteFontInstance {},
	Coin_Font: class extends self.ISpriteFontInstance {},
	Button_Exit: class extends self.ISpriteInstance {},
	Button_Play: class extends self.ISpriteInstance {},
	Button_Menu: class extends self.ISpriteInstance {},
	Button_Music: class extends self.ISpriteInstance {},
	Button_Pause: class extends self.ISpriteInstance {},
	Button_Restart: class extends self.ISpriteInstance {},
	Button_Sound: class extends self.ISpriteInstance {},
	Button_Start: class extends self.ISpriteInstance {},
	Button_Back: class extends self.ISpriteInstance {},
	Game_Icon: class extends self.ISpriteInstance {},
	Game_Logo: class extends self.ISpriteInstance {},
	Black_Screen: class extends self.ISpriteInstance {},
	Window_Score: class extends self.ISpriteInstance {},
	Text_Paused: class extends self.ISpriteInstance {},
	Text_Tap_To_Play: class extends self.ISpriteInstance {},
	Text_Game_Over: class extends self.ISpriteInstance {},
	Text_You_Score: class extends self.ISpriteInstance {},
	Buttons: class extends self.ISpriteInstance {},
	Texts: class extends self.ISpriteInstance {},
	Objects: class extends self.ISpriteInstance {},
	Backgrounds: class extends self.ITiledBackgroundInstance {}
}