const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.scrollto,
		C3.Behaviors.Sin,
		C3.Behaviors.Fade,
		C3.Behaviors.Platform,
		C3.Plugins.Touch,
		C3.Plugins.Browser,
		C3.Plugins.Audio,
		C3.Behaviors.Rotate,
		C3.Behaviors.Bullet,
		C3.Plugins.Mouse,
		C3.Behaviors.Anchor,
		C3.Plugins.Spritefont2,
		C3.Plugins.XML,
		C3.Plugins.AJAX,
		C3.Plugins.LocalStorage,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Sprite.Acts.SetAnimSpeed,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Behaviors.Sin.Acts.SetEnabled,
		C3.JavaScriptInEvents.Events_game_Event4_Act3,
		C3.Plugins.Sprite.Cnds.CompareY,
		C3.Plugins.Sprite.Exps.Y,
		C3.Behaviors.Platform.Acts.SetGravity,
		C3.Behaviors.Platform.Acts.SetMaxFallSpeed,
		C3.Plugins.Touch.Cnds.OnTouchStart,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Cnds.Else,
		C3.Behaviors.Platform.Acts.SetEnabled,
		C3.Behaviors.Platform.Acts.SimulateControl,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Behaviors.Bullet.Acts.SetEnabled,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Behaviors.scrollto.Acts.Shake,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Sprite.Acts.RotateCounterclockwise,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Plugins.Sprite.Acts.SetScale,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Acts.SetPosToObject,
		C3.Plugins.Sprite.Exps.Angle,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Behaviors.Bullet.Acts.SetAngleOfMotion,
		C3.Plugins.Sprite.Cnds.IsBetweenAngles,
		C3.Behaviors.Rotate.Acts.SetSpeed,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Spritefont2.Acts.SetText,
		C3.Plugins.Audio.Acts.StopAll,
		C3.Plugins.System.Acts.Wait,
		C3.Behaviors.Fade.Acts.StartFade,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Audio.Acts.SetSilent,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.Mouse.Exps.Y,
		C3.Plugins.Sprite.Cnds.CompareOpacity,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.Sprite.Exps.Opacity,
		C3.Plugins.Mouse.Cnds.IsOverObject,
		C3.Plugins.Mouse.Acts.SetCursor,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Acts.GetItem,
		C3.Plugins.LocalStorage.Cnds.OnItemMissing,
		C3.Plugins.LocalStorage.Cnds.OnItemGet,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.AJAX.Acts.Request,
		C3.Plugins.AJAX.Cnds.OnComplete,
		C3.Plugins.XML.Acts.Load,
		C3.Plugins.AJAX.Exps.LastData,
		C3.Plugins.XML.Exps.StringValue,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Browser.Acts.GoToURLWindow
	];
};
self.C3_JsPropNameTable = [
	{ScrollTo: 0},
	{cat_cam: 0},
	{wall_create_go: 0},
	{Sine: 0},
	{wall_create: 0},
	{point_cat: 0},
	{wall_right: 0},
	{Fade: 0},
	{cat_blow: 0},
	{wall_left: 0},
	{Platform: 0},
	{cat: 0},
	{Touch: 0},
	{Browser: 0},
	{Audio: 0},
	{cat_helice: 0},
	{wall: 0},
	{Rotate: 0},
	{wall_gear: 0},
	{Bullet: 0},
	{base: 0},
	{base_helice: 0},
	{bt_sound: 0},
	{bg_mountains: 0},
	{bg_cloud_01: 0},
	{bg_cloud_02: 0},
	{Mouse: 0},
	{Anchor: 0},
	{tutorial: 0},
	{info_txt_record: 0},
	{share_facebook: 0},
	{share_twitter: 0},
	{font_record: 0},
	{font_info: 0},
	{XML: 0},
	{AJAX: 0},
	{effect_up: 0},
	{effect_down: 0},
	{bg_limit: 0},
	{cat_smoke: 0},
	{LocalStorage: 0},
	{wall_all: 0},
	{flapcat: 0},
	{bg: 0},
	{music_now: 0},
	{music: 0},
	{detect_mouse: 0},
	{game: 0},
	{cat_life: 0},
	{cat_direction: 0},
	{game_record: 0},
	{game_points: 0},
	{effect: 0},
	{facebookShare: 0},
	{facebook_message: 0},
	{twitterShare: 0},
	{twitter_message: 0}
];

self.InstanceType = {
	cat_cam: class extends self.ISpriteInstance {},
	wall_create_go: class extends self.ISpriteInstance {},
	wall_create: class extends self.ISpriteInstance {},
	point_cat: class extends self.ISpriteInstance {},
	wall_right: class extends self.ISpriteInstance {},
	cat_blow: class extends self.ISpriteInstance {},
	wall_left: class extends self.ISpriteInstance {},
	cat: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {},
	Browser: class extends self.IInstance {},
	Audio: class extends self.IInstance {},
	cat_helice: class extends self.ISpriteInstance {},
	wall_gear: class extends self.ISpriteInstance {},
	base: class extends self.ISpriteInstance {},
	base_helice: class extends self.ISpriteInstance {},
	bt_sound: class extends self.ISpriteInstance {},
	bg_mountains: class extends self.ISpriteInstance {},
	bg_cloud_01: class extends self.ISpriteInstance {},
	bg_cloud_02: class extends self.ISpriteInstance {},
	Mouse: class extends self.IInstance {},
	tutorial: class extends self.ISpriteInstance {},
	info_txt_record: class extends self.ISpriteInstance {},
	share_facebook: class extends self.ISpriteInstance {},
	share_twitter: class extends self.ISpriteInstance {},
	font_record: class extends self.ISpriteFontInstance {},
	font_info: class extends self.ISpriteFontInstance {},
	XML: class extends self.IInstance {},
	AJAX: class extends self.IInstance {},
	effect_up: class extends self.ISpriteInstance {},
	effect_down: class extends self.ISpriteInstance {},
	bg_limit: class extends self.ISpriteInstance {},
	cat_smoke: class extends self.ISpriteInstance {},
	LocalStorage: class extends self.IInstance {},
	wall_all: class extends self.ISpriteInstance {},
	flapcat: class extends self.ISpriteInstance {},
	wall: class extends self.ISpriteInstance {},
	bg: class extends self.ISpriteInstance {}
}