const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Plugins.Arr,
		C3.Plugins.Audio,
		C3.Plugins.Browser,
		C3.Plugins.Function,
		C3.Plugins.LocalStorage,
		C3.Plugins.Mouse,
		C3.Plugins.Touch,
		C3.Behaviors.Fade,
		C3.Behaviors.Rotate,
		C3.Behaviors.Sin,
		C3.Behaviors.Bullet,
		C3.Behaviors.wrap,
		C3.Behaviors.Physics,
		C3.Plugins.NinePatch,
		C3.Plugins.Spritefont2,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Acts.SetGroupActive,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Spritefont2.Acts.SetText,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.System.Exps.projectname,
		C3.JavaScriptInEvents.Game_events_Event1_Act12,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.Function.Cnds.OnFunction,
		C3.Plugins.Arr.Cnds.ArrForEach,
		C3.Plugins.Arr.Cnds.CompareCurrent,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Arr.Exps.CurY,
		C3.Plugins.Sprite.Acts.SetCollisions,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.Arr.Exps.CurX,
		C3.Plugins.Arr.Acts.SetXYZ,
		C3.Plugins.System.Exps.int,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Sprite.Exps.UID,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Arr.Exps.At,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.Function.Acts.CallFunction,
		C3.Plugins.System.Cnds.For,
		C3.Plugins.Function.Exps.Param,
		C3.Plugins.System.Exps.loopindex,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Acts.MoveAtAngle,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.System.Acts.AddVar,
		C3.Behaviors.Fade.Acts.StartFade,
		C3.Plugins.System.Exps.layoutheight,
		C3.Plugins.Sprite.Acts.MoveToBottom,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Behaviors.Physics.Acts.ApplyForceAtAngle,
		C3.Plugins.Arr.Cnds.Contains,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.Sprite.Cnds.PickByUID,
		C3.Plugins.Arr.Acts.Clear,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Exps.layoutwidth,
		C3.Plugins.Arr.Acts.SetSize,
		C3.Plugins.NinePatch.Acts.SetPos,
		C3.Plugins.NinePatch.Acts.SetSize,
		C3.Plugins.System.Exps.dt,
		C3.Plugins.Sprite.Cnds.CompareY,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.Arr.Acts.SetXY,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.System.Cnds.CompareBetween,
		C3.Plugins.Touch.Cnds.OnTouchEnd,
		C3.Plugins.Arr.Cnds.CompareXY,
		C3.Plugins.Sprite.Cnds.CompareX,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.Sprite.Acts.SetWidth,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.JavaScriptInEvents.Game_events_Event72_Act4,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Mouse.Cnds.IsButtonDown,
		C3.Plugins.Mouse.Acts.SetCursorSprite,
		C3.JavaScriptInEvents.Global_events_Event4_Act3,
		C3.Plugins.Audio.Cnds.IsTagPlaying,
		C3.JavaScriptInEvents.Main_events_Event2_Act3,
		C3.JavaScriptInEvents.Main_events_Event3_Act2,
		C3.Plugins.Browser.Acts.Close
	];
};
self.C3_JsPropNameTable = [
	{ButtonExit: 0},
	{ButtonPlay: 0},
	{return: 0},
	{Array: 0},
	{Audio: 0},
	{Browser: 0},
	{Function: 0},
	{LocalStorage: 0},
	{Mouse: 0},
	{SwapData: 0},
	{Touch: 0},
	{Background: 0},
	{Matched: 0},
	{Moving: 0},
	{trigger: 0},
	{targetY: 0},
	{row: 0},
	{col: 0},
	{dy: 0},
	{color: 0},
	{State: 0},
	{Fade: 0},
	{Block: 0},
	{Rotate: 0},
	{Sine: 0},
	{Block_1: 0},
	{Bullet: 0},
	{Wrap: 0},
	{Block_2: 0},
	{Block_3: 0},
	{Block_4: 0},
	{Block_5: 0},
	{Selection: 0},
	{Selection2: 0},
	{Selector: 0},
	{Selector2: 0},
	{HotJewels: 0},
	{Marker: 0},
	{Physics: 0},
	{Splinter_1: 0},
	{Splinter_2: 0},
	{Splinter_3: 0},
	{Splinter_4: 0},
	{Box: 0},
	{Box2: 0},
	{Clock: 0},
	{Coins: 0},
	{Cursor: 0},
	{CursorHover: 0},
	{Sprite: 0},
	{Sprite3: 0},
	{TimerBar: 0},
	{TimerBarBackground: 0},
	{AllScoreFont: 0},
	{LastScoreFont: 0},
	{MovesFont: 0},
	{ScoreFont: 0},
	{TimerFont: 0},
	{AllScore: 0},
	{OutTimer: 0},
	{Score2: 0},
	{Moves: 0},
	{ScoreBar: 0},
	{LastScore: 0},
	{Minutes: 0},
	{Seconds: 0},
	{Tile: 0},
	{MovingBlocks: 0},
	{Matches: 0},
	{CX: 0},
	{CY: 0},
	{Trigger: 0},
	{FirstPiece: 0},
	{UserId: 0},
	{Score: 0},
	{Sound: 0}
];

self.InstanceType = {
	ButtonExit: class extends self.ISpriteInstance {},
	ButtonPlay: class extends self.ISpriteInstance {},
	return: class extends self.ISpriteInstance {},
	Array: class extends self.IArrayInstance {},
	Audio: class extends self.IInstance {},
	Browser: class extends self.IInstance {},
	Function: class extends self.IInstance {},
	LocalStorage: class extends self.IInstance {},
	Mouse: class extends self.IInstance {},
	SwapData: class extends self.IArrayInstance {},
	Touch: class extends self.IInstance {},
	Background: class extends self.ISpriteInstance {},
	Block: class extends self.ISpriteInstance {},
	Block_1: class extends self.ISpriteInstance {},
	Block_2: class extends self.ISpriteInstance {},
	Block_3: class extends self.ISpriteInstance {},
	Block_4: class extends self.ISpriteInstance {},
	Block_5: class extends self.ISpriteInstance {},
	Selection: class extends self.ISpriteInstance {},
	Selection2: class extends self.ISpriteInstance {},
	Selector: class extends self.ISpriteInstance {},
	Selector2: class extends self.ISpriteInstance {},
	HotJewels: class extends self.ISpriteInstance {},
	Marker: class extends self.ISpriteInstance {},
	Splinter_1: class extends self.ISpriteInstance {},
	Splinter_2: class extends self.ISpriteInstance {},
	Splinter_3: class extends self.ISpriteInstance {},
	Splinter_4: class extends self.ISpriteInstance {},
	Box: class extends self.I9PatchInstance {},
	Box2: class extends self.I9PatchInstance {},
	Clock: class extends self.ISpriteInstance {},
	Coins: class extends self.ISpriteInstance {},
	Cursor: class extends self.ISpriteInstance {},
	CursorHover: class extends self.ISpriteInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	TimerBar: class extends self.ISpriteInstance {},
	TimerBarBackground: class extends self.ISpriteInstance {},
	AllScoreFont: class extends self.ISpriteFontInstance {},
	LastScoreFont: class extends self.ISpriteFontInstance {},
	MovesFont: class extends self.ISpriteFontInstance {},
	ScoreFont: class extends self.ISpriteFontInstance {},
	TimerFont: class extends self.ISpriteFontInstance {}
}