const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Arr,
		C3.Plugins.Audio,
		C3.Plugins.Browser,
		C3.Plugins.Function,
		C3.Plugins.LocalStorage,
		C3.Plugins.Touch,
		C3.Plugins.Sprite,
		C3.Behaviors.Sin,
		C3.Plugins.Spritefont2,
		C3.Behaviors.custom,
		C3.Plugins.TiledBg,
		C3.Behaviors.Fade,
		C3.Behaviors.Rotate,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Sprite.Acts.SetHeight,
		C3.Plugins.System.Exps.viewportbottom,
		C3.Plugins.Sprite.Acts.SetWidth,
		C3.Plugins.System.Exps.viewportright,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Exps.Height,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Spritefont2.Acts.SetPos,
		C3.JavaScriptInEvents.Game_events_Event1_Act20,
		C3.Plugins.Arr.Cnds.ArrForEach,
		C3.Plugins.Arr.Acts.SetXY,
		C3.Plugins.Arr.Exps.CurX,
		C3.Plugins.Arr.Exps.CurY,
		C3.Plugins.System.Cnds.For,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.System.Exps.loopindex,
		C3.Plugins.Arr.Acts.JSONLoad,
		C3.Plugins.Function.Acts.CallFunction,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.Touch.Cnds.OnTouchEnd,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Behaviors.custom.Acts.AccelerateAngle,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Touch.Exps.X,
		C3.Plugins.Touch.Exps.Y,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Behaviors.custom.Acts.Reverse,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.Plugins.Sprite.Exps.AnimationFrame,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Function.Cnds.OnFunction,
		C3.Plugins.Arr.Exps.Height,
		C3.Plugins.Arr.Exps.At,
		C3.Plugins.Arr.Cnds.CompareXY,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.Arr.Acts.Push,
		C3.Plugins.Arr.Acts.Delete,
		C3.Plugins.Function.Exps.Param,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Spritefont2.Acts.SetText,
		C3.Plugins.Sprite.Cnds.OnAnimFinished,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.JavaScriptInEvents.Game_events_Event114_Act1,
		C3.Plugins.System.Acts.RestartLayout,
		C3.JavaScriptInEvents.Game_events_Event118_Act1,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.System.Acts.SetGroupActive,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Spritefont2.Acts.SetVisible,
		C3.Plugins.Spritefont2.Acts.SetScale,
		C3.Plugins.Spritefont2.Acts.SetCharacterSpacing,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Acts.GetItem,
		C3.Plugins.LocalStorage.Cnds.OnItemGet,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.System.Acts.GoToLayout,
		C3.JavaScriptInEvents.Game_events_Event128_Act2,
		C3.Plugins.Sprite.Cnds.CompareY,
		C3.Behaviors.custom.Acts.Stop,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Audio.Acts.SetVolume,
		C3.Plugins.LocalStorage.Cnds.CompareValue,
		C3.Plugins.Audio.Acts.SetSilent,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.LocalStorage.Cnds.OnItemMissing,
		C3.JavaScriptInEvents.Main_events_Event7_Act2,
		C3.Plugins.System.Exps.loadingprogress,
		C3.Plugins.System.Cnds.OnLoadFinished,
		C3.Plugins.Audio.Acts.Preload,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.Sprite.Acts.SetY,
		C3.JavaScriptInEvents.Global_events_Event22_Act1,
		C3.Plugins.Browser.Acts.Close
	];
};
self.C3_JsPropNameTable = [
	{Array: 0},
	{Audio: 0},
	{Browser: 0},
	{ConnectDeleter: 0},
	{CurrentGame: 0},
	{Dist: 0},
	{Function: 0},
	{Groups: 0},
	{LocalStorage: 0},
	{Touch: 0},
	{BtnBack: 0},
	{Sine: 0},
	{BtnStart: 0},
	{BtnRestart: 0},
	{Sound: 0},
	{BtnSound: 0},
	{BtnExit: 0},
	{Borders: 0},
	{CurX: 0},
	{CurY: 0},
	{Tiles: 0},
	{TopBorder: 0},
	{Black: 0},
	{BallsFont: 0},
	{CustomMovement: 0},
	{HighScoreFont: 0},
	{LevelsFont: 0},
	{LoadingFont: 0},
	{ScoreFont: 0},
	{TimeFont: 0},
	{Backgrounds: 0},
	{used: 0},
	{Ball: 0},
	{group: 0},
	{BallCollision: 0},
	{Frame: 0},
	{Frames: 0},
	{GameLogo: 0},
	{Line: 0},
	{Sine2: 0},
	{Smoke: 0},
	{Fade: 0},
	{Bubble: 0},
	{Rotate: 0},
	{Star: 0},
	{GameIcon: 0},
	{SunRain: 0},
	{FrameTop: 0},
	{BackLine: 0},
	{FrameBack: 0},
	{Minutes: 0},
	{Seconds: 0},
	{Shots: 0},
	{AdShow: 0},
	{ScoreBonus: 0},
	{HighScore: 0},
	{Clear: 0},
	{IsGameOver: 0},
	{Score: 0},
	{MoveEnded: 0},
	{DestrGroup: 0},
	{LineAdded: 0},
	{ShootCounter: 0},
	{TileY: 0},
	{TileX: 0},
	{InShoot: 0},
	{StarSize: 0},
	{BubbleSize: 0},
	{BubblePosition: 0},
	{UserId: 0}
];

self.InstanceType = {
	Array: class extends self.IArrayInstance {},
	Audio: class extends self.IInstance {},
	Browser: class extends self.IInstance {},
	ConnectDeleter: class extends self.IArrayInstance {},
	CurrentGame: class extends self.IArrayInstance {},
	Dist: class extends self.IArrayInstance {},
	Function: class extends self.IInstance {},
	Groups: class extends self.IArrayInstance {},
	LocalStorage: class extends self.IInstance {},
	Touch: class extends self.IInstance {},
	BtnBack: class extends self.ISpriteInstance {},
	BtnStart: class extends self.ISpriteInstance {},
	BtnRestart: class extends self.ISpriteInstance {},
	BtnSound: class extends self.ISpriteInstance {},
	BtnExit: class extends self.ISpriteInstance {},
	Borders: class extends self.ISpriteInstance {},
	Tiles: class extends self.ISpriteInstance {},
	TopBorder: class extends self.ISpriteInstance {},
	Black: class extends self.ISpriteInstance {},
	BallsFont: class extends self.ISpriteFontInstance {},
	HighScoreFont: class extends self.ISpriteFontInstance {},
	LevelsFont: class extends self.ISpriteFontInstance {},
	LoadingFont: class extends self.ISpriteFontInstance {},
	ScoreFont: class extends self.ISpriteFontInstance {},
	TimeFont: class extends self.ISpriteFontInstance {},
	Backgrounds: class extends self.ISpriteInstance {},
	Ball: class extends self.ISpriteInstance {},
	BallCollision: class extends self.ISpriteInstance {},
	Frame: class extends self.ISpriteInstance {},
	Frames: class extends self.ISpriteInstance {},
	GameLogo: class extends self.ISpriteInstance {},
	Line: class extends self.ITiledBackgroundInstance {},
	Smoke: class extends self.ISpriteInstance {},
	Bubble: class extends self.ISpriteInstance {},
	Star: class extends self.ISpriteInstance {},
	GameIcon: class extends self.ISpriteInstance {},
	SunRain: class extends self.ISpriteInstance {},
	FrameTop: class extends self.ISpriteInstance {},
	BackLine: class extends self.ISpriteInstance {},
	FrameBack: class extends self.ISpriteInstance {}
}