const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Bullet,
		C3.Plugins.Particles,
		C3.Behaviors.Pin,
		C3.Plugins.Touch,
		C3.Plugins.TiledBg,
		C3.Plugins.Spritefont2,
		C3.Behaviors.Sin,
		C3.Plugins.Browser,
		C3.Plugins.Audio,
		C3.Plugins.LocalStorage,
		C3.Plugins.advert,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.Audio.Cnds.IsTagPlaying,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Touch.Cnds.IsInTouch,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.System.Acts.GoToLayout,
		C3.JavaScriptInEvents.Start_Event4_Act2,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Acts.GetItem,
		C3.Plugins.LocalStorage.Cnds.OnItemGet,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Behaviors.Pin.Acts.Pin,
		C3.Plugins.Spritefont2.Acts.SetText,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Exps.random,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.Touch.Cnds.OnTouchStart,
		C3.Plugins.Sprite.Cnds.IsOnScreen,
		C3.Behaviors.Bullet.Cnds.CompareSpeed,
		C3.Behaviors.Bullet.Acts.SetSpeed,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Behaviors.Bullet.Acts.SetAngleOfMotion,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Cnds.CompareY,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Sprite.Cnds.OnDestroyed,
		C3.Plugins.Audio.Acts.Stop,
		C3.Behaviors.Bullet.Acts.SetEnabled,
		C3.Plugins.Particles.Acts.Destroy,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Spritefont2.Acts.SetVisible,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.System.Acts.AddVar,
		C3.JavaScriptInEvents.Game_Event22_Act1,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.LocalStorage.Acts.ClearStorage,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.System.Exps.viewportright,
		C3.Plugins.System.Exps.viewporttop,
		C3.Plugins.advert.Acts.ShowInterstitial,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.Sprite.Cnds.IsVisible,
		C3.Plugins.Browser.Acts.GoToURLWindow,
		C3.Plugins.System.Acts.RestartLayout,
		C3.JavaScriptInEvents.Admob_Event11_Act2,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Audio.Acts.SetMuted
	];
};
self.C3_JsPropNameTable = [
	{Bullet: 0},
	{ball: 0},
	{Pin: 0},
	{Particles: 0},
	{Touch: 0},
	{TiledBackground: 0},
	{rate: 0},
	{Moregames: 0},
	{Fb: 0},
	{pass: 0},
	{BAR1: 0},
	{BAR2: 0},
	{Particles2: 0},
	{Fichier: 0},
	{SCORE: 0},
	{Sine: 0},
	{Fichier4: 0},
	{HighScore: 0},
	{Fichier2: 0},
	{Fichier3: 0},
	{Replay: 0},
	{Browser: 0},
	{Audio: 0},
	{LocalStorage: 0},
	{mute: 0},
	{Advert: 0},
	{GUI: 0},
	{MUSIC: 0},
	{score: 0},
	{HIGH_SCORE: 0},
	{X: 0},
	{inter: 0}
];

self.InstanceType = {
	ball: class extends self.ISpriteInstance {},
	Particles: class extends self.IParticlesInstance {},
	Touch: class extends self.IInstance {},
	TiledBackground: class extends self.ITiledBackgroundInstance {},
	rate: class extends self.ISpriteInstance {},
	Moregames: class extends self.ISpriteInstance {},
	Fb: class extends self.ISpriteInstance {},
	BAR1: class extends self.ISpriteInstance {},
	BAR2: class extends self.ISpriteInstance {},
	Particles2: class extends self.IParticlesInstance {},
	Fichier: class extends self.ISpriteInstance {},
	SCORE: class extends self.ISpriteFontInstance {},
	Fichier4: class extends self.ISpriteInstance {},
	HighScore: class extends self.ISpriteFontInstance {},
	Fichier2: class extends self.ISpriteInstance {},
	Fichier3: class extends self.ISpriteInstance {},
	Replay: class extends self.ISpriteInstance {},
	Browser: class extends self.IInstance {},
	Audio: class extends self.IInstance {},
	LocalStorage: class extends self.IInstance {},
	mute: class extends self.ISpriteInstance {},
	Advert: class extends self.IInstance {},
	GUI: class extends self.ISpriteInstance {}
}