const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.scrollto,
		C3.Behaviors.Sin,
		C3.Behaviors.Platform,
		C3.Behaviors.Fade,
		C3.Behaviors.Rotate,
		C3.Plugins.Touch,
		C3.Plugins.Mouse,
		C3.Plugins.Spritefont2,
		C3.Plugins.Audio,
		C3.Plugins.LocalStorage,
		C3.Plugins.XML,
		C3.Plugins.Browser,
		C3.Plugins.AJAX,
		C3.Behaviors.Anchor,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Audio.Cnds.IsTagPlaying,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Behaviors.Fade.Acts.StartFade,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Sprite.Cnds.IsOnScreen,
		C3.Plugins.Sprite.Acts.SetPosToObject,
		C3.Plugins.Mouse.Cnds.IsOverObject,
		C3.Plugins.Mouse.Acts.SetCursor,
		C3.Plugins.Touch.Cnds.IsInTouch,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Behaviors.Platform.Acts.SetVectorY,
		C3.Plugins.Touch.Cnds.OnTouchStart,
		C3.Plugins.Touch.Cnds.OnTouchEnd,
		C3.Behaviors.Platform.Acts.SetEnabled,
		C3.JavaScriptInEvents.Events_game_Event18_Act3,
		C3.Behaviors.Platform.Acts.SimulateControl,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Plugins.Sprite.Acts.RotateClockwise,
		C3.Plugins.Sprite.Acts.MoveForward,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Sprite.Acts.MoveToBottom,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Plugins.Sprite.Acts.SetScale,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.Sprite.Exps.Height,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Cnds.IsCollisionEnabled,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Sprite.Acts.SetCollisions,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Sprite.Cnds.CompareOpacity,
		C3.Plugins.Sprite.Exps.Opacity,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Sprite.Cnds.CompareY,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Behaviors.scrollto.Acts.Shake,
		C3.Behaviors.Platform.Acts.SetMaxSpeed,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.Plugins.Audio.Acts.SetSilent,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Spritefont2.Acts.SetText,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.Mouse.Exps.Y,
		C3.JavaScriptInEvents.Events_game_Event79_Act1,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Acts.GetItem,
		C3.Plugins.LocalStorage.Cnds.OnItemMissing,
		C3.Plugins.LocalStorage.Cnds.OnItemGet,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.AJAX.Acts.Request,
		C3.Plugins.AJAX.Cnds.OnComplete,
		C3.Plugins.XML.Acts.Load,
		C3.Plugins.AJAX.Exps.LastData,
		C3.Plugins.XML.Exps.StringValue,
		C3.Plugins.Browser.Acts.GoToURLWindow
	];
};
self.C3_JsPropNameTable = [
	{background: 0},
	{ScrollTo: 0},
	{element_camera: 0},
	{direction: 0},
	{copter: 0},
	{Sine: 0},
	{logo_ship: 0},
	{logo_flapcat: 0},
	{Platform: 0},
	{flapcat: 0},
	{ship_air: 0},
	{wall_ghost: 0},
	{Fade: 0},
	{Rotate: 0},
	{effect_smoke: 0},
	{wall_1: 0},
	{wall_up: 0},
	{wall_down: 0},
	{element_limit: 0},
	{Touch: 0},
	{Mouse: 0},
	{effect_blow: 0},
	{effect_down: 0},
	{effect_up: 0},
	{effect_fire: 0},
	{info_bt_sound: 0},
	{info_record: 0},
	{info_points_txt: 0},
	{info_record_txt: 0},
	{share_facebook: 0},
	{share_twitter: 0},
	{Audio: 0},
	{LocalStorage: 0},
	{XML: 0},
	{Browser: 0},
	{AJAX: 0},
	{Anchor: 0},
	{info_tutorial: 0},
	{effect_star: 0},
	{background_limit: 0},
	{home: 0},
	{walls: 0},
	{game: 0},
	{game_motion: 0},
	{game_effect: 0},
	{game_tutorial: 0},
	{game_points: 0},
	{game_record: 0},
	{flapcat_life: 0},
	{flapcat_direction: 0},
	{flapcat_effect: 0},
	{wall_position: 0},
	{facebookShare: 0},
	{facebook_message: 0},
	{twitterShare: 0},
	{twitter_message: 0}
];

self.InstanceType = {
	background: class extends self.ISpriteInstance {},
	element_camera: class extends self.ISpriteInstance {},
	copter: class extends self.ISpriteInstance {},
	logo_ship: class extends self.ISpriteInstance {},
	logo_flapcat: class extends self.ISpriteInstance {},
	flapcat: class extends self.ISpriteInstance {},
	ship_air: class extends self.ISpriteInstance {},
	wall_ghost: class extends self.ISpriteInstance {},
	effect_smoke: class extends self.ISpriteInstance {},
	wall_1: class extends self.ISpriteInstance {},
	wall_up: class extends self.ISpriteInstance {},
	wall_down: class extends self.ISpriteInstance {},
	element_limit: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {},
	Mouse: class extends self.IInstance {},
	effect_blow: class extends self.ISpriteInstance {},
	effect_down: class extends self.ISpriteInstance {},
	effect_up: class extends self.ISpriteInstance {},
	effect_fire: class extends self.ISpriteInstance {},
	info_bt_sound: class extends self.ISpriteInstance {},
	info_record: class extends self.ISpriteInstance {},
	info_points_txt: class extends self.ISpriteFontInstance {},
	info_record_txt: class extends self.ISpriteFontInstance {},
	share_facebook: class extends self.ISpriteInstance {},
	share_twitter: class extends self.ISpriteInstance {},
	Audio: class extends self.IInstance {},
	LocalStorage: class extends self.IInstance {},
	XML: class extends self.IInstance {},
	Browser: class extends self.IInstance {},
	AJAX: class extends self.IInstance {},
	info_tutorial: class extends self.ISpriteInstance {},
	effect_star: class extends self.ISpriteInstance {},
	background_limit: class extends self.ISpriteInstance {},
	home: class extends self.ISpriteInstance {},
	walls: class extends self.ISpriteInstance {}
}