const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Rotate,
		C3.Behaviors.Sin,
		C3.Behaviors.Bullet,
		C3.Behaviors.wrap,
		C3.Plugins.Arr,
		C3.Plugins.Audio,
		C3.Plugins.Browser,
		C3.Plugins.Function,
		C3.Plugins.Mouse,
		C3.Plugins.Touch,
		C3.Plugins.Spritefont2,
		C3.Behaviors.Fade,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Acts.SetGroupActive,
		C3.Plugins.System.Acts.SetVar,
		C3.JavaScriptInEvents.Game_events_Event1_Act8,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Spritefont2.Acts.SetText,
		C3.Plugins.Sprite.Acts.MoveAtAngle,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.Function.Cnds.OnFunction,
		C3.Plugins.Arr.Cnds.ArrForEach,
		C3.Plugins.Arr.Cnds.CompareCurrent,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Arr.Exps.CurY,
		C3.Plugins.Sprite.Acts.SetCollisions,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.Arr.Exps.CurX,
		C3.Plugins.Arr.Acts.SetXYZ,
		C3.Plugins.System.Exps.int,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Sprite.Exps.UID,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Arr.Exps.At,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.Function.Acts.CallFunction,
		C3.Plugins.System.Cnds.For,
		C3.Plugins.Function.Exps.Param,
		C3.Plugins.System.Exps.loopindex,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.System.Exps.layoutheight,
		C3.Plugins.Sprite.Acts.MoveToBottom,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.System.Acts.Wait,
		C3.Behaviors.Fade.Acts.StartFade,
		C3.Plugins.System.Cnds.Repeat,
		C3.Plugins.Sprite.Exps.AnimationFrameCount,
		C3.Plugins.Arr.Cnds.Contains,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.Sprite.Cnds.PickByUID,
		C3.Plugins.Arr.Acts.Clear,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Exps.layoutwidth,
		C3.Plugins.Arr.Acts.SetSize,
		C3.Plugins.System.Exps.dt,
		C3.Plugins.Sprite.Cnds.CompareY,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.Arr.Acts.SetXY,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.System.Cnds.CompareBetween,
		C3.Plugins.Touch.Cnds.OnTouchEnd,
		C3.Plugins.Arr.Cnds.CompareXY,
		C3.Plugins.Sprite.Cnds.CompareX,
		C3.Plugins.System.Acts.SubVar,
		C3.JavaScriptInEvents.Game_events_Event69_Act3,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Mouse.Cnds.IsButtonDown,
		C3.Plugins.Mouse.Acts.SetCursorSprite,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.JavaScriptInEvents.Global_events_Event12_Act2,
		C3.JavaScriptInEvents.Global_events_Event13_Act2,
		C3.Plugins.System.Acts.SetTimescale,
		C3.JavaScriptInEvents.Global_events_Event15_Act3,
		C3.JavaScriptInEvents.Global_events_Event16_Act3,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.Audio.Acts.Preload,
		C3.Plugins.System.Exps.loadingprogress,
		C3.Plugins.Sprite.Acts.SetWidth,
		C3.Plugins.System.Cnds.OnLoadFinished
	];
};
self.C3_JsPropNameTable = [
	{Background: 0},
	{Loading: 0},
	{LoadingBar: 0},
	{LoadingBarBackground: 0},
	{ChessMap: 0},
	{Rotate: 0},
	{Sine: 0},
	{CandyStartMenu: 0},
	{Bullet: 0},
	{Wrap: 0},
	{CandyStartMenu2: 0},
	{CandyStartMenu3: 0},
	{CandyStartMenu4: 0},
	{CandyStartMenu5: 0},
	{CandyStartMenu6: 0},
	{CandyStartMenu7: 0},
	{CandyMatch: 0},
	{BtnMelody: 0},
	{BtnPause: 0},
	{BtnReturn: 0},
	{BtnSound: 0},
	{ButtonPlay: 0},
	{Array: 0},
	{Audio: 0},
	{Browser: 0},
	{Function: 0},
	{Mouse: 0},
	{SwapData: 0},
	{Touch: 0},
	{MovesFont: 0},
	{LevelsFont: 0},
	{LoadingFont: 0},
	{ScoreFont: 0},
	{TimerFont: 0},
	{Frame: 0},
	{Fade: 0},
	{BOOM: 0},
	{Matched: 0},
	{Moving: 0},
	{trigger: 0},
	{targetY: 0},
	{row: 0},
	{col: 0},
	{dy: 0},
	{color: 0},
	{State: 0},
	{Candy: 0},
	{Frame2: 0},
	{Cursor: 0},
	{CursorHover: 0},
	{Marker: 0},
	{Selection: 0},
	{Selection2: 0},
	{Selector: 0},
	{StartMenuFrame: 0},
	{Selector2: 0},
	{Speed: 0},
	{MiniCandy: 0},
	{ScoreCollision: 0},
	{Level: 0},
	{AllScore: 0},
	{OutTimer: 0},
	{Score2: 0},
	{Moves: 0},
	{ScoreBar: 0},
	{LastScore: 0},
	{Minutes: 0},
	{Seconds: 0},
	{TILE: 0},
	{MovingBlocks: 0},
	{Matches: 0},
	{CX: 0},
	{CY: 0},
	{Trigger: 0},
	{FirstPiece: 0},
	{UserId: 0},
	{BestScore: 0},
	{Score: 0},
	{Sound: 0},
	{Melody: 0},
	{TimeScaler: 0}
];

self.InstanceType = {
	Background: class extends self.ISpriteInstance {},
	Loading: class extends self.ISpriteInstance {},
	LoadingBar: class extends self.ISpriteInstance {},
	LoadingBarBackground: class extends self.ISpriteInstance {},
	ChessMap: class extends self.ISpriteInstance {},
	CandyStartMenu: class extends self.ISpriteInstance {},
	CandyStartMenu2: class extends self.ISpriteInstance {},
	CandyStartMenu3: class extends self.ISpriteInstance {},
	CandyStartMenu4: class extends self.ISpriteInstance {},
	CandyStartMenu5: class extends self.ISpriteInstance {},
	CandyStartMenu6: class extends self.ISpriteInstance {},
	CandyStartMenu7: class extends self.ISpriteInstance {},
	CandyMatch: class extends self.ISpriteInstance {},
	BtnMelody: class extends self.ISpriteInstance {},
	BtnPause: class extends self.ISpriteInstance {},
	BtnReturn: class extends self.ISpriteInstance {},
	BtnSound: class extends self.ISpriteInstance {},
	ButtonPlay: class extends self.ISpriteInstance {},
	Array: class extends self.IArrayInstance {},
	Audio: class extends self.IInstance {},
	Browser: class extends self.IInstance {},
	Function: class extends self.IInstance {},
	Mouse: class extends self.IInstance {},
	SwapData: class extends self.IArrayInstance {},
	Touch: class extends self.IInstance {},
	MovesFont: class extends self.ISpriteFontInstance {},
	LevelsFont: class extends self.ISpriteFontInstance {},
	LoadingFont: class extends self.ISpriteFontInstance {},
	ScoreFont: class extends self.ISpriteFontInstance {},
	TimerFont: class extends self.ISpriteFontInstance {},
	Frame: class extends self.ISpriteInstance {},
	BOOM: class extends self.ISpriteInstance {},
	Candy: class extends self.ISpriteInstance {},
	Frame2: class extends self.ISpriteInstance {},
	Cursor: class extends self.ISpriteInstance {},
	CursorHover: class extends self.ISpriteInstance {},
	Marker: class extends self.ISpriteInstance {},
	Selection: class extends self.ISpriteInstance {},
	Selection2: class extends self.ISpriteInstance {},
	Selector: class extends self.ISpriteInstance {},
	StartMenuFrame: class extends self.ISpriteInstance {},
	Selector2: class extends self.ISpriteInstance {},
	MiniCandy: class extends self.ISpriteInstance {},
	ScoreCollision: class extends self.ISpriteInstance {}
}