const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Arr,
		C3.Plugins.Audio,
		C3.Plugins.Browser,
		C3.Plugins.Function,
		C3.Plugins.LocalStorage,
		C3.Plugins.Touch,
		C3.Plugins.Sprite,
		C3.Behaviors.Pin,
		C3.Behaviors.Sin,
		C3.Behaviors.custom,
		C3.Plugins.TiledBg,
		C3.Behaviors.Fade,
		C3.Behaviors.Rotate,
		C3.Plugins.Spritefont2,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Sprite.Acts.SetHeight,
		C3.Plugins.System.Exps.viewportbottom,
		C3.Plugins.Sprite.Acts.SetWidth,
		C3.Plugins.System.Exps.viewportright,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Exps.Height,
		C3.Behaviors.Pin.Acts.Pin,
		C3.Plugins.Arr.Cnds.ArrForEach,
		C3.Plugins.Arr.Acts.SetXY,
		C3.Plugins.Arr.Exps.CurX,
		C3.Plugins.Arr.Exps.CurY,
		C3.Plugins.System.Cnds.For,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.System.Exps.loopindex,
		C3.Plugins.Arr.Acts.JSONLoad,
		C3.Plugins.Function.Acts.CallFunction,
		C3.Plugins.Touch.Cnds.OnTouchEnd,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Touch.Exps.Y,
		C3.Behaviors.Pin.Acts.Unpin,
		C3.Plugins.Audio.Acts.PlayByName,
		C3.Plugins.System.Exps.choose,
		C3.Behaviors.custom.Acts.AccelerateAngle,
		C3.Plugins.Sprite.Exps.Angle,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Touch.Cnds.IsInTouch,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Touch.Exps.X,
		C3.Plugins.Function.Cnds.OnFunction,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.Function.Exps.Param,
		C3.Plugins.Arr.Cnds.CompareXY,
		C3.Plugins.Arr.Exps.At,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.Plugins.Audio.Acts.SetSilent,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.Audio.Acts.StopAll,
		C3.Plugins.System.Cnds.IsMobile,
		C3.Plugins.Browser.Cnds.IsPortraitLandscape,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.System.Acts.SetTimescale,
		C3.Plugins.Sprite.Cnds.OnAnimFinished,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Touch.Cnds.OnTouchStart,
		C3.Behaviors.Fade.Acts.StartFade,
		C3.Plugins.Sprite.Cnds.OnFrameChanged,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Behaviors.custom.Acts.Reverse,
		C3.Plugins.Sprite.Exps.AnimationFrame,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Spritefont2.Acts.SetText,
		C3.Plugins.Arr.Exps.Height,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.Arr.Acts.Push,
		C3.Plugins.Arr.Acts.Delete,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.System.Acts.RestartLayout,
		C3.JavaScriptInEvents.Gamecode_Event383_Act2,
		C3.JavaScriptInEvents.Gamecode_Event384_Act2,
		C3.Plugins.System.Acts.SetGroupActive,
		C3.Plugins.Spritefont2.Acts.Destroy,
		C3.Plugins.Sprite.Cnds.CompareY,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.System.Acts.GoToLayout,
		C3.JavaScriptInEvents.Menucode_Event13_Act3,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Acts.GetItem,
		C3.Plugins.LocalStorage.Cnds.OnItemGet,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.LocalStorage.Cnds.OnItemMissing,
		C3.JavaScriptInEvents.Loadingcode_Event2_Act4
	];
};
self.C3_JsPropNameTable = [
	{Array: 0},
	{Audio: 0},
	{Browser: 0},
	{ConnectDeleter: 0},
	{CurrentGame: 0},
	{Dist: 0},
	{Function: 0},
	{Groups: 0},
	{LocalStorage: 0},
	{Touch: 0},
	{Pin: 0},
	{MoreGamesButton: 0},
	{MoreGamesButton2: 0},
	{Sine: 0},
	{PlayButton: 0},
	{RestartButton: 0},
	{GameBorder: 0},
	{CurX: 0},
	{CurY: 0},
	{GameTile: 0},
	{TopGameBorder: 0},
	{BlackFrame: 0},
	{GameBackground: 0},
	{used: 0},
	{CustomMovement: 0},
	{Ball: 0},
	{group: 0},
	{BallCollision: 0},
	{GameOverFrame: 0},
	{BonusHud: 0},
	{GameTittle: 0},
	{LevelLine: 0},
	{GameForeground: 0},
	{Fade: 0},
	{CompanyLogo: 0},
	{Grass: 0},
	{RotateScreen: 0},
	{SoundUI: 0},
	{GameFloor: 0},
	{Rotate: 0},
	{MenuLight: 0},
	{ColorFrame: 0},
	{MenuBalls: 0},
	{FlyingBalls: 0},
	{Sun: 0},
	{Clouds: 0},
	{CannonBase: 0},
	{GameStone: 0},
	{Cannon: 0},
	{LevelHud: 0},
	{CannonEffect: 0},
	{CannonAim: 0},
	{GameTutorial: 0},
	{FadeScreen: 0},
	{Ballshootfont: 0},
	{GameScoreFont: 0},
	{EndscoreFont: 0},
	{Score1UI: 0},
	{Score2UI: 0},
	{Score3UI: 0},
	{Score4UI: 0},
	{Score5UI: 0},
	{ScoreHUDfamily: 0},
	{Toucher: 0},
	{Shots: 0},
	{ScoreBonus: 0},
	{HighScore: 0},
	{Clear: 0},
	{IsGameOver: 0},
	{Score: 0},
	{MoveEnded: 0},
	{DestrGroup: 0},
	{LineAdded: 0},
	{ShootCounter: 0},
	{TileY: 0},
	{TileX: 0},
	{UserId: 0},
	{InShoot: 0},
	{IsScreenRotate: 0},
	{Sound: 0}
];

self.InstanceType = {
	Array: class extends self.IArrayInstance {},
	Audio: class extends self.IInstance {},
	Browser: class extends self.IInstance {},
	ConnectDeleter: class extends self.IArrayInstance {},
	CurrentGame: class extends self.IArrayInstance {},
	Dist: class extends self.IArrayInstance {},
	Function: class extends self.IInstance {},
	Groups: class extends self.IArrayInstance {},
	LocalStorage: class extends self.IInstance {},
	Touch: class extends self.IInstance {},
	MoreGamesButton: class extends self.ISpriteInstance {},
	MoreGamesButton2: class extends self.ISpriteInstance {},
	PlayButton: class extends self.ISpriteInstance {},
	RestartButton: class extends self.ISpriteInstance {},
	GameBorder: class extends self.ISpriteInstance {},
	GameTile: class extends self.ISpriteInstance {},
	TopGameBorder: class extends self.ISpriteInstance {},
	BlackFrame: class extends self.ISpriteInstance {},
	GameBackground: class extends self.ISpriteInstance {},
	Ball: class extends self.ISpriteInstance {},
	BallCollision: class extends self.ISpriteInstance {},
	GameOverFrame: class extends self.ISpriteInstance {},
	BonusHud: class extends self.ISpriteInstance {},
	GameTittle: class extends self.ISpriteInstance {},
	LevelLine: class extends self.ITiledBackgroundInstance {},
	GameForeground: class extends self.ISpriteInstance {},
	CompanyLogo: class extends self.ISpriteInstance {},
	Grass: class extends self.ISpriteInstance {},
	RotateScreen: class extends self.ISpriteInstance {},
	SoundUI: class extends self.ISpriteInstance {},
	GameFloor: class extends self.ISpriteInstance {},
	MenuLight: class extends self.ISpriteInstance {},
	ColorFrame: class extends self.ISpriteInstance {},
	MenuBalls: class extends self.ISpriteInstance {},
	FlyingBalls: class extends self.ISpriteInstance {},
	Sun: class extends self.ISpriteInstance {},
	Clouds: class extends self.ISpriteInstance {},
	CannonBase: class extends self.ISpriteInstance {},
	GameStone: class extends self.ISpriteInstance {},
	Cannon: class extends self.ISpriteInstance {},
	LevelHud: class extends self.ISpriteInstance {},
	CannonEffect: class extends self.ISpriteInstance {},
	CannonAim: class extends self.ISpriteInstance {},
	GameTutorial: class extends self.ISpriteInstance {},
	FadeScreen: class extends self.ISpriteInstance {},
	Ballshootfont: class extends self.ISpriteFontInstance {},
	GameScoreFont: class extends self.ISpriteFontInstance {},
	EndscoreFont: class extends self.ISpriteFontInstance {},
	Score1UI: class extends self.ISpriteInstance {},
	Score2UI: class extends self.ISpriteInstance {},
	Score3UI: class extends self.ISpriteInstance {},
	Score4UI: class extends self.ISpriteInstance {},
	Score5UI: class extends self.ISpriteInstance {},
	ScoreHUDfamily: class extends self.ISpriteInstance {}
}