const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Sin,
		C3.Plugins.Audio,
		C3.Plugins.Browser,
		C3.Plugins.Keyboard,
		C3.Plugins.Mouse,
		C3.Plugins.Touch,
		C3.Plugins.LocalStorage,
		C3.Behaviors.Fade,
		C3.Behaviors.Bullet,
		C3.Behaviors.Pin,
		C3.Behaviors.destroy,
		C3.Plugins.Spritefont2,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.System.Exps.layoutwidth,
		C3.Plugins.System.Exps.layoutheight,
		C3.Plugins.System.Acts.SetGroupActive,
		C3.Plugins.System.Acts.SetVar,
		C3.JavaScriptInEvents.Gameevent_Event2_Act8,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.System.Exps.viewporttop,
		C3.Plugins.Sprite.Exps.Height,
		C3.Plugins.Spritefont2.Acts.SetPosToObject,
		C3.Plugins.Spritefont2.Acts.SetText,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Sprite.Cnds.CompareX,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.System.Exps.dt,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Sprite.Acts.SetHeight,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.Spritefont2.Acts.SetVisible,
		C3.Plugins.Touch.Cnds.IsInTouch,
		C3.Plugins.Touch.Cnds.OnTouchEnd,
		C3.Plugins.Sprite.Cnds.IsBetweenAngles,
		C3.Plugins.Sprite.Exps.Angle,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Audio.Cnds.IsTagPlaying,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Sprite.Cnds.CompareHeight,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.Sprite.Cnds.IsOutsideLayout,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Behaviors.Fade.Acts.RestartFade,
		C3.JavaScriptInEvents.Gameevent_Event30_Act6,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.System.Exps.projectname,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.System.Exps.viewportleft,
		C3.Plugins.System.Exps.viewportright,
		C3.Plugins.System.Exps.viewportbottom,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.System.Cnds.Repeat,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.Sprite.Acts.RotateTowardAngle,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Behaviors.Bullet.Acts.SetGravity,
		C3.Behaviors.Bullet.Acts.SetSpeed,
		C3.Behaviors.Pin.Acts.Pin,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Acts.SubInstanceVar,
		C3.Plugins.Audio.Acts.Preload,
		C3.Plugins.Spritefont2.Acts.SetPos,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.System.Exps.loadingprogress,
		C3.Plugins.Spritefont2.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.System.Cnds.OnLoadFinished,
		C3.Plugins.Spritefont2.Acts.SetBoolInstanceVar,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.Keyboard.Cnds.OnAnyKey,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.System.Acts.WaitForSignal,
		C3.Plugins.Mouse.Cnds.IsOverObject,
		C3.Behaviors.Sin.Acts.SetEnabled,
		C3.Plugins.System.Acts.SetLayerOpacity,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.LocalStorage.Cnds.OnItemMissing,
		C3.Plugins.Audio.Acts.SetVolume,
		C3.JavaScriptInEvents.Globalevent_Event27_Act1,
		C3.Plugins.System.Acts.SetTimescale,
		C3.Plugins.Browser.Acts.RequestFullScreen,
		C3.Plugins.Browser.Acts.CancelFullScreen,
		C3.Plugins.Mouse.Cnds.IsButtonDown,
		C3.Plugins.Mouse.Acts.SetCursorSprite,
		C3.Plugins.System.Cnds.LayerCmpOpacity,
		C3.Plugins.System.Exps.layeropacity,
		C3.Plugins.System.Acts.Signal,
		C3.JavaScriptInEvents.Menuevent_Event4_Act1,
		C3.Plugins.System.Acts.GoToLayoutByName,
		C3.Plugins.Sprite.Acts.StartAnim,
		C3.JavaScriptInEvents.Menuevent_Event9_Act2,
		C3.Plugins.Browser.Acts.Close,
		C3.Plugins.Sprite.Acts.SetPosToObject,
		C3.JavaScriptInEvents.Gameoverevent_Event5_Act1
	];
};
self.C3_JsPropNameTable = [
	{Cursor: 0},
	{CursorHover: 0},
	{Sine: 0},
	{SunRays: 0},
	{FrameBestScore: 0},
	{FrameScore: 0},
	{Loading_Background: 0},
	{Level_3_Background_Water: 0},
	{Level_3_Foreground_Water: 0},
	{Level_3_Middleground_Water: 0},
	{Level_4_Middleground_Water: 0},
	{Main_Background: 0},
	{Level_1_Background: 0},
	{Level_1_Foreground: 0},
	{Level_2_Middleground: 0},
	{Level_2_Foreground: 0},
	{Level_2_Background: 0},
	{Level_3_Background: 0},
	{Level_3_Middleground: 0},
	{Level_4_Foreground: 0},
	{Level_4_Middleground: 0},
	{Audio: 0},
	{Browser: 0},
	{Keyboard: 0},
	{Mouse: 0},
	{Touch: 0},
	{LocalStorage: 0},
	{Size: 0},
	{Fade: 0},
	{Star: 0},
	{Clouds: 0},
	{Bullet: 0},
	{Pin: 0},
	{DestroyOutsideLayout: 0},
	{Snowflakes: 0},
	{Burning: 0},
	{Player: 0},
	{Platform_1: 0},
	{Platform_2: 0},
	{Stick: 0},
	{TextFont: 0},
	{BestScoreFont: 0},
	{ScoreFont: 0},
	{HelpFont: 0},
	{Active: 0},
	{LoadingFont: 0},
	{GameScoreFont: 0},
	{ButtonExit: 0},
	{ButtonFullscreen: 0},
	{ButtonPlay: 0},
	{ButtonMenu: 0},
	{ButtonMusic: 0},
	{ButtonSound: 0},
	{ButtonStart: 0},
	{ButtonRestart: 0},
	{Collision: 0},
	{WindowGameOver: 0},
	{WindowScore: 0},
	{GameIcon: 0},
	{GameLogo: 0},
	{PlayerLogo: 0},
	{Buttons: 0},
	{Texts: 0},
	{GameState: 0},
	{Score: 0},
	{WalkDist: 0},
	{BestScore: 0},
	{StateShaking: 0},
	{UserId: 0},
	{NewPlatformX: 0},
	{Level: 0},
	{Fullscreen: 0},
	{Sound: 0},
	{Sound_Volume: 0},
	{Music: 0},
	{Music_Volume: 0}
];

self.InstanceType = {
	Cursor: class extends self.ISpriteInstance {},
	CursorHover: class extends self.ISpriteInstance {},
	SunRays: class extends self.ISpriteInstance {},
	FrameBestScore: class extends self.ISpriteInstance {},
	FrameScore: class extends self.ISpriteInstance {},
	Loading_Background: class extends self.ISpriteInstance {},
	Level_3_Background_Water: class extends self.ISpriteInstance {},
	Level_3_Foreground_Water: class extends self.ISpriteInstance {},
	Level_3_Middleground_Water: class extends self.ISpriteInstance {},
	Level_4_Middleground_Water: class extends self.ISpriteInstance {},
	Main_Background: class extends self.ISpriteInstance {},
	Level_1_Background: class extends self.ISpriteInstance {},
	Level_1_Foreground: class extends self.ISpriteInstance {},
	Level_2_Middleground: class extends self.ISpriteInstance {},
	Level_2_Foreground: class extends self.ISpriteInstance {},
	Level_2_Background: class extends self.ISpriteInstance {},
	Level_3_Background: class extends self.ISpriteInstance {},
	Level_3_Middleground: class extends self.ISpriteInstance {},
	Level_4_Foreground: class extends self.ISpriteInstance {},
	Level_4_Middleground: class extends self.ISpriteInstance {},
	Audio: class extends self.IInstance {},
	Browser: class extends self.IInstance {},
	Keyboard: class extends self.IInstance {},
	Mouse: class extends self.IInstance {},
	Touch: class extends self.IInstance {},
	LocalStorage: class extends self.IInstance {},
	Star: class extends self.ISpriteInstance {},
	Clouds: class extends self.ISpriteInstance {},
	Snowflakes: class extends self.ISpriteInstance {},
	Player: class extends self.ISpriteInstance {},
	Platform_1: class extends self.ISpriteInstance {},
	Platform_2: class extends self.ISpriteInstance {},
	Stick: class extends self.ISpriteInstance {},
	TextFont: class extends self.ISpriteFontInstance {},
	BestScoreFont: class extends self.ISpriteFontInstance {},
	ScoreFont: class extends self.ISpriteFontInstance {},
	HelpFont: class extends self.ISpriteFontInstance {},
	LoadingFont: class extends self.ISpriteFontInstance {},
	GameScoreFont: class extends self.ISpriteFontInstance {},
	ButtonExit: class extends self.ISpriteInstance {},
	ButtonFullscreen: class extends self.ISpriteInstance {},
	ButtonPlay: class extends self.ISpriteInstance {},
	ButtonMenu: class extends self.ISpriteInstance {},
	ButtonMusic: class extends self.ISpriteInstance {},
	ButtonSound: class extends self.ISpriteInstance {},
	ButtonStart: class extends self.ISpriteInstance {},
	ButtonRestart: class extends self.ISpriteInstance {},
	Collision: class extends self.ISpriteInstance {},
	WindowGameOver: class extends self.ISpriteInstance {},
	WindowScore: class extends self.ISpriteInstance {},
	GameIcon: class extends self.ISpriteInstance {},
	GameLogo: class extends self.ISpriteInstance {},
	PlayerLogo: class extends self.ISpriteInstance {},
	Buttons: class extends self.ISpriteInstance {},
	Texts: class extends self.ISpriteInstance {}
}