const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Rotate,
		C3.Behaviors.Fade,
		C3.Behaviors.Sin,
		C3.Plugins.Audio,
		C3.Plugins.Browser,
		C3.Plugins.Keyboard,
		C3.Plugins.Mouse,
		C3.Plugins.Touch,
		C3.Plugins.LocalStorage,
		C3.Behaviors.Bullet,
		C3.Behaviors.Physics,
		C3.Plugins.Spritefont2,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.System.Exps.layoutwidth,
		C3.Plugins.System.Exps.layoutheight,
		C3.Plugins.Spritefont2.Acts.SetPos,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.System.Acts.SetGroupActive,
		C3.Plugins.System.Acts.SetVar,
		C3.JavaScriptInEvents.Game_events_Event2_Act29,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.System.Exps.viewportleft,
		C3.Plugins.System.Exps.viewporttop,
		C3.Plugins.System.Exps.viewportright,
		C3.Plugins.System.Exps.viewportbottom,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Behaviors.Sin.Cnds.IsEnabled,
		C3.Behaviors.Fade.Acts.StartFade,
		C3.Behaviors.Sin.Acts.SetEnabled,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Sprite.Cnds.OnDestroyed,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Sprite.Acts.SetPosToObject,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.Sprite.Exps.Angle,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Spritefont2.Acts.SetText,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Behaviors.Fade.Acts.RestartFade,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.System.Acts.WaitForSignal,
		C3.Plugins.System.Acts.GoToLayout,
		C3.JavaScriptInEvents.Game_events_Event30_Act4,
		C3.Plugins.Touch.Cnds.OnTouchStart,
		C3.Plugins.Touch.Exps.X,
		C3.Plugins.Touch.Exps.Y,
		C3.Plugins.Touch.Cnds.IsInTouch,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Acts.SetWidth,
		C3.Plugins.Sprite.Acts.SetHeight,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Exps.Height,
		C3.Behaviors.Physics.Acts.ApplyImpulseAtAngle,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Behaviors.Physics.Acts.SetImmovable,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.Plugins.System.Acts.SetLayerScale,
		C3.Plugins.Sprite.Cnds.OnAnyAnimFinished,
		C3.Plugins.Sprite.Cnds.CompareWidth,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Spritefont2.Acts.SetAngle,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Audio.Acts.Preload,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.System.Exps.loadingprogress,
		C3.Plugins.System.Cnds.OnLoadFinished,
		C3.Plugins.System.Acts.SetLayerOpacity,
		C3.Plugins.System.Acts.SetTimescale,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.LocalStorage.Cnds.OnItemMissing,
		C3.JavaScriptInEvents.Global_events_Event9_Act1,
		C3.JavaScriptInEvents.Global_events_Event12_Act1,
		C3.Plugins.Sprite.Cnds.CompareAnimSpeed,
		C3.Plugins.System.Acts.Wait,
		C3.JavaScriptInEvents.Global_events_Event14_Act1,
		C3.JavaScriptInEvents.Global_events_Event17_Act1,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.Sprite.Acts.StartAnim,
		C3.Plugins.Audio.Acts.SetVolume,
		C3.Plugins.System.Cnds.Else,
		C3.JavaScriptInEvents.Global_events_Event39_Act2,
		C3.Plugins.Browser.Acts.Close,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.System.Exps.layeropacity,
		C3.Plugins.System.Exps.layerscale,
		C3.Plugins.System.Cnds.LayerCmpOpacity,
		C3.Plugins.System.Acts.Signal,
		C3.JavaScriptInEvents.Main_events_Event4_Act1,
		C3.JavaScriptInEvents.Game_over_events_Event5_Act1
	];
};
self.C3_JsPropNameTable = [
	{Cursor: 0},
	{CursorHover: 0},
	{Rotate: 0},
	{SunRays: 0},
	{EndMusic: 0},
	{EndSound: 0},
	{FramePaused: 0},
	{AreaMusic: 0},
	{SliderMusic: 0},
	{TextPaused: 0},
	{AreaSound: 0},
	{FrameSound: 0},
	{SliderSound: 0},
	{FrameMusic: 0},
	{Fade: 0},
	{TextTapToPlay: 0},
	{TextGameOver: 0},
	{TextGameResults: 0},
	{TextTimeOver: 0},
	{FrameFruits: 0},
	{FrameLives: 0},
	{FrameTime: 0},
	{Background: 0},
	{Sine: 0},
	{GameLogo: 0},
	{GameIcon: 0},
	{TouchArea: 0},
	{Audio: 0},
	{Browser: 0},
	{Keyboard: 0},
	{Mouse: 0},
	{Touch: 0},
	{LocalStorage: 0},
	{Explosion: 0},
	{Grass: 0},
	{ID: 0},
	{Bullet: 0},
	{Flame: 0},
	{Touched: 0},
	{SelfWidth: 0},
	{SelfHeight: 0},
	{Physics: 0},
	{Fruits: 0},
	{Slasher: 0},
	{Blasts: 0},
	{Bomb: 0},
	{LastScoreFont: 0},
	{LifeFont: 0},
	{BestScoreFont: 0},
	{ScoreFont: 0},
	{TimeFont: 0},
	{MusicFont: 0},
	{SoundFont: 0},
	{LoadingFont: 0},
	{InfoFont: 0},
	{GameScoreFont: 0},
	{ComboFont: 0},
	{ButtonExit: 0},
	{ButtonPlay: 0},
	{ButtonMenu: 0},
	{ButtonMusic: 0},
	{ButtonPause: 0},
	{ButtonReload: 0},
	{ButtonReturn: 0},
	{ButtonSound: 0},
	{ButtonStart: 0},
	{ButtonGo: 0},
	{ButtonRestart: 0},
	{ButtonAddMusic: 0},
	{ButtonAddSound: 0},
	{ButtonSubtractMusic: 0},
	{ButtonSubtractSound: 0},
	{Side: 0},
	{WallCollision: 0},
	{DamageCollision: 0},
	{Buttons: 0},
	{TextFonts: 0},
	{LastX: 0},
	{LastY: 0},
	{Scale: 0},
	{Lives: 0},
	{Score: 0},
	{Minutes: 0},
	{Seconds: 0},
	{UserId: 0},
	{LastScore: 0},
	{BestScore: 0},
	{Sound: 0},
	{Music: 0},
	{Pause: 0}
];

self.InstanceType = {
	Cursor: class extends self.ISpriteInstance {},
	CursorHover: class extends self.ISpriteInstance {},
	SunRays: class extends self.ISpriteInstance {},
	EndMusic: class extends self.ISpriteInstance {},
	EndSound: class extends self.ISpriteInstance {},
	FramePaused: class extends self.ISpriteInstance {},
	AreaMusic: class extends self.ISpriteInstance {},
	SliderMusic: class extends self.ISpriteInstance {},
	TextPaused: class extends self.ISpriteInstance {},
	AreaSound: class extends self.ISpriteInstance {},
	FrameSound: class extends self.ISpriteInstance {},
	SliderSound: class extends self.ISpriteInstance {},
	FrameMusic: class extends self.ISpriteInstance {},
	TextTapToPlay: class extends self.ISpriteInstance {},
	TextGameOver: class extends self.ISpriteInstance {},
	TextGameResults: class extends self.ISpriteInstance {},
	TextTimeOver: class extends self.ISpriteInstance {},
	FrameFruits: class extends self.ISpriteInstance {},
	FrameLives: class extends self.ISpriteInstance {},
	FrameTime: class extends self.ISpriteInstance {},
	Background: class extends self.ISpriteInstance {},
	GameLogo: class extends self.ISpriteInstance {},
	GameIcon: class extends self.ISpriteInstance {},
	TouchArea: class extends self.ISpriteInstance {},
	Audio: class extends self.IInstance {},
	Browser: class extends self.IInstance {},
	Keyboard: class extends self.IInstance {},
	Mouse: class extends self.IInstance {},
	Touch: class extends self.IInstance {},
	LocalStorage: class extends self.IInstance {},
	Explosion: class extends self.ISpriteInstance {},
	Grass: class extends self.ISpriteInstance {},
	Flame: class extends self.ISpriteInstance {},
	Fruits: class extends self.ISpriteInstance {},
	Slasher: class extends self.ISpriteInstance {},
	Blasts: class extends self.ISpriteInstance {},
	Bomb: class extends self.ISpriteInstance {},
	LastScoreFont: class extends self.ISpriteFontInstance {},
	LifeFont: class extends self.ISpriteFontInstance {},
	BestScoreFont: class extends self.ISpriteFontInstance {},
	ScoreFont: class extends self.ISpriteFontInstance {},
	TimeFont: class extends self.ISpriteFontInstance {},
	MusicFont: class extends self.ISpriteFontInstance {},
	SoundFont: class extends self.ISpriteFontInstance {},
	LoadingFont: class extends self.ISpriteFontInstance {},
	InfoFont: class extends self.ISpriteFontInstance {},
	GameScoreFont: class extends self.ISpriteFontInstance {},
	ComboFont: class extends self.ISpriteFontInstance {},
	ButtonExit: class extends self.ISpriteInstance {},
	ButtonPlay: class extends self.ISpriteInstance {},
	ButtonMenu: class extends self.ISpriteInstance {},
	ButtonMusic: class extends self.ISpriteInstance {},
	ButtonPause: class extends self.ISpriteInstance {},
	ButtonReload: class extends self.ISpriteInstance {},
	ButtonReturn: class extends self.ISpriteInstance {},
	ButtonSound: class extends self.ISpriteInstance {},
	ButtonStart: class extends self.ISpriteInstance {},
	ButtonGo: class extends self.ISpriteInstance {},
	ButtonRestart: class extends self.ISpriteInstance {},
	ButtonAddMusic: class extends self.ISpriteInstance {},
	ButtonAddSound: class extends self.ISpriteInstance {},
	ButtonSubtractMusic: class extends self.ISpriteInstance {},
	ButtonSubtractSound: class extends self.ISpriteInstance {},
	WallCollision: class extends self.ISpriteInstance {},
	DamageCollision: class extends self.ISpriteInstance {},
	Buttons: class extends self.ISpriteInstance {},
	TextFonts: class extends self.ISpriteInstance {}
}