const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Audio,
		C3.Plugins.Browser,
		C3.Plugins.LocalStorage,
		C3.Plugins.Mouse,
		C3.Plugins.Touch,
		C3.Plugins.Sprite,
		C3.Behaviors.Bullet,
		C3.Behaviors.Pin,
		C3.Behaviors.destroy,
		C3.Behaviors.Rotate,
		C3.Plugins.Spritefont2,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Spritefont2.Acts.SetVisible,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Sprite.Acts.SetHeight,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.System.Exps.projectname,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.Spritefont2.Acts.SetText,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Sprite.Cnds.CompareX,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.System.Exps.dt,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Sprite.Acts.SetWidth,
		C3.Plugins.System.Exps.layoutwidth,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.Touch.Cnds.IsInTouch,
		C3.Plugins.Sprite.Exps.Height,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Touch.Cnds.OnTouchEnd,
		C3.Plugins.Sprite.Cnds.IsBetweenAngles,
		C3.Plugins.Sprite.Exps.Angle,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Audio.Cnds.IsTagPlaying,
		C3.Plugins.Sprite.Cnds.CompareHeight,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Cnds.IsOutsideLayout,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.JavaScriptInEvents.Game_events_Event27_Act4,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.System.Acts.ResetGlobals,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Acts.RestartLayout,
		C3.JavaScriptInEvents.Game_events_Event29_Act4,
		C3.Plugins.System.Cnds.OnLoadFinished,
		C3.Plugins.Audio.Acts.Preload,
		C3.Plugins.System.Acts.GoToLayout,
		C3.JavaScriptInEvents.Loading_events_Event1_Act10,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.JavaScriptInEvents.Global_events_Event2_Act10,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.System.Acts.SetGroupActive,
		C3.Plugins.Audio.Acts.SetVolume,
		C3.JavaScriptInEvents.Global_events_Event34_Act4,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Cnds.Repeat,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.Sprite.Acts.RotateTowardAngle,
		C3.Behaviors.Bullet.Acts.SetGravity,
		C3.Behaviors.Bullet.Acts.SetSpeed,
		C3.Behaviors.Pin.Acts.Pin,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Acts.SubInstanceVar
	];
};
self.C3_JsPropNameTable = [
	{Audio: 0},
	{Browser: 0},
	{LocalStorage: 0},
	{Mouse: 0},
	{Touch: 0},
	{BtnMelody: 0},
	{BtnPlay: 0},
	{BtnSound: 0},
	{Frame: 0},
	{Background: 0},
	{GameLogo: 0},
	{Platform1: 0},
	{Platform2: 0},
	{Burning: 0},
	{Player: 0},
	{Bullet: 0},
	{Pin: 0},
	{DestroyOutsideLayout: 0},
	{Snow: 0},
	{Stick: 0},
	{Rotate: 0},
	{SunLogo: 0},
	{SunScore: 0},
	{Collision: 0},
	{CollisionGameOver: 0},
	{Sprite: 0},
	{HelpFont: 0},
	{HighScoreFont: 0},
	{ScoreFont: 0},
	{WonderfulFont: 0},
	{GameState: 0},
	{StateShaking: 0},
	{Score: 0},
	{HighScore: 0},
	{NewPlatformX: 0},
	{WalkDist: 0},
	{Melody: 0},
	{Sound: 0}
];

self.InstanceType = {
	Audio: class extends self.IInstance {},
	Browser: class extends self.IInstance {},
	LocalStorage: class extends self.IInstance {},
	Mouse: class extends self.IInstance {},
	Touch: class extends self.IInstance {},
	BtnMelody: class extends self.ISpriteInstance {},
	BtnPlay: class extends self.ISpriteInstance {},
	BtnSound: class extends self.ISpriteInstance {},
	Background: class extends self.ISpriteInstance {},
	GameLogo: class extends self.ISpriteInstance {},
	Platform1: class extends self.ISpriteInstance {},
	Platform2: class extends self.ISpriteInstance {},
	Player: class extends self.ISpriteInstance {},
	Snow: class extends self.ISpriteInstance {},
	Stick: class extends self.ISpriteInstance {},
	SunLogo: class extends self.ISpriteInstance {},
	SunScore: class extends self.ISpriteInstance {},
	Collision: class extends self.ISpriteInstance {},
	CollisionGameOver: class extends self.ISpriteInstance {},
	Sprite: class extends self.ISpriteInstance {},
	HelpFont: class extends self.ISpriteFontInstance {},
	HighScoreFont: class extends self.ISpriteFontInstance {},
	ScoreFont: class extends self.ISpriteFontInstance {},
	WonderfulFont: class extends self.ISpriteFontInstance {}
}