const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Rotate,
		C3.Behaviors.Fade,
		C3.Behaviors.Sin,
		C3.Plugins.Audio,
		C3.Plugins.Browser,
		C3.Plugins.Keyboard,
		C3.Plugins.Mouse,
		C3.Plugins.Touch,
		C3.Plugins.LocalStorage,
		C3.Behaviors.Pin,
		C3.Behaviors.Bullet,
		C3.Plugins.TiledBg,
		C3.Behaviors.Flash,
		C3.Plugins.Spritefont2,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Acts.SetGroupActive,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Spritefont2.Acts.SetText,
		C3.Plugins.Sprite.Acts.SetPosToObject,
		C3.Behaviors.Bullet.Acts.SetEnabled,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Mouse.Cnds.IsOverObject,
		C3.Plugins.Sprite.Acts.SetTowardPosition,
		C3.Plugins.Mouse.Exps.X,
		C3.Plugins.Mouse.Exps.Y,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.Sprite.Exps.X,
		C3.Behaviors.Sin.Acts.SetEnabled,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Behaviors.Sin.Cnds.IsEnabled,
		C3.Plugins.Audio.Acts.Play,
		C3.Behaviors.Fade.Acts.StartFade,
		C3.Plugins.Mouse.Cnds.OnObjectClicked,
		C3.Plugins.Sprite.Cnds.OnDestroyed,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.System.Exps.viewportright,
		C3.Plugins.System.Exps.viewportbottom,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.System.Exps.projectname,
		C3.Plugins.System.Acts.WaitForSignal,
		C3.Plugins.System.Acts.GoToLayout,
		C3.JavaScriptInEvents.Gameevent_Event33_Act4,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.JavaScriptInEvents.Gameevent_Event38_Act4,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.Touch.Exps.X,
		C3.Plugins.Touch.Exps.Y,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Sprite.Acts.StartAnim,
		C3.Behaviors.Bullet.Acts.SetAngleOfMotion,
		C3.Plugins.Sprite.Exps.Angle,
		C3.Behaviors.Pin.Acts.Pin,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Plugins.Sprite.Cnds.CompareX,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.Sprite.Acts.StopAnim,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Behaviors.Flash.Acts.Flash,
		C3.Plugins.Sprite.Cnds.IsOutsideLayout,
		C3.Plugins.Sprite.Cnds.OnAnyAnimFinished,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Sprite.Exps.AnimationFrame,
		C3.Plugins.Sprite.Acts.MoveToBottom,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.System.Exps.loadingprogress,
		C3.Plugins.System.Cnds.OnLoadFinished,
		C3.Plugins.Audio.Acts.Preload,
		C3.Plugins.System.Acts.SetLayerOpacity,
		C3.Plugins.System.Acts.SetTimescale,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.Spritefont2.Cnds.CompareInstanceVar,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.TiledBg.Acts.SetX,
		C3.Plugins.TiledBg.Exps.X,
		C3.Plugins.LocalStorage.Cnds.OnItemMissing,
		C3.Plugins.Audio.Acts.SetVolume,
		C3.Plugins.System.Cnds.Else,
		C3.JavaScriptInEvents.Addevent_Event43_Act6,
		C3.JavaScriptInEvents.Addevent_Event45_Act6,
		C3.JavaScriptInEvents.Addevent_Event46_Act1,
		C3.JavaScriptInEvents.Addevent_Event50_Act1,
		C3.Plugins.System.Acts.RestartLayout,
		C3.JavaScriptInEvents.Addevent_Event53_Act6,
		C3.JavaScriptInEvents.Addevent_Event60_Act1,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Browser.Acts.Close,
		C3.Plugins.Browser.Acts.RequestFullScreen,
		C3.Plugins.Browser.Acts.CancelFullScreen,
		C3.Plugins.Mouse.Cnds.IsButtonDown,
		C3.Plugins.Mouse.Acts.SetCursorSprite,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.JavaScriptInEvents.Addevent_Event99_Act1,
		C3.Plugins.Sprite.Cnds.CompareAnimSpeed,
		C3.JavaScriptInEvents.Addevent_Event101_Act1,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.System.Acts.SetLayerScale,
		C3.Plugins.System.Exps.layeropacity,
		C3.Plugins.System.Exps.layerscale,
		C3.Plugins.TiledBg.Cnds.CompareX,
		C3.Plugins.TiledBg.Exps.Width,
		C3.JavaScriptInEvents.Addevent_Event117,
		C3.Plugins.System.Cnds.LayerCmpOpacity,
		C3.Plugins.System.Acts.Signal
	];
};
self.C3_JsPropNameTable = [
	{Cursor: 0},
	{CursorHover: 0},
	{Rotate: 0},
	{SunLight: 0},
	{FramePaused: 0},
	{TextPaused: 0},
	{FrameInfo: 0},
	{TextGameInfo: 0},
	{Fade: 0},
	{TextTapToPlay: 0},
	{TextGameOver: 0},
	{TextGameResults: 0},
	{GuiLife: 0},
	{GuiTime: 0},
	{FrameGui: 0},
	{GuiRockets: 0},
	{GuiScore: 0},
	{TextTimeOver: 0},
	{InfoIcons: 0},
	{Background: 0},
	{Sine: 0},
	{GameLogo: 0},
	{GameIcon: 0},
	{Clouds: 0},
	{TouchArea: 0},
	{Barrel: 0},
	{Fire: 0},
	{Audio: 0},
	{Browser: 0},
	{Keyboard: 0},
	{Mouse: 0},
	{Touch: 0},
	{LocalStorage: 0},
	{Explosion_1: 0},
	{Explosion_2: 0},
	{Explosion_3: 0},
	{Explosion_4: 0},
	{ID: 0},
	{Pin: 0},
	{RocketTrail_1: 0},
	{Bullet: 0},
	{TankRocket_1: 0},
	{Bomb: 0},
	{Explosion_5: 0},
	{Explosion_6: 0},
	{Smoke: 0},
	{TankMuzzle_Effect: 0},
	{SmokeEffect: 0},
	{Move: 0},
	{Box: 0},
	{Parachute: 0},
	{Flash: 0},
	{Shield: 0},
	{TankRocket_2: 0},
	{RocketTrail_2: 0},
	{Score: 0},
	{AddLife: 0},
	{AddRockets: 0},
	{AddRocketsX2: 0},
	{AddScore: 0},
	{AddSeconds: 0},
	{AddShield: 0},
	{DustEffect: 0},
	{Type: 0},
	{Tank: 0},
	{TankMuzzle: 0},
	{Speed: 0},
	{Turn: 0},
	{Aircrafts: 0},
	{FriendlyAircraft: 0},
	{LastScoreFont: 0},
	{LivesFont: 0},
	{BestScoreFont: 0},
	{ScoreFont: 0},
	{TimeFont: 0},
	{LoadingFont: 0},
	{InfoFont: 0},
	{GameOverFont: 0},
	{RocketsFont: 0},
	{BtnExit: 0},
	{BtnFullscreen: 0},
	{BtnPlay: 0},
	{BtnInfo: 0},
	{BtnMenu: 0},
	{Button_Music: 0},
	{BtnPause: 0},
	{BtnReload: 0},
	{BtnReturn: 0},
	{Button_Sound: 0},
	{BtnStart: 0},
	{BtnGo: 0},
	{BtnLeft: 0},
	{BtnRight: 0},
	{BtnAutoShooting: 0},
	{BtnRestart: 0},
	{Buttons: 0},
	{TextFonts: 0},
	{Scores: 0},
	{Lives: 0},
	{Rockets: 0},
	{Seconds: 0},
	{Minutes: 0},
	{LastScore: 0},
	{BestScore: 0},
	{CountScore: 0},
	{CountRockets: 0},
	{AutoShooting: 0},
	{CountSeconds: 0},
	{Pause: 0},
	{Fullscreen: 0},
	{Sound: 0},
	{Sound_Status: 0},
	{Music: 0},
	{Music_Status: 0}
];

self.InstanceType = {
	Cursor: class extends self.ISpriteInstance {},
	CursorHover: class extends self.ISpriteInstance {},
	SunLight: class extends self.ISpriteInstance {},
	FramePaused: class extends self.ISpriteInstance {},
	TextPaused: class extends self.ISpriteInstance {},
	FrameInfo: class extends self.ISpriteInstance {},
	TextGameInfo: class extends self.ISpriteInstance {},
	TextTapToPlay: class extends self.ISpriteInstance {},
	TextGameOver: class extends self.ISpriteInstance {},
	TextGameResults: class extends self.ISpriteInstance {},
	GuiLife: class extends self.ISpriteInstance {},
	GuiTime: class extends self.ISpriteInstance {},
	FrameGui: class extends self.ISpriteInstance {},
	GuiRockets: class extends self.ISpriteInstance {},
	GuiScore: class extends self.ISpriteInstance {},
	TextTimeOver: class extends self.ISpriteInstance {},
	InfoIcons: class extends self.ISpriteInstance {},
	Background: class extends self.ISpriteInstance {},
	GameLogo: class extends self.ISpriteInstance {},
	GameIcon: class extends self.ISpriteInstance {},
	Clouds: class extends self.ISpriteInstance {},
	TouchArea: class extends self.ISpriteInstance {},
	Barrel: class extends self.ISpriteInstance {},
	Fire: class extends self.ISpriteInstance {},
	Audio: class extends self.IInstance {},
	Browser: class extends self.IInstance {},
	Keyboard: class extends self.IInstance {},
	Mouse: class extends self.IInstance {},
	Touch: class extends self.IInstance {},
	LocalStorage: class extends self.IInstance {},
	Explosion_1: class extends self.ISpriteInstance {},
	Explosion_2: class extends self.ISpriteInstance {},
	Explosion_3: class extends self.ISpriteInstance {},
	Explosion_4: class extends self.ISpriteInstance {},
	RocketTrail_1: class extends self.ISpriteInstance {},
	TankRocket_1: class extends self.ISpriteInstance {},
	Bomb: class extends self.ISpriteInstance {},
	Explosion_5: class extends self.ISpriteInstance {},
	Explosion_6: class extends self.ISpriteInstance {},
	Smoke: class extends self.ITiledBackgroundInstance {},
	TankMuzzle_Effect: class extends self.ISpriteInstance {},
	SmokeEffect: class extends self.ISpriteInstance {},
	Box: class extends self.ISpriteInstance {},
	Parachute: class extends self.ISpriteInstance {},
	Shield: class extends self.ISpriteInstance {},
	TankRocket_2: class extends self.ISpriteInstance {},
	RocketTrail_2: class extends self.ISpriteInstance {},
	Score: class extends self.ISpriteInstance {},
	AddLife: class extends self.ISpriteInstance {},
	AddRockets: class extends self.ISpriteInstance {},
	AddRocketsX2: class extends self.ISpriteInstance {},
	AddScore: class extends self.ISpriteInstance {},
	AddSeconds: class extends self.ISpriteInstance {},
	AddShield: class extends self.ISpriteInstance {},
	DustEffect: class extends self.ISpriteInstance {},
	Tank: class extends self.ISpriteInstance {},
	TankMuzzle: class extends self.ISpriteInstance {},
	Aircrafts: class extends self.ISpriteInstance {},
	FriendlyAircraft: class extends self.ISpriteInstance {},
	LastScoreFont: class extends self.ISpriteFontInstance {},
	LivesFont: class extends self.ISpriteFontInstance {},
	BestScoreFont: class extends self.ISpriteFontInstance {},
	ScoreFont: class extends self.ISpriteFontInstance {},
	TimeFont: class extends self.ISpriteFontInstance {},
	LoadingFont: class extends self.ISpriteFontInstance {},
	InfoFont: class extends self.ISpriteFontInstance {},
	GameOverFont: class extends self.ISpriteFontInstance {},
	RocketsFont: class extends self.ISpriteFontInstance {},
	BtnExit: class extends self.ISpriteInstance {},
	BtnFullscreen: class extends self.ISpriteInstance {},
	BtnPlay: class extends self.ISpriteInstance {},
	BtnInfo: class extends self.ISpriteInstance {},
	BtnMenu: class extends self.ISpriteInstance {},
	Button_Music: class extends self.ISpriteInstance {},
	BtnPause: class extends self.ISpriteInstance {},
	BtnReload: class extends self.ISpriteInstance {},
	BtnReturn: class extends self.ISpriteInstance {},
	Button_Sound: class extends self.ISpriteInstance {},
	BtnStart: class extends self.ISpriteInstance {},
	BtnGo: class extends self.ISpriteInstance {},
	BtnLeft: class extends self.ISpriteInstance {},
	BtnRight: class extends self.ISpriteInstance {},
	BtnAutoShooting: class extends self.ISpriteInstance {},
	BtnRestart: class extends self.ISpriteInstance {},
	Buttons: class extends self.ISpriteInstance {},
	TextFonts: class extends self.ISpriteInstance {},
	Scores: class extends self.ISpriteInstance {}
}