const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Platform,
		C3.Behaviors.Bullet,
		C3.Plugins.Touch,
		C3.Plugins.TiledBg,
		C3.Behaviors.solid,
		C3.Plugins.Particles,
		C3.Plugins.Spritefont2,
		C3.Behaviors.Sin,
		C3.Plugins.Browser,
		C3.Plugins.Audio,
		C3.Plugins.LocalStorage,
		C3.Plugins.advert,
		C3.Behaviors.Pin,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.System.Exps.viewportright,
		C3.Plugins.System.Exps.viewporttop,
		C3.Behaviors.Bullet.Acts.SetAngleOfMotion,
		C3.Plugins.Audio.Cnds.IsTagPlaying,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Cnds.Every,
		C3.Behaviors.Platform.Acts.SetVectorY,
		C3.Plugins.Sprite.Acts.StartAnim,
		C3.Plugins.TiledBg.Cnds.CompareX,
		C3.Plugins.TiledBg.Acts.SetX,
		C3.Plugins.Touch.Cnds.OnTapGesture,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Sprite.Cnds.IsOnScreen,
		C3.Plugins.Particles.Acts.SetPosToObject,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Audio.Acts.SetMuted,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Acts.GetItem,
		C3.Plugins.LocalStorage.Cnds.OnItemGet,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.Spritefont2.Acts.SetText,
		C3.JavaScriptInEvents.Game_sht_Event1_Act9,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Touch.Cnds.OnTouchStart,
		C3.Plugins.Sprite.Cnds.CompareX,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Behaviors.Pin.Acts.Pin,
		C3.Plugins.TiledBg.Acts.Destroy,
		C3.Plugins.Sprite.Cnds.IsOutsideLayout,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Cnds.OnDestroyed,
		C3.Plugins.Sprite.Cnds.IsVisible,
		C3.Behaviors.Bullet.Acts.SetEnabled,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.Particles.Acts.Destroy,
		C3.Plugins.System.Acts.AddVar,
		C3.JavaScriptInEvents.Game_sht_Event46_Act1,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Spritefont2.Acts.SetVisible,
		C3.Plugins.System.Acts.RestartLayout,
		C3.JavaScriptInEvents.Gui_Event3_Act2,
		C3.Plugins.Browser.Acts.GoToURLWindow
	];
};
self.C3_JsPropNameTable = [
	{Platform: 0},
	{ball: 0},
	{create: 0},
	{Var: 0},
	{Bullet: 0},
	{bar: 0},
	{Touch: 0},
	{Solid: 0},
	{Background: 0},
	{BLUE: 0},
	{green: 0},
	{Yellow: 0},
	{RED: 0},
	{Particles: 0},
	{SCORE: 0},
	{Fichier: 0},
	{Sine: 0},
	{Fichier4: 0},
	{RATE: 0},
	{MoreGames: 0},
	{Fb: 0},
	{Browser: 0},
	{Audio: 0},
	{TiledBackground: 0},
	{mute: 0},
	{LocalStorage: 0},
	{HighScore: 0},
	{Fichier3: 0},
	{Fichier2: 0},
	{Replay: 0},
	{Particles2: 0},
	{Advert: 0},
	{Pin: 0},
	{COLORS: 0},
	{GUI: 0},
	{MUSIC: 0},
	{ANIMATION: 0},
	{UserId: 0},
	{y: 0},
	{CREATE: 0},
	{inter: 0}
];

self.InstanceType = {
	ball: class extends self.ISpriteInstance {},
	bar: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {},
	Background: class extends self.ITiledBackgroundInstance {},
	BLUE: class extends self.ITiledBackgroundInstance {},
	green: class extends self.ITiledBackgroundInstance {},
	Yellow: class extends self.ITiledBackgroundInstance {},
	RED: class extends self.ITiledBackgroundInstance {},
	Particles: class extends self.IParticlesInstance {},
	SCORE: class extends self.ISpriteFontInstance {},
	Fichier: class extends self.ISpriteInstance {},
	Fichier4: class extends self.ISpriteInstance {},
	RATE: class extends self.ISpriteInstance {},
	MoreGames: class extends self.ISpriteInstance {},
	Fb: class extends self.ISpriteInstance {},
	Browser: class extends self.IInstance {},
	Audio: class extends self.IInstance {},
	TiledBackground: class extends self.ITiledBackgroundInstance {},
	mute: class extends self.ISpriteInstance {},
	LocalStorage: class extends self.IInstance {},
	HighScore: class extends self.ISpriteFontInstance {},
	Fichier3: class extends self.ISpriteInstance {},
	Fichier2: class extends self.ISpriteInstance {},
	Replay: class extends self.ISpriteInstance {},
	Particles2: class extends self.IParticlesInstance {},
	Advert: class extends self.IInstance {},
	COLORS: class extends self.ITiledBackgroundInstance {},
	GUI: class extends self.ISpriteInstance {}
}