const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Rotate,
		C3.Behaviors.Sin,
		C3.Plugins.TiledBg,
		C3.Behaviors.Bullet,
		C3.Plugins.Audio,
		C3.Plugins.Browser,
		C3.Plugins.Keyboard,
		C3.Plugins.Mouse,
		C3.Plugins.Touch,
		C3.Plugins.LocalStorage,
		C3.Behaviors.Pin,
		C3.Behaviors.scrollto,
		C3.Behaviors.Fade,
		C3.Plugins.Spritefont2,
		C3.Behaviors.EightDir,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Acts.SetGroupActive,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Spritefont2.Acts.SetPos,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Behaviors.Bullet.Acts.SetSpeed,
		C3.Plugins.Spritefont2.Acts.SetText,
		C3.Plugins.Sprite.Acts.SetHeight,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Acts.SetPosToObject,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Acts.MoveToBottom,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.TiledBg.Cnds.CompareX,
		C3.Plugins.TiledBg.Exps.Width,
		C3.Plugins.TiledBg.Acts.SetX,
		C3.Plugins.TiledBg.Exps.X,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Sprite.Cnds.OnAnimFinished,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Exps.random,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Behaviors.Pin.Acts.Pin,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Plugins.Sprite.Cnds.CompareX,
		C3.Behaviors.EightDir.Acts.SimulateControl,
		C3.Behaviors.Sin.Acts.SetEnabled,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Sprite.Cnds.CompareY,
		C3.Plugins.Sprite.Cnds.CompareHeight,
		C3.Plugins.Sprite.Exps.Angle,
		C3.Plugins.Sprite.Exps.Height,
		C3.Plugins.System.Cnds.Else,
		C3.JavaScriptInEvents.Game_events_Event116_Act17,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.System.Exps.projectname,
		C3.Plugins.Spritefont2.Acts.SetVisible,
		C3.Plugins.Audio.Acts.Preload,
		C3.Plugins.System.Exps.loadingprogress,
		C3.Plugins.System.Cnds.OnLoadFinished,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.JavaScriptInEvents.Global_events_Event1_Act4,
		C3.Plugins.Spritefont2.Cnds.CompareInstanceVar,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.LocalStorage.Cnds.OnItemMissing,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.System.Exps.viewportleft,
		C3.Plugins.Sprite.Exps.LayerName,
		C3.Plugins.System.Exps.viewportright,
		C3.Plugins.System.Exps.originalwindowwidth,
		C3.Plugins.LocalStorage.Cnds.IsProcessingGets,
		C3.Plugins.Touch.Exps.X,
		C3.Plugins.System.Exps.log10,
		C3.Plugins.Audio.Acts.SetVolume,
		C3.Plugins.Sprite.Acts.SetWidth,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.JavaScriptInEvents.Global_events_Event59_Act1,
		C3.Plugins.System.Acts.WaitForSignal,
		C3.Plugins.System.Acts.GoToLayout,
		C3.JavaScriptInEvents.Global_events_Event61_Act1,
		C3.Plugins.System.Acts.SetTimescale,
		C3.JavaScriptInEvents.Global_events_Event63_Act1,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.System.Exps.choose,
		C3.Behaviors.Bullet.Cnds.CompareTravelled,
		C3.Plugins.Browser.Acts.RequestFullScreen,
		C3.Plugins.Browser.Acts.CancelFullScreen,
		C3.Plugins.Mouse.Cnds.IsButtonDown,
		C3.Plugins.Mouse.Acts.SetCursorSprite,
		C3.Plugins.Mouse.Cnds.IsOverObject,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.JavaScriptInEvents.Global_events_Event112_Act1,
		C3.Plugins.Sprite.Cnds.CompareAnimSpeed,
		C3.Plugins.Sprite.Acts.StartAnim,
		C3.JavaScriptInEvents.Global_events_Event120_Act22,
		C3.JavaScriptInEvents.Global_events_Event122_Act3,
		C3.Plugins.Browser.Acts.Close,
		C3.Plugins.System.Acts.SetLayerOpacity,
		C3.Plugins.System.Cnds.LayerCmpOpacity,
		C3.Plugins.System.Exps.layeropacity,
		C3.Plugins.System.Acts.Signal,
		C3.JavaScriptInEvents.Global_events_Event131
	];
};
self.C3_JsPropNameTable = [
	{Cursor: 0},
	{CursorHover: 0},
	{Rotate: 0},
	{SunLight: 0},
	{Name: 0},
	{Audio_Line: 0},
	{FramePaused: 0},
	{Slider_Music: 0},
	{Sine: 0},
	{Paused: 0},
	{Frame_Audio_Background: 0},
	{Frame_Audio: 0},
	{Slider_Sound: 0},
	{NeedWorms: 0},
	{TimeOver: 0},
	{FrameBottom: 0},
	{FrameTop: 0},
	{LevelUp: 0},
	{FrameLevelUp: 0},
	{GameOver: 0},
	{FrameGameOver: 0},
	{Winner: 0},
	{YouWin: 0},
	{FrameInfo: 0},
	{GameLogo: 0},
	{GameIcon: 0},
	{Bullet: 0},
	{Sky: 0},
	{Collision: 0},
	{BubbleCollision: 0},
	{ID: 0},
	{FishMenuSpawn: 0},
	{FishMenu: 0},
	{FishInfo_1: 0},
	{FishInfo_2: 0},
	{FishInfo_3: 0},
	{FishInfo_4: 0},
	{FishInfo_5: 0},
	{SeaHorseInfo: 0},
	{SeaShellInfo: 0},
	{SeaStarInfo: 0},
	{SharkInfo: 0},
	{BubbleTreasureInfo: 0},
	{BubbleBombInfo: 0},
	{Gift: 0},
	{BubbleGiftInfo: 0},
	{BubbleWormInfo: 0},
	{BubbleTimeInfo: 0},
	{Audio: 0},
	{Browser: 0},
	{Keyboard: 0},
	{Mouse: 0},
	{Touch: 0},
	{LocalStorage: 0},
	{Hook: 0},
	{Pin: 0},
	{Fish: 0},
	{FishingLine: 0},
	{FishID: 0},
	{Turn: 0},
	{FishHook: 0},
	{HookColl: 0},
	{Shark: 0},
	{BubbleTime: 0},
	{BubbleBomb: 0},
	{BubbleGift: 0},
	{BubbleTreasure: 0},
	{Plumb: 0},
	{Worm: 0},
	{BubbleExplosion: 0},
	{Bomb: 0},
	{BombExplosion: 0},
	{BubbleWorm: 0},
	{Catch_10: 0},
	{Catch_18: 0},
	{Catch_12: 0},
	{Catch_50: 0},
	{Catch_14: 0},
	{Catch_16: 0},
	{AddBombs1: 0},
	{AddWorms10: 0},
	{SeaStar: 0},
	{SeaShell: 0},
	{Sine2: 0},
	{SeaHorse: 0},
	{Catch_6: 0},
	{Catch_8: 0},
	{Catch_20: 0},
	{AddSeconds30: 0},
	{AddScore50: 0},
	{AddScore100: 0},
	{ScrollTo: 0},
	{Boat: 0},
	{Background: 0},
	{Ground: 0},
	{FishingNet: 0},
	{PlayerBody: 0},
	{PlayerHead: 0},
	{PlayerHandPaddle: 0},
	{PlayerHandRod: 0},
	{Fade: 0},
	{Bubble: 0},
	{Seaweed_1: 0},
	{Seaweed_4: 0},
	{Seaweed_5: 0},
	{Seaweed_7: 0},
	{Seaweed_6: 0},
	{Seaweed_3: 0},
	{Seaweed_2: 0},
	{Underwater: 0},
	{LastScoreFont: 0},
	{ScoreFont: 0},
	{BestScoreFont: 0},
	{TimeFont: 0},
	{MusicFont: 0},
	{SoundFont: 0},
	{LoadingFont: 0},
	{TargetFont: 0},
	{LevelFont: 0},
	{BombsFont: 0},
	{WormsFont: 0},
	{LevelBonusFont: 0},
	{TextFont: 0},
	{GameOverFont: 0},
	{GameInfoFont: 0},
	{InfoFont: 0},
	{Button_Exit: 0},
	{Button_Fullscreen: 0},
	{Button_Play: 0},
	{Button_Info: 0},
	{Button_Menu: 0},
	{Button_Music: 0},
	{Button_Pause: 0},
	{Button_Restart: 0},
	{Button_Return: 0},
	{Button_Sound: 0},
	{Button_Start: 0},
	{Button_Down: 0},
	{Button_Left: 0},
	{Button_Right: 0},
	{Button_Bomb: 0},
	{Button_Go: 0},
	{Buttons: 0},
	{"8Direction": 0},
	{Player: 0},
	{Bubbles: 0},
	{ScoreObjects: 0},
	{Level: 0},
	{Score: 0},
	{Catch: 0},
	{Bombs: 0},
	{Worms: 0},
	{Caught: 0},
	{Seconds: 0},
	{Minutes: 0},
	{LastScore: 0},
	{BestScore: 0},
	{CountScore: 0},
	{CountWorms: 0},
	{UserId: 0},
	{CountSeconds: 0},
	{Pause: 0},
	{Fullscreen: 0},
	{Sound: 0},
	{Sound_Status: 0},
	{Sound_Volume: 0},
	{Music: 0},
	{Music_Status: 0},
	{Music_Volume: 0},
	{Audio_Line_Width: 0}
];

self.InstanceType = {
	Cursor: class extends self.ISpriteInstance {},
	CursorHover: class extends self.ISpriteInstance {},
	SunLight: class extends self.ISpriteInstance {},
	Audio_Line: class extends self.ISpriteInstance {},
	FramePaused: class extends self.ISpriteInstance {},
	Slider_Music: class extends self.ISpriteInstance {},
	Paused: class extends self.ISpriteInstance {},
	Frame_Audio_Background: class extends self.ISpriteInstance {},
	Frame_Audio: class extends self.ISpriteInstance {},
	Slider_Sound: class extends self.ISpriteInstance {},
	NeedWorms: class extends self.ISpriteInstance {},
	TimeOver: class extends self.ISpriteInstance {},
	FrameBottom: class extends self.ISpriteInstance {},
	FrameTop: class extends self.ISpriteInstance {},
	LevelUp: class extends self.ISpriteInstance {},
	FrameLevelUp: class extends self.ISpriteInstance {},
	GameOver: class extends self.ISpriteInstance {},
	FrameGameOver: class extends self.ISpriteInstance {},
	Winner: class extends self.ISpriteInstance {},
	YouWin: class extends self.ISpriteInstance {},
	FrameInfo: class extends self.ISpriteInstance {},
	GameLogo: class extends self.ISpriteInstance {},
	GameIcon: class extends self.ISpriteInstance {},
	Sky: class extends self.ITiledBackgroundInstance {},
	Collision: class extends self.ISpriteInstance {},
	BubbleCollision: class extends self.ISpriteInstance {},
	FishMenuSpawn: class extends self.ISpriteInstance {},
	FishMenu: class extends self.ISpriteInstance {},
	FishInfo_1: class extends self.ISpriteInstance {},
	FishInfo_2: class extends self.ISpriteInstance {},
	FishInfo_3: class extends self.ISpriteInstance {},
	FishInfo_4: class extends self.ISpriteInstance {},
	FishInfo_5: class extends self.ISpriteInstance {},
	SeaHorseInfo: class extends self.ISpriteInstance {},
	SeaShellInfo: class extends self.ISpriteInstance {},
	SeaStarInfo: class extends self.ISpriteInstance {},
	SharkInfo: class extends self.ISpriteInstance {},
	BubbleTreasureInfo: class extends self.ISpriteInstance {},
	BubbleBombInfo: class extends self.ISpriteInstance {},
	BubbleGiftInfo: class extends self.ISpriteInstance {},
	BubbleWormInfo: class extends self.ISpriteInstance {},
	BubbleTimeInfo: class extends self.ISpriteInstance {},
	Audio: class extends self.IInstance {},
	Browser: class extends self.IInstance {},
	Keyboard: class extends self.IInstance {},
	Mouse: class extends self.IInstance {},
	Touch: class extends self.IInstance {},
	LocalStorage: class extends self.IInstance {},
	Hook: class extends self.ISpriteInstance {},
	Fish: class extends self.ISpriteInstance {},
	FishingLine: class extends self.ISpriteInstance {},
	FishHook: class extends self.ISpriteInstance {},
	HookColl: class extends self.ISpriteInstance {},
	Shark: class extends self.ISpriteInstance {},
	BubbleTime: class extends self.ISpriteInstance {},
	BubbleBomb: class extends self.ISpriteInstance {},
	BubbleGift: class extends self.ISpriteInstance {},
	BubbleTreasure: class extends self.ISpriteInstance {},
	Plumb: class extends self.ISpriteInstance {},
	Worm: class extends self.ISpriteInstance {},
	BubbleExplosion: class extends self.ISpriteInstance {},
	Bomb: class extends self.ISpriteInstance {},
	BombExplosion: class extends self.ISpriteInstance {},
	BubbleWorm: class extends self.ISpriteInstance {},
	Catch_10: class extends self.ISpriteInstance {},
	Catch_18: class extends self.ISpriteInstance {},
	Catch_12: class extends self.ISpriteInstance {},
	Catch_50: class extends self.ISpriteInstance {},
	Catch_14: class extends self.ISpriteInstance {},
	Catch_16: class extends self.ISpriteInstance {},
	AddBombs1: class extends self.ISpriteInstance {},
	AddWorms10: class extends self.ISpriteInstance {},
	SeaStar: class extends self.ISpriteInstance {},
	SeaShell: class extends self.ISpriteInstance {},
	SeaHorse: class extends self.ISpriteInstance {},
	Catch_6: class extends self.ISpriteInstance {},
	Catch_8: class extends self.ISpriteInstance {},
	Catch_20: class extends self.ISpriteInstance {},
	AddSeconds30: class extends self.ISpriteInstance {},
	AddScore50: class extends self.ISpriteInstance {},
	AddScore100: class extends self.ISpriteInstance {},
	Boat: class extends self.ISpriteInstance {},
	Background: class extends self.ITiledBackgroundInstance {},
	Ground: class extends self.ITiledBackgroundInstance {},
	FishingNet: class extends self.ISpriteInstance {},
	PlayerBody: class extends self.ISpriteInstance {},
	PlayerHead: class extends self.ISpriteInstance {},
	PlayerHandPaddle: class extends self.ISpriteInstance {},
	PlayerHandRod: class extends self.ISpriteInstance {},
	Bubble: class extends self.ISpriteInstance {},
	Seaweed_1: class extends self.ISpriteInstance {},
	Seaweed_4: class extends self.ISpriteInstance {},
	Seaweed_5: class extends self.ISpriteInstance {},
	Seaweed_7: class extends self.ISpriteInstance {},
	Seaweed_6: class extends self.ISpriteInstance {},
	Seaweed_3: class extends self.ISpriteInstance {},
	Seaweed_2: class extends self.ISpriteInstance {},
	Underwater: class extends self.ITiledBackgroundInstance {},
	LastScoreFont: class extends self.ISpriteFontInstance {},
	ScoreFont: class extends self.ISpriteFontInstance {},
	BestScoreFont: class extends self.ISpriteFontInstance {},
	TimeFont: class extends self.ISpriteFontInstance {},
	MusicFont: class extends self.ISpriteFontInstance {},
	SoundFont: class extends self.ISpriteFontInstance {},
	LoadingFont: class extends self.ISpriteFontInstance {},
	TargetFont: class extends self.ISpriteFontInstance {},
	LevelFont: class extends self.ISpriteFontInstance {},
	BombsFont: class extends self.ISpriteFontInstance {},
	WormsFont: class extends self.ISpriteFontInstance {},
	LevelBonusFont: class extends self.ISpriteFontInstance {},
	TextFont: class extends self.ISpriteFontInstance {},
	GameOverFont: class extends self.ISpriteFontInstance {},
	GameInfoFont: class extends self.ISpriteFontInstance {},
	InfoFont: class extends self.ISpriteFontInstance {},
	Button_Exit: class extends self.ISpriteInstance {},
	Button_Fullscreen: class extends self.ISpriteInstance {},
	Button_Play: class extends self.ISpriteInstance {},
	Button_Info: class extends self.ISpriteInstance {},
	Button_Menu: class extends self.ISpriteInstance {},
	Button_Music: class extends self.ISpriteInstance {},
	Button_Pause: class extends self.ISpriteInstance {},
	Button_Restart: class extends self.ISpriteInstance {},
	Button_Return: class extends self.ISpriteInstance {},
	Button_Sound: class extends self.ISpriteInstance {},
	Button_Start: class extends self.ISpriteInstance {},
	Button_Down: class extends self.ISpriteInstance {},
	Button_Left: class extends self.ISpriteInstance {},
	Button_Right: class extends self.ISpriteInstance {},
	Button_Bomb: class extends self.ISpriteInstance {},
	Button_Go: class extends self.ISpriteInstance {},
	Buttons: class extends self.ISpriteInstance {},
	Player: class extends self.ISpriteInstance {},
	Bubbles: class extends self.ISpriteInstance {},
	ScoreObjects: class extends self.ISpriteInstance {}
}