const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Touch,
		C3.Plugins.Sprite,
		C3.Behaviors.Physics,
		C3.Behaviors.Platform,
		C3.Behaviors.Rotate,
		C3.Plugins.TiledBg,
		C3.Behaviors.solid,
		C3.Plugins.Text,
		C3.Plugins.Audio,
		C3.Plugins.Spritefont2,
		C3.Plugins.LocalStorage,
		C3.Plugins.advert,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.advert.Acts.CreateBanner,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.System.Exps.viewporttop,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.Touch.Cnds.OnTapGesture,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Acts.GoToLayout,
		C3.JavaScriptInEvents.Start_Event2_Act5,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.Spritefont2.Acts.SetY,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.Sprite.Cnds.IsVisible,
		C3.Plugins.System.Cnds.Else,
		C3.JavaScriptInEvents.Bottles_Event4_Act2,
		C3.Plugins.Touch.Cnds.OnTouchStart,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.Sprite.Exps.AnimationFrame,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Spritefont2.Acts.SetText,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Text.Cnds.IsVisible,
		C3.Plugins.Text.Exps.Text,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Behaviors.Physics.Acts.SetWorldGravity,
		C3.Behaviors.Physics.Acts.SetSteppingMode,
		C3.Behaviors.Physics.Acts.SetIterations,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.System.Acts.RestartLayout,
		C3.JavaScriptInEvents.Game_Event4_Act2,
		C3.Behaviors.Platform.Cnds.IsOnFloor,
		C3.Plugins.Sprite.Exps.Angle,
		C3.Plugins.Sprite.Cnds.IsBetweenAngles,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.advert.Acts.ShowInterstitial,
		C3.Plugins.System.Cnds.Every,
		C3.JavaScriptInEvents.Game_Event19_Act2,
		C3.Plugins.Touch.Exps.Y,
		C3.Plugins.Touch.Cnds.IsInTouch,
		C3.Plugins.Touch.Cnds.OnTouchEnd,
		C3.Plugins.Touch.Exps.SpeedAt,
		C3.Behaviors.Platform.Acts.SetJumpStrength,
		C3.Behaviors.Platform.Acts.SimulateControl,
		C3.Behaviors.Platform.Cnds.OnLand,
		C3.Behaviors.Rotate.Acts.SetSpeed,
		C3.Plugins.Sprite.Cnds.IsCollisionEnabled,
		C3.Behaviors.Platform.Cnds.OnJump,
		C3.Plugins.advert.Acts.CreateInterstitial,
		C3.Plugins.advert.Cnds.IsBannerLoaded,
		C3.Plugins.advert.Acts.ShowBanner,
		C3.Plugins.System.Cnds.OnLayoutEnd
	];
};
self.C3_JsPropNameTable = [
	{Touch: 0},
	{Physics: 0},
	{Platform: 0},
	{Rotate: 0},
	{bottle: 0},
	{R: 0},
	{L: 0},
	{START: 0},
	{BG3: 0},
	{BACK: 0},
	{Solid: 0},
	{table: 0},
	{TiledBackground: 0},
	{TiledBackground2: 0},
	{BUY: 0},
	{tittle: 0},
	{BUY_text: 0},
	{COIN: 0},
	{PLAY: 0},
	{Audio: 0},
	{BG: 0},
	{Score: 0},
	{LocalStorage: 0},
	{MobileAdvert: 0},
	{More_games: 0},
	{B6: 0},
	{B7: 0},
	{B8: 0},
	{B9: 0},
	{B10: 0},
	{B11: 0},
	{B12: 0},
	{touch1: 0},
	{touch2: 0},
	{touchY: 0},
	{touch_time: 0},
	{touch_speed: 0},
	{BATTELE_ANGLE: 0},
	{BATTELE_ANGLE2: 0},
	{SCORE: 0},
	{SCORE_STOP: 0},
	{SLIDE: 0},
	{banner: 0},
	{INTER: 0}
];

self.InstanceType = {
	Touch: class extends self.IInstance {},
	bottle: class extends self.ISpriteInstance {},
	R: class extends self.ISpriteInstance {},
	L: class extends self.ISpriteInstance {},
	START: class extends self.ISpriteInstance {},
	BG3: class extends self.ITiledBackgroundInstance {},
	BACK: class extends self.ISpriteInstance {},
	table: class extends self.ISpriteInstance {},
	TiledBackground: class extends self.ITiledBackgroundInstance {},
	TiledBackground2: class extends self.ITiledBackgroundInstance {},
	BUY: class extends self.ISpriteInstance {},
	tittle: class extends self.ISpriteInstance {},
	BUY_text: class extends self.ITextInstance {},
	COIN: class extends self.ISpriteInstance {},
	PLAY: class extends self.ISpriteInstance {},
	Audio: class extends self.IInstance {},
	BG: class extends self.ISpriteInstance {},
	Score: class extends self.ISpriteFontInstance {},
	LocalStorage: class extends self.IInstance {},
	MobileAdvert: class extends self.IInstance {}
}