const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Arr,
		C3.Plugins.Browser,
		C3.Plugins.Function,
		C3.Plugins.Mouse,
		C3.Plugins.Audio,
		C3.Plugins.Touch,
		C3.Plugins.LocalStorage,
		C3.Plugins.Spritefont2,
		C3.Plugins.Sprite,
		C3.Behaviors.Fade,
		C3.Behaviors.Sin,
		C3.Behaviors.Rotate,
		C3.Behaviors.Bullet,
		C3.Behaviors.wrap,
		C3.Plugins.TiledBg,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Acts.SetTimescale,
		C3.Plugins.System.Acts.SetGroupActive,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.System.Exps.projectname,
		C3.JavaScriptInEvents.Game_events_Event1_Act13,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.Spritefont2.Acts.SetText,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Acts.MoveAtAngle,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.Arr.Acts.SetXY,
		C3.Plugins.Sprite.Exps.UID,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.System.Cnds.CompareBetween,
		C3.Plugins.Arr.Exps.At,
		C3.Plugins.Touch.Cnds.OnTouchEnd,
		C3.Plugins.Arr.Cnds.CompareXY,
		C3.Plugins.Arr.Acts.Clear,
		C3.Plugins.Function.Acts.CallFunction,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Cnds.CompareX,
		C3.Plugins.Sprite.Cnds.CompareY,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.System.Exps.int,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.System.Exps.dt,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.Function.Cnds.OnFunction,
		C3.Plugins.Arr.Cnds.ArrForEach,
		C3.Plugins.Arr.Cnds.CompareCurrent,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Arr.Exps.CurY,
		C3.Plugins.Sprite.Acts.SetCollisions,
		C3.Plugins.Arr.Exps.CurX,
		C3.Plugins.Arr.Acts.SetXYZ,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.System.Cnds.For,
		C3.Plugins.Function.Exps.Param,
		C3.Plugins.System.Exps.loopindex,
		C3.Plugins.System.Exps.layoutheight,
		C3.Plugins.Sprite.Acts.MoveToBottom,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.System.Acts.AddVar,
		C3.Behaviors.Fade.Acts.StartFade,
		C3.Plugins.System.Cnds.Repeat,
		C3.Plugins.Arr.Cnds.Contains,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.Sprite.Cnds.PickByUID,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Exps.layoutwidth,
		C3.Plugins.Arr.Acts.SetSize,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.TiledBg.Acts.SetHeight,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.JavaScriptInEvents.Game_events_Event87_Act3,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Cnds.OnLoadFinished,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.Browser.Acts.RequestFullScreen,
		C3.Plugins.Browser.Acts.CancelFullScreen,
		C3.Plugins.Mouse.Cnds.IsOverObject,
		C3.Behaviors.Sin.Acts.SetEnabled,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.System.Acts.WaitForSignal,
		C3.JavaScriptInEvents.Global_events_Event33_Act6,
		C3.Plugins.System.Acts.RestartLayout,
		C3.JavaScriptInEvents.Global_events_Event34_Act6,
		C3.JavaScriptInEvents.Global_events_Event35_Act7,
		C3.JavaScriptInEvents.Global_events_Event36_Act2,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.System.Acts.SetLayerOpacity,
		C3.Plugins.System.Cnds.LayerCmpOpacity,
		C3.Plugins.System.Exps.layeropacity,
		C3.Plugins.System.Acts.Signal,
		C3.Plugins.Browser.Acts.Close,
		C3.JavaScriptInEvents.Global_events_Event59_Act4,
		C3.Plugins.Audio.Acts.Preload
	];
};
self.C3_JsPropNameTable = [
	{Array: 0},
	{Browser: 0},
	{Function: 0},
	{SwapData: 0},
	{Mouse: 0},
	{Audio: 0},
	{Touch: 0},
	{LocalStorage: 0},
	{BestScoreFont: 0},
	{BlocksFont: 0},
	{LastScoreFont: 0},
	{LevelsFont: 0},
	{MovesFont: 0},
	{ScoreFont: 0},
	{TimerFont: 0},
	{BtnExit: 0},
	{BtnFullscreen: 0},
	{BtnMusic: 0},
	{BtnPause: 0},
	{BtnRestart: 0},
	{BtnMenu: 0},
	{BtnSound: 0},
	{BtnPlay: 0},
	{Matched: 0},
	{Moving: 0},
	{trigger: 0},
	{targetY: 0},
	{row: 0},
	{col: 0},
	{dy: 0},
	{color: 0},
	{State: 0},
	{Fade: 0},
	{Sine: 0},
	{Sine2: 0},
	{Elements: 0},
	{BOOM: 0},
	{ChessMap: 0},
	{Marker: 0},
	{Rotate: 0},
	{Selection: 0},
	{Selector: 0},
	{ScoreCollision: 0},
	{Selector2: 0},
	{Background: 0},
	{ElementStartMenu: 0},
	{Bullet: 0},
	{Wrap: 0},
	{ElementStartMenu2: 0},
	{ElementStartMenu3: 0},
	{ElementStartMenu4: 0},
	{ElementStartMenu5: 0},
	{ElementStartMenu6: 0},
	{GameLogo: 0},
	{GuiFrame: 0},
	{GuiFrame2: 0},
	{GuiFrame3: 0},
	{Speed: 0},
	{MiniCoin: 0},
	{Sun: 0},
	{TimerGui: 0},
	{TimerLine: 0},
	{Buttons: 0},
	{MiniJelly: 0},
	{CX: 0},
	{CY: 0},
	{Level: 0},
	{Score: 0},
	{Blocks: 0},
	{Moves: 0},
	{Trigger: 0},
	{Minutes: 0},
	{Matches: 0},
	{ScoreBar: 0},
	{Seconds: 0},
	{LastScore: 0},
	{BestScore: 0},
	{FirstPiece: 0},
	{UserId: 0},
	{MovingBlocks: 0},
	{TILE: 0},
	{Music: 0},
	{Sound: 0},
	{Fullscreen: 0},
	{TimeScaler: 0}
];

self.InstanceType = {
	Array: class extends self.IArrayInstance {},
	Browser: class extends self.IInstance {},
	Function: class extends self.IInstance {},
	SwapData: class extends self.IArrayInstance {},
	Mouse: class extends self.IInstance {},
	Audio: class extends self.IInstance {},
	Touch: class extends self.IInstance {},
	LocalStorage: class extends self.IInstance {},
	BestScoreFont: class extends self.ISpriteFontInstance {},
	BlocksFont: class extends self.ISpriteFontInstance {},
	LastScoreFont: class extends self.ISpriteFontInstance {},
	LevelsFont: class extends self.ISpriteFontInstance {},
	MovesFont: class extends self.ISpriteFontInstance {},
	ScoreFont: class extends self.ISpriteFontInstance {},
	TimerFont: class extends self.ISpriteFontInstance {},
	BtnExit: class extends self.ISpriteInstance {},
	BtnFullscreen: class extends self.ISpriteInstance {},
	BtnMusic: class extends self.ISpriteInstance {},
	BtnPause: class extends self.ISpriteInstance {},
	BtnRestart: class extends self.ISpriteInstance {},
	BtnMenu: class extends self.ISpriteInstance {},
	BtnSound: class extends self.ISpriteInstance {},
	BtnPlay: class extends self.ISpriteInstance {},
	Elements: class extends self.ISpriteInstance {},
	BOOM: class extends self.ISpriteInstance {},
	ChessMap: class extends self.ISpriteInstance {},
	Marker: class extends self.ISpriteInstance {},
	Selection: class extends self.ISpriteInstance {},
	Selector: class extends self.ISpriteInstance {},
	ScoreCollision: class extends self.ISpriteInstance {},
	Selector2: class extends self.ISpriteInstance {},
	Background: class extends self.ISpriteInstance {},
	ElementStartMenu: class extends self.ISpriteInstance {},
	ElementStartMenu2: class extends self.ISpriteInstance {},
	ElementStartMenu3: class extends self.ISpriteInstance {},
	ElementStartMenu4: class extends self.ISpriteInstance {},
	ElementStartMenu5: class extends self.ISpriteInstance {},
	ElementStartMenu6: class extends self.ISpriteInstance {},
	GameLogo: class extends self.ISpriteInstance {},
	GuiFrame: class extends self.ISpriteInstance {},
	GuiFrame2: class extends self.ISpriteInstance {},
	GuiFrame3: class extends self.ISpriteInstance {},
	MiniCoin: class extends self.ISpriteInstance {},
	Sun: class extends self.ISpriteInstance {},
	TimerGui: class extends self.ISpriteInstance {},
	TimerLine: class extends self.ITiledBackgroundInstance {},
	Buttons: class extends self.ISpriteInstance {},
	MiniJelly: class extends self.ISpriteInstance {}
}